const _orig = new Map();
const TRAD_KAB_SITE = {
  'Le portail N°1 de la':'ⴰⵎⵙⴻⴳⵏⵓ ⴰⵎⴻⵣⵡⴰⵔⵓ ⵏ',
  'diaspora algérienne':'ⵜⴰⵙⴻⴼⵙⵉⵜ ⵜⴰⵣⵣⴰⵢⵔⵉⵜ',
  'Visibilité internationale, annonces immobilières, annuaire professionnel, alertes transport en temps réel — tout ce dont la communauté algérienne a besoin, en un seul endroit.':'ⵜⵉⵣⵔⴰⵡⵉⵏ ⵜⵉⵎⴻⵇⵔⴰⵏⵉⵏ, ⵜⵉⵎⴻⵙⵏⴰⴷⵉⵏ, ⵉⵏⵣⴻⵔⴼⴰⵏ ⵏ ⵜⴰⵏⴻⵇⵇⴰⵍⵜ — ⴰⴽⴽ ⴰⵢ ⵉⵍⴰⵇ ⵜⴰⵙⴻⴼⵙⵉⵜ ⵜⴰⵣⵣⴰⵢⵔⵉⵜ.',
  '(app DZ Diaspora)':'(ⴰⴱⴱ ⴷⵣ ⴷⵉⴰⵙⴱⵓⵔⴰ)',
  '(offres, promesses, justificatifs) — ils serviront en cas de litige':'(ⵓⴼⴼⵔⴻⵙ, ⴱⵔⵓⵎⴻⵙⵙⴻⵙ, ⵊⵓⵙⵜⵉⴼⵉⵙⴰⵜⵉⴼⵙ) — ⵉⵍⵙ ⵙⴻⵔⴼⵉⵔⵓⵏⵜ ⴻⵏ ⵙⴰⵙ ⴷⴻ ⵍⵉⵜⵉⴳⴻ',
  '(recommandé — toujours actif)':'(ⵔⴻⵙⵓⵎⵎⴰⵏⴷⴻ — ⵜⵓⵓⵊⵓⵓⵔⵙ ⴰⵙⵜⵉⴼ)',
  '(via votre numéro)':'(ⴼⵉⴰ ⴼⵓⵜⵔⴻ ⵏⵓⵎⴻⵔⵓ)',
  '* +213 (0) 799 87 28 90 — virement bancaire uniquement':'* +213 (0) 799 87 28 90 — ⴼⵉⵔⴻⵎⴻⵏⵜ ⴱⴰⵏⵙⴰⵉⵔⴻ ⵓⵏⵉⵇⵓⴻⵎⴻⵏⵜ',
  '* Virement bancaire uniquement':'* ⴼⵉⵔⴻⵎⴻⵏⵜ ⴱⴰⵏⵙⴰⵉⵔⴻ ⵓⵏⵉⵇⵓⴻⵎⴻⵏⵜ',
  '* Virement bancaire uniquement — NET-HABITA':'* ⴼⵉⵔⴻⵎⴻⵏⵜ ⴱⴰⵏⵙⴰⵉⵔⴻ ⵓⵏⵉⵇⵓⴻⵎⴻⵏⵜ — ⵏⴻⵜ-ⵀⴰⴱⵉⵜⴰ',
  '+ Nouvelle demande':'+ ⵏⵓⵓⴼⴻⵍⵍⴻ ⴷⴻⵎⴰⵏⴷⴻ',
  ', puis activez':', ⴱⵓⵉⵙ ⴰⵙⵜⵉⴼⴻⵣ',
  '-- Budget mensuel envisagé --':'-- ⴱⵓⴷⴳⴻⵜ ⵎⴻⵏⵙⵓⴻⵍ ⴻⵏⴼⵉⵙⴰⴳⴻ --',
  '-- Choisir une specialite --':'-- ⵙⵀⵓⵉⵙⵉⵔ ⵓⵏⴻ ⵙⴱⴻⵙⵉⴰⵍⵉⵜⴻ --',
  '-- Choisir une wilaya --':'-- ⵙⵀⵓⵉⵙⵉⵔ ⵓⵏⴻ ⵡⵉⵍⴰⵢⴰ --',
  '-- Format publicitaire souhaité --':'-- ⴼⵓⵔⵎⴰⵜ ⴱⵓⴱⵍⵉⵙⵉⵜⴰⵉⵔⴻ ⵙⵓⵓⵀⴰⵉⵜⴻ --',
  '-- Non vérifié --':'-- ⵏⵓⵏ ⴼⴻⵔⵉⴼⵉⴻ --',
  '-- Selectionnez --':'-- ⵙⴻⵍⴻⵙⵜⵉⵓⵏⵏⴻⵣ --',
  '-- Sélectionnez --':'-- ⵙⴻⵍⴻⵙⵜⵉⵓⵏⵏⴻⵣ --',
  '-- Tous les types --':'-- ⵜⵓⵓⵙ ⵍⴻⵙ ⵜⵢⴱⴻⵙ --',
  '-- Toutes les wilayas --':'-- ⵜⵓⵓⵜⴻⵙ ⵍⴻⵙ ⵡⵉⵍⴰⵢⴰⵙ --',
  '-- Wilaya --':'-- ⵡⵉⵍⴰⵢⴰ --',
  '1 MOIS — 20€':'1 ⵎⵓⵉⵙ — 20€',
  '1 annonce par jour pendant 7 jours. Ideal pour une vente ponctuelle.':'1 ⴰⵏⵏⵓⵏⵙⴻ ⴱⴰⵔ ⵊⵓⵓⵔ ⴱⴻⵏⴷⴰⵏⵜ 7 ⵊⵓⵓⵔⵙ. ⵉⴷⴻⴰⵍ ⴱⵓⵓⵔ ⵓⵏⴻ ⴼⴻⵏⵜⴻ ⴱⵓⵏⵙⵜⵓⴻⵍⵍⴻ.',
  '1 annonce publiee par jour':'1 ⴰⵏⵏⵓⵏⵙⴻ ⴱⵓⴱⵍⵉⴻⴻ ⴱⴰⵔ ⵊⵓⵓⵔ',
  '1 mois':'1 ⵎⵓⵉⵙ',
  '1 pièce (studio)':'1 ⴱⵉⴻⵙⴻ (ⵙⵜⵓⴷⵉⵓ)',
  '1. Choisissez votre secteur':'1. ⵙⵀⵓⵉⵙⵉⵙⵙⴻⵣ ⴼⵓⵜⵔⴻ ⵙⴻⵙⵜⴻⵓⵔ',
  '1. Editeur du site':'1. ⴻⴷⵉⵜⴻⵓⵔ ⴷⵓ ⵙⵉⵜⴻ',
  '10 ans pour les majeurs (19 ans et plus), 5 ans pour les mineurs':'10 ⴰⵏⵙ ⴱⵓⵓⵔ ⵍⴻⵙ ⵎⴰⵊⴻⵓⵔⵙ (19 ⴰⵏⵙ ⴻⵜ ⴱⵍⵓⵙ), 5 ⴰⵏⵙ ⴱⵓⵓⵔ ⵍⴻⵙ ⵎⵉⵏⴻⵓⵔⵙ',
  '10. Limitation de responsabilite':'10. ⵍⵉⵎⵉⵜⴰⵜⵉⵓⵏ ⴷⴻ ⵔⴻⵙⴱⵓⵏⵙⴰⴱⵉⵍⵉⵜⴻ',
  '100€ à 300€':'100€ ⴰ 300€',
  '11, Rue du Bicheri, El Mouradia, Alger':'11, ⵔⵓⴻ ⴷⵓ ⴱⵉⵙⵀⴻⵔⵉ, ⴻⵍ ⵎⵓⵓⵔⴰⴷⵉⴰ, ⴰⵍⴳⴻⵔ',
  '11. Liens externes':'11. ⵍⵉⴻⵏⵙ ⴻⵅⵜⴻⵔⵏⴻⵙ',
  '12 MOIS — 180€ ⭐':'12 ⵎⵓⵉⵙ — 180€ ⭐',
  '12. Modification des CGU':'12. ⵎⵓⴷⵉⴼⵉⵙⴰⵜⵉⵓⵏ ⴷⴻⵙ ⵙⴳⵓ',
  '13. Droit applicable':'13. ⴷⵔⵓⵉⵜ ⴰⴱⴱⵍⵉⵙⴰⴱⵍⴻ',
  '14. Contact':'14. ⵙⵓⵏⵜⴰⵙⵜ',
  '15 à 60 sec':'15 ⴰ 60 ⵙⴻⵙ',
  '18, Rue Mustapha Khalef, Ben Aknoun, Alger':'18, ⵔⵓⴻ ⵎⵓⵙⵜⴰⴱⵀⴰ ⴽⵀⴰⵍⴻⴼ, ⴱⴻⵏ ⴰⴽⵏⵓⵓⵏ, ⴰⵍⴳⴻⵔ',
  '2 pièces (F2)':'2 ⴱⵉⴻⵙⴻⵙ (ⴼ2)',
  '2. Objet du site':'2. ⵓⴱⵊⴻⵜ ⴷⵓ ⵙⵉⵜⴻ',
  '21, Chemin Sfindja, El Biar, Alger':'21, ⵙⵀⴻⵎⵉⵏ ⵙⴼⵉⵏⴷⵊⴰ, ⴻⵍ ⴱⵉⴰⵔ, ⴰⵍⴳⴻⵔ',
  '24h':'24ⵀ',
  '25, Chemin Abdelkader Gadouche, Hydra, Alger':'25, ⵙⵀⴻⵎⵉⵏ ⴰⴱⴷⴻⵍⴽⴰⴷⴻⵔ ⴳⴰⴷⵓⵓⵙⵀⴻ, ⵀⵢⴷⵔⴰ, ⴰⵍⴳⴻⵔ',
  '3 MOIS — 55€':'3 ⵎⵓⵉⵙ — 55€',
  '3 pièces (F3)':'3 ⴱⵉⴻⵙⴻⵙ (ⴼ3)',
  '3. Acces au site':'3. ⴰⵙⵙⴻⵙ ⴰⵓ ⵙⵉⵜⴻ',
  '30 jours':'30 ⵊⵓⵓⵔⵙ',
  '300€ à 500€':'300€ ⴰ 500€',
  '4 annonces gratuites':'4 ⴰⵏⵏⵓⵏⵙⴻⵙ ⴳⵔⴰⵜⵓⵉⵜⴻⵙ',
  '4 annonces gratuites a l inscription':'4 ⴰⵏⵏⵓⵏⵙⴻⵙ ⴳⵔⴰⵜⵓⵉⵜⴻⵙ ⴰ ⵍ ⵉⵏⵙⵙⵔⵉⴱⵜⵉⵓⵏ',
  '4 annonces gratuites à l inscription':'4 ⴰⵏⵏⵓⵏⵙⴻⵙ ⴳⵔⴰⵜⵓⵉⵜⴻⵙ ⴰ ⵍ ⵉⵏⵙⵙⵔⵉⴱⵜⵉⵓⵏ',
  '4 pièces (F4)':'4 ⴱⵉⴻⵙⴻⵙ (ⴼ4)',
  '4. Comptes utilisateurs':'4. ⵙⵓⵎⴱⵜⴻⵙ ⵓⵜⵉⵍⵉⵙⴰⵜⴻⵓⵔⵙ',
  '48 a 72 heures en moyenne':'48 ⴰ 72 ⵀⴻⵓⵔⴻⵙ ⴻⵏ ⵎⵓⵢⴻⵏⵏⴻ',
  '5 ans, renouvellement a demander avant expiration':'5 ⴰⵏⵙ, ⵔⴻⵏⵓⵓⴼⴻⵍⵍⴻⵎⴻⵏⵜ ⴰ ⴷⴻⵎⴰⵏⴷⴻⵔ ⴰⴼⴰⵏⵜ ⴻⵅⴱⵉⵔⴰⵜⵉⵓⵏ',
  '5 pièces et plus':'5 ⴱⵉⴻⵙⴻⵙ ⴻⵜ ⴱⵍⵓⵙ',
  '5. Annonces et contenus deposes par les utilisateurs':'5. ⴰⵏⵏⵓⵏⵙⴻⵙ ⴻⵜ ⵙⵓⵏⵜⴻⵏⵓⵙ ⴷⴻⴱⵓⵙⴻⵙ ⴱⴰⵔ ⵍⴻⵙ ⵓⵜⵉⵍⵉⵙⴰⵜⴻⵓⵔⵙ',
  '6 MOIS — 105€':'6 ⵎⵓⵉⵙ — 105€',
  '6 mois':'6 ⵎⵓⵉⵙ',
  '6. Espace Professionnel (Devenir Pro)':'6. ⴻⵙⴱⴰⵙⴻ ⴱⵔⵓⴼⴻⵙⵙⵉⵓⵏⵏⴻⵍ (ⴷⴻⴼⴻⵏⵉⵔ ⴱⵔⵓ)',
  '69 wilayas':'69 ⵡⵉⵍⴰⵢⴰⵙ',
  '7 annonces sur 7 jours':'7 ⴰⵏⵏⵓⵏⵙⴻⵙ ⵙⵓⵔ 7 ⵊⵓⵓⵔⵙ',
  '7 jours':'7 ⵊⵓⵓⵔⵙ',
  '7. Propriete intellectuelle':'7. ⴱⵔⵓⴱⵔⵉⴻⵜⴻ ⵉⵏⵜⴻⵍⵍⴻⵙⵜⵓⴻⵍⵍⴻ',
  '7M+':'7ⵎ+',
  '8, Rue des Cretes, El Biar, Alger':'8, ⵔⵓⴻ ⴷⴻⵙ ⵙⵔⴻⵜⴻⵙ, ⴻⵍ ⴱⵉⴰⵔ, ⴰⵍⴳⴻⵔ',
  '8. Donnees personnelles (RGPD)':'8. ⴷⵓⵏⵏⴻⴻⵙ ⴱⴻⵔⵙⵓⵏⵏⴻⵍⵍⴻⵙ (ⵔⴳⴱⴷ)',
  '9. Cookies':'9. ⵙⵓⵓⴽⵉⴻⵙ',
  ': bien vendu avec des dettes cachees — demandez un certificat de non-hypotheque':': ⴱⵉⴻⵏ ⴼⴻⵏⴷⵓ ⴰⴼⴻⵙ ⴷⴻⵙ ⴷⴻⵜⵜⴻⵙ ⵙⴰⵙⵀⴻⴻⵙ — ⴷⴻⵎⴰⵏⴷⴻⵣ ⵓⵏ ⵙⴻⵔⵜⵉⴼⵉⵙⴰⵜ ⴷⴻ ⵏⵓⵏ-ⵀⵢⴱⵓⵜⵀⴻⵇⵓⴻ',
  ': faux sites de banques algeriennes — verifiez toujours l URL officielle':': ⴼⴰⵓⵅ ⵙⵉⵜⴻⵙ ⴷⴻ ⴱⴰⵏⵇⵓⴻⵙ ⴰⵍⴳⴻⵔⵉⴻⵏⵏⴻⵙ — ⴼⴻⵔⵉⴼⵉⴻⵣ ⵜⵓⵓⵊⵓⵓⵔⵙ ⵍ ⵓⵔⵍ ⵓⴼⴼⵉⵙⵉⴻⵍⵍⴻ',
  ': guide sans carte professionnelle — demandez toujours une identification':': ⴳⵓⵉⴷⴻ ⵙⴰⵏⵙ ⵙⴰⵔⵜⴻ ⴱⵔⵓⴼⴻⵙⵙⵉⵓⵏⵏⴻⵍⵍⴻ — ⴷⴻⵎⴰⵏⴷⴻⵣ ⵜⵓⵓⵊⵓⵓⵔⵙ ⵓⵏⴻ ⵉⴷⴻⵏⵜⵉⴼⵉⵙⴰⵜⵉⵓⵏ',
  ': illegal et risque — billets faux, agression, poursuites penales':': ⵉⵍⵍⴻⴳⴰⵍ ⴻⵜ ⵔⵉⵙⵇⵓⴻ — ⴱⵉⵍⵍⴻⵜⵙ ⴼⴰⵓⵅ, ⴰⴳⵔⴻⵙⵙⵉⵓⵏ, ⴱⵓⵓⵔⵙⵓⵉⵜⴻⵙ ⴱⴻⵏⴰⵍⴻⵙ',
  ': paiement par virement DZD —':': ⴱⴰⵉⴻⵎⴻⵏⵜ ⴱⴰⵔ ⴼⵉⵔⴻⵎⴻⵏⵜ ⴷⵣⴷ —',
  ': promesses de rendements eleves — pas de placement garanti a 20-30% en Algerie':': ⴱⵔⵓⵎⴻⵙⵙⴻⵙ ⴷⴻ ⵔⴻⵏⴷⴻⵎⴻⵏⵜⵙ ⴻⵍⴻⴼⴻⵙ — ⴱⴰⵙ ⴷⴻ ⴱⵍⴰⵙⴻⵎⴻⵏⵜ ⴳⴰⵔⴰⵏⵜⵉ ⴰ 20-30% ⴻⵏ ⴰⵍⴳⴻⵔⵉⴻ',
  ': relation en ligne aboutissant a une demande d argent — soyez vigilant':': ⵔⴻⵍⴰⵜⵉⵓⵏ ⴻⵏ ⵍⵉⴳⵏⴻ ⴰⴱⵓⵓⵜⵉⵙⵙⴰⵏⵜ ⴰ ⵓⵏⴻ ⴷⴻⵎⴰⵏⴷⴻ ⴷ ⴰⵔⴳⴻⵏⵜ — ⵙⵓⵢⴻⵣ ⴼⵉⴳⵉⵍⴰⵏⵜ',
  ': reservez uniquement via des agences agreees ONAT ou compagnies officielles':': ⵔⴻⵙⴻⵔⴼⴻⵣ ⵓⵏⵉⵇⵓⴻⵎⴻⵏⵜ ⴼⵉⴰ ⴷⴻⵙ ⴰⴳⴻⵏⵙⴻⵙ ⴰⴳⵔⴻⴻⴻⵙ ⵓⵏⴰⵜ ⵓⵓ ⵙⵓⵎⴱⴰⴳⵏⵉⴻⵙ ⵓⴼⴼⵉⵙⵉⴻⵍⵍⴻⵙ',
  ': verifiez l inscription au barreau avant tout versement':': ⴼⴻⵔⵉⴼⵉⴻⵣ ⵍ ⵉⵏⵙⵙⵔⵉⴱⵜⵉⵓⵏ ⴰⵓ ⴱⴰⵔⵔⴻⴰⵓ ⴰⴼⴰⵏⵜ ⵜⵓⵓⵜ ⴼⴻⵔⵙⴻⵎⴻⵏⵜ',
  ': vous avez gagne un prix en Algerie — c est une arnaque, ne payez pas de frais':': ⴼⵓⵓⵙ ⴰⴼⴻⵣ ⴳⴰⴳⵏⴻ ⵓⵏ ⴱⵔⵉⵅ ⴻⵏ ⴰⵍⴳⴻⵔⵉⴻ — ⵙ ⴻⵙⵜ ⵓⵏⴻ ⴰⵔⵏⴰⵇⵓⴻ, ⵏⴻ ⴱⴰⵢⴻⵣ ⴱⴰⵙ ⴷⴻ ⴼⵔⴰⵉⵙ',
  'AADL':'ⴰⴰⴷⵍ',
  'AFerry (comparateur)':'ⴰⴼⴻⵔⵔⵢ (ⵙⵓⵎⴱⴰⵔⴰⵜⴻⵓⵔ)',
  'APK direct':'ⴰⴱⴽ ⴷⵉⵔⴻⵙⵜ',
  'Abonnement':'ⴰⴱⵓⵏⵏⴻⵎⴻⵏⵜ',
  'Abonnement / الاشتراك':'ⴰⴱⵓⵏⵏⴻⵎⴻⵏⵜ / الاشتراك',
  'Abonnement choisi / الاشتراك المختار':'ⴰⴱⵓⵏⵏⴻⵎⴻⵏⵜ ⵙⵀⵓⵉⵙⵉ / الاشتراك المختار',
  'Abonnement souhaite *':'ⴰⴱⵓⵏⵏⴻⵎⴻⵏⵜ ⵙⵓⵓⵀⴰⵉⵜⴻ *',
  'Acces depuis Batna — Guide recommande':'ⴰⵙⵙⴻⵙ ⴷⴻⴱⵓⵉⵙ ⴱⴰⵜⵏⴰ — ⴳⵓⵉⴷⴻ ⵔⴻⵙⵓⵎⵎⴰⵏⴷⴻ',
  'Acces rapide':'ⴰⵙⵙⴻⵙ ⵔⴰⴱⵉⴷⴻ',
  'Accessible depuis Alger en 3h':'ⴰⵙⵙⴻⵙⵙⵉⴱⵍⴻ ⴷⴻⴱⵓⵉⵙ ⴰⵍⴳⴻⵔ ⴻⵏ 3ⵀ',
  'Accueil':'ⴰⵙⵙⵓⴻⵉⵍ',
  'Accès professionnel requis':'ⴰⵙⵙⴻⵙ ⴱⵔⵓⴼⴻⵙⵙⵉⵓⵏⵏⴻⵍ ⵔⴻⵇⵓⵉⵙ',
  'Accès réservé':'ⴰⵙⵙⴻⵙ ⵔⴻⵙⴻⵔⴼⴻ',
  'Accès réservé administrateur':'ⴰⵙⵙⴻⵙ ⵔⴻⵙⴻⵔⴼⴻ ⴰⴷⵎⵉⵏⵉⵙⵜⵔⴰⵜⴻⵓⵔ',
  'Accès à l annuaire':'ⴰⵙⵙⴻⵙ ⴰ ⵍ ⴰⵏⵏⵓⴰⵉⵔⴻ',
  'Achat, location, agences':'ⴰⵙⵀⴰⵜ, ⵍⵓⵙⴰⵜⵉⵓⵏ, ⴰⴳⴻⵏⵙⴻⵙ',
  'Acte de mariage / divorce :':'ⴰⵙⵜⴻ ⴷⴻ ⵎⴰⵔⵉⴰⴳⴻ / ⴷⵉⴼⵓⵔⵙⴻ :',
  'Acte de naissance (12S) :':'ⴰⵙⵜⴻ ⴷⴻ ⵏⴰⵉⵙⵙⴰⵏⵙⴻ (12ⵙ) :',
  'Actualités en direct':'ⴰⵙⵜⵓⴰⵍⵉⵜⴻⵙ ⴻⵏ ⴷⵉⵔⴻⵙⵜ',
  'Admin Pro — DZ Diaspora':'ⴰⴷⵎⵉⵏ ⴱⵔⵓ — ⴷⵣ ⴷⵉⴰⵙⴱⵓⵔⴰ',
  'Admin Pub — DZ Diaspora':'ⴰⴷⵎⵉⵏ ⴱⵓⴱ — ⴷⵣ ⴷⵉⴰⵙⴱⵓⵔⴰ',
  'Admin RDV — DZ Diaspora':'ⴰⴷⵎⵉⵏ ⵔⴷⴼ — ⴷⵣ ⴷⵉⴰⵙⴱⵓⵔⴰ',
  'Administratif':'ⴰⴷⵎⵉⵏⵉⵙⵜⵔⴰⵜⵉⴼ',
  'Administratif Algerie — Passeport, carte consulaire, demarches':'ⴰⴷⵎⵉⵏⵉⵙⵜⵔⴰⵜⵉⴼ ⴰⵍⴳⴻⵔⵉⴻ — ⴱⴰⵙⵙⴻⴱⵓⵔⵜ, ⵙⴰⵔⵜⴻ ⵙⵓⵏⵙⵓⵍⴰⵉⵔⴻ, ⴷⴻⵎⴰⵔⵙⵀⴻⵙ',
  'Adrar':'ⴰⴷⵔⴰⵔ',
  'Adresse / العنوان':'ⴰⴷⵔⴻⵙⵙⴻ / العنوان',
  'Adresse cabinet *':'ⴰⴷⵔⴻⵙⵙⴻ ⵙⴰⴱⵉⵏⴻⵜ *',
  'Adresse cabinet / عنوان المكتب':'ⴰⴷⵔⴻⵙⵙⴻ ⵙⴰⴱⵉⵏⴻⵜ / عنوان المكتب',
  'Aflou':'ⴰⴼⵍⵓⵓ',
  'Agences de voyage':'ⴰⴳⴻⵏⵙⴻⵙ ⴷⴻ ⴼⵓⵢⴰⴳⴻ',
  'Agents immobiliers':'ⴰⴳⴻⵏⵜⵙ ⵉⵎⵎⵓⴱⵉⵍⵉⴻⵔⵙ',
  'Ain Oussara':'ⴰⵉⵏ ⵓⵓⵙⵙⴰⵔⴰ',
  'Ain Taya — Est d Alger':'ⴰⵉⵏ ⵜⴰⵢⴰ — ⴻⵙⵜ ⴷ ⴰⵍⴳⴻⵔ',
  'Air Algerie':'ⴰⵉⵔ ⴰⵍⴳⴻⵔⵉⴻ',
  'Air France':'ⴰⵉⵔ ⴼⵔⴰⵏⵙⴻ',
  'Al Salam Bank / Al Baraka':'ⴰⵍ ⵙⴰⵍⴰⵎ ⴱⴰⵏⴽ / ⴰⵍ ⴱⴰⵔⴰⴽⴰ',
  'Alertes en temps réel':'ⴰⵍⴻⵔⵜⴻⵙ ⴻⵏ ⵜⴻⵎⴱⵙ ⵔⴻⴻⵍ',
  'Alertes transport en temps réel':'ⴰⵍⴻⵔⵜⴻⵙ ⵜⵔⴰⵏⵙⴱⵓⵔⵜ ⴻⵏ ⵜⴻⵎⴱⵙ ⵔⴻⴻⵍ',
  'Alertez les secours':'ⴰⵍⴻⵔⵜⴻⵣ ⵍⴻⵙ ⵙⴻⵙⵓⵓⵔⵙ',
  'Alger':'ⴰⵍⴳⴻⵔ',
  'Algerie Ferries':'ⴰⵍⴳⴻⵔⵉⴻ ⴼⴻⵔⵔⵉⴻⵙ',
  'Algériens à l\'étranger':'ⴰⵍⴳⴻⵔⵉⴻⵏⵙ ⴰ ⵍ\'ⴻⵜⵔⴰⵏⴳⴻⵔ',
  'Alternative au depart de Sete vers les ports algeriens.':'ⴰⵍⵜⴻⵔⵏⴰⵜⵉⴼⴻ ⴰⵓ ⴷⴻⴱⴰⵔⵜ ⴷⴻ ⵙⴻⵜⴻ ⴼⴻⵔⵙ ⵍⴻⵙ ⴱⵓⵔⵜⵙ ⴰⵍⴳⴻⵔⵉⴻⵏⵙ.',
  'Alterne avec d\'autres':'ⴰⵍⵜⴻⵔⵏⴻ ⴰⴼⴻⵙ ⴷ\'ⴰⵓⵜⵔⴻⵙ',
  'Ambassades en Algerie (pour ressortissants etrangers)':'ⴰⵎⴱⴰⵙⵙⴰⴷⴻⵙ ⴻⵏ ⴰⵍⴳⴻⵔⵉⴻ (ⴱⵓⵓⵔ ⵔⴻⵙⵙⵓⵔⵜⵉⵙⵙⴰⵏⵜⵙ ⴻⵜⵔⴰⵏⴳⴻⵔⵙ)',
  'Ancienne cite romaine fondee en 100 ap. J.-C. Wilaya de Batna — classee UNESCO.':'ⴰⵏⵙⵉⴻⵏⵏⴻ ⵙⵉⵜⴻ ⵔⵓⵎⴰⵉⵏⴻ ⴼⵓⵏⴷⴻⴻ ⴻⵏ 100 ⴰⴱ. ⵊ.-ⵙ. ⵡⵉⵍⴰⵢⴰ ⴷⴻ ⴱⴰⵜⵏⴰ — ⵙⵍⴰⵙⵙⴻⴻ ⵓⵏⴻⵙⵙⵓ.',
  'Anglais':'ⴰⵏⴳⵍⴰⵉⵙ',
  'Annaba':'ⴰⵏⵏⴰⴱⴰ',
  'Annonces':'ⴰⵏⵏⵓⵏⵙⴻⵙ',
  'Annonces illimitees':'ⴰⵏⵏⵓⵏⵙⴻⵙ ⵉⵍⵍⵉⵎⵉⵜⴻⴻⵙ',
  'Annonces immobilières illimitées':'ⴰⵏⵏⵓⵏⵙⴻⵙ ⵉⵎⵎⵓⴱⵉⵍⵉⴻⵔⴻⵙ ⵉⵍⵍⵉⵎⵉⵜⴻⴻⵙ',
  'Annonces mises en avant':'ⴰⵏⵏⵓⵏⵙⴻⵙ ⵎⵉⵙⴻⵙ ⴻⵏ ⴰⴼⴰⵏⵜ',
  'Annuaire':'ⴰⵏⵏⵓⴰⵉⵔⴻ',
  'Annuaire Professionnels — DZ Diaspora':'ⴰⵏⵏⵓⴰⵉⵔⴻ ⴱⵔⵓⴼⴻⵙⵙⵉⵓⵏⵏⴻⵍⵙ — ⴷⵣ ⴷⵉⴰⵙⴱⵓⵔⴰ',
  'Annuaire pro':'ⴰⵏⵏⵓⴰⵉⵔⴻ ⴱⵔⵓ',
  'Annuel':'ⴰⵏⵏⵓⴻⵍ',
  'Annuel — 240€/an':'ⴰⵏⵏⵓⴻⵍ — 240€/ⴰⵏ',
  'Annuel — ~36 475 DZD':'ⴰⵏⵏⵓⴻⵍ — ~36 475 ⴷⵣⴷ',
  'Annuel — ~36 475 DZD (virement)':'ⴰⵏⵏⵓⴻⵍ — ~36 475 ⴷⵣⴷ (ⴼⵉⵔⴻⵎⴻⵏⵜ)',
  'Annulation a tout moment':'ⴰⵏⵏⵓⵍⴰⵜⵉⵓⵏ ⴰ ⵜⵓⵓⵜ ⵎⵓⵎⴻⵏⵜ',
  'Anti-Arnaques':'ⴰⵏⵜⵉ-ⴰⵔⵏⴰⵇⵓⴻⵙ',
  'Anti-Arnaques Algerie — Protegez-vous des escroqueries':'ⴰⵏⵜⵉ-ⴰⵔⵏⴰⵇⵓⴻⵙ ⴰⵍⴳⴻⵔⵉⴻ — ⴱⵔⵓⵜⴻⴳⴻⵣ-ⴼⵓⵓⵙ ⴷⴻⵙ ⴻⵙⵙⵔⵓⵇⵓⴻⵔⵉⴻⵙ',
  'Anticipez vos reservations en periode de vacances scolaires et de Ramadan':'ⴰⵏⵜⵉⵙⵉⴱⴻⵣ ⴼⵓⵙ ⵔⴻⵙⴻⵔⴼⴰⵜⵉⵓⵏⵙ ⴻⵏ ⴱⴻⵔⵉⵓⴷⴻ ⴷⴻ ⴼⴰⵙⴰⵏⵙⴻⵙ ⵙⵙⵓⵍⴰⵉⵔⴻⵙ ⴻⵜ ⴷⴻ ⵔⴰⵎⴰⴷⴰⵏ',
  'App mobile uniquement':'ⴰⴱⴱ ⵎⵓⴱⵉⵍⴻ ⵓⵏⵉⵇⵓⴻⵎⴻⵏⵜ',
  'Appartement':'ⴰⴱⴱⴰⵔⵜⴻⵎⴻⵏⵜ',
  'Appel':'ⴰⴱⴱⴻⵍ',
  'Appelez au secours':'ⴰⴱⴱⴻⵍⴻⵣ ⴰⵓ ⵙⴻⵙⵓⵓⵔⵙ',
  'Application Android':'ⴰⴱⴱⵍⵉⵙⴰⵜⵉⵓⵏ ⴰⵏⴷⵔⵓⵉⴷ',
  'Apport personnel generalement exige (souvent 10 a 30% du montant du bien)':'ⴰⴱⴱⵓⵔⵜ ⴱⴻⵔⵙⵓⵏⵏⴻⵍ ⴳⴻⵏⴻⵔⴰⵍⴻⵎⴻⵏⵜ ⴻⵅⵉⴳⴻ (ⵙⵓⵓⴼⴻⵏⵜ 10 ⴰ 30% ⴷⵓ ⵎⵓⵏⵜⴰⵏⵜ ⴷⵓ ⴱⵉⴻⵏ)',
  'Arabe':'ⴰⵔⴰⴱⴻ',
  'Arnaques a la location de vacances':'ⴰⵔⵏⴰⵇⵓⴻⵙ ⴰ ⵍⴰ ⵍⵓⵙⴰⵜⵉⵓⵏ ⴷⴻ ⴼⴰⵙⴰⵏⵙⴻⵙ',
  'Arrhes perdues':'ⴰⵔⵔⵀⴻⵙ ⴱⴻⵔⴷⵓⴻⵙ',
  'Art. 1 — Moralité et authenticité :':'ⴰⵔⵜ. 1 — ⵎⵓⵔⴰⵍⵉⵜⴻ ⴻⵜ ⴰⵓⵜⵀⴻⵏⵜⵉⵙⵉⵜⴻ :',
  'Art. 2 — Obligations :':'ⴰⵔⵜ. 2 — ⵓⴱⵍⵉⴳⴰⵜⵉⵓⵏⵙ :',
  'Art. 3 — Résiliation :':'ⴰⵔⵜ. 3 — ⵔⴻⵙⵉⵍⵉⴰⵜⵉⵓⵏ :',
  'Art. 4 — Poursuites judiciaires :':'ⴰⵔⵜ. 4 — ⴱⵓⵓⵔⵙⵓⵉⵜⴻⵙ ⵊⵓⴷⵉⵙⵉⴰⵉⵔⴻⵙ :',
  'Article Sponsorisé':'ⴰⵔⵜⵉⵙⵍⴻ ⵙⴱⵓⵏⵙⵓⵔⵉⵙⴻ',
  'Article rédigé professionnellement':'ⴰⵔⵜⵉⵙⵍⴻ ⵔⴻⴷⵉⴳⴻ ⴱⵔⵓⴼⴻⵙⵙⵉⵓⵏⵏⴻⵍⵍⴻⵎⴻⵏⵜ',
  'Aucun badge':'ⴰⵓⵙⵓⵏ ⴱⴰⴷⴳⴻ',
  'Aucune somme ne doit etre versee avant la signature officielle':'ⴰⵓⵙⵓⵏⴻ ⵙⵓⵎⵎⴻ ⵏⴻ ⴷⵓⵉⵜ ⴻⵜⵔⴻ ⴼⴻⵔⵙⴻⴻ ⴰⴼⴰⵏⵜ ⵍⴰ ⵙⵉⴳⵏⴰⵜⵓⵔⴻ ⵓⴼⴼⵉⵙⵉⴻⵍⵍⴻ',
  'Autoriser l installation':'ⴰⵓⵜⵓⵔⵉⵙⴻⵔ ⵍ ⵉⵏⵙⵜⴰⵍⵍⴰⵜⵉⵓⵏ',
  'Autre':'ⴰⵓⵜⵔⴻ',
  'Autre / Je ne sais pas encore':'ⴰⵓⵜⵔⴻ / ⵊⴻ ⵏⴻ ⵙⴰⵉⵙ ⴱⴰⵙ ⴻⵏⵙⵓⵔⴻ',
  'Autre pays':'ⴰⵓⵜⵔⴻ ⴱⴰⵢⵙ',
  'Autre spécialité':'ⴰⵓⵜⵔⴻ ⵙⴱⴻⵙⵉⴰⵍⵉⵜⴻ',
  'Avocats & Notaires':'ⴰⴼⵓⵙⴰⵜⵙ & ⵏⵓⵜⴰⵉⵔⴻⵙ',
  'Avocats, notaires, huissiers':'ⴰⴼⵓⵙⴰⵜⵙ, ⵏⵓⵜⴰⵉⵔⴻⵙ, ⵀⵓⵉⵙⵙⵉⴻⵔⵙ',
  'Aïn Defla':'ⴰⵉⵏ ⴷⴻⴼⵍⴰ',
  'Aïn Témouchent':'ⴰⵉⵏ ⵜⴻⵎⵓⵓⵙⵀⴻⵏⵜ',
  'BDL — Banque de Developpement Local':'ⴱⴷⵍ — ⴱⴰⵏⵇⵓⴻ ⴷⴻ ⴷⴻⴼⴻⵍⵓⴱⴱⴻⵎⴻⵏⵜ ⵍⵓⵙⴰⵍ',
  'BEA — Banque Exterieure d Algerie':'ⴱⴻⴰ — ⴱⴰⵏⵇⵓⴻ ⴻⵅⵜⴻⵔⵉⴻⵓⵔⴻ ⴷ ⴰⵍⴳⴻⵔⵉⴻ',
  'BNA — Banque Nationale d Algerie':'ⴱⵏⴰ — ⴱⴰⵏⵇⵓⴻ ⵏⴰⵜⵉⵓⵏⴰⵍⴻ ⴷ ⴰⵍⴳⴻⵔⵉⴻ',
  'BNH — Banque Nationale de l Habitat':'ⴱⵏⵀ — ⴱⴰⵏⵇⵓⴻ ⵏⴰⵜⵉⵓⵏⴰⵍⴻ ⴷⴻ ⵍ ⵀⴰⴱⵉⵜⴰⵜ',
  'BNP Paribas El Djazair':'ⴱⵏⴱ ⴱⴰⵔⵉⴱⴰⵙ ⴻⵍ ⴷⵊⴰⵣⴰⵉⵔ',
  'Badge Partenaire Officiel ⭐':'ⴱⴰⴷⴳⴻ ⴱⴰⵔⵜⴻⵏⴰⵉⵔⴻ ⵓⴼⴼⵉⵙⵉⴻⵍ ⭐',
  'Badge Pro verifie renforce la confiance des patients et clients.':'ⴱⴰⴷⴳⴻ ⴱⵔⵓ ⴼⴻⵔⵉⴼⵉⴻ ⵔⴻⵏⴼⵓⵔⵙⴻ ⵍⴰ ⵙⵓⵏⴼⵉⴰⵏⵙⴻ ⴷⴻⵙ ⴱⴰⵜⵉⴻⵏⵜⵙ ⴻⵜ ⵙⵍⵉⴻⵏⵜⵙ.',
  'Badge professionnel verifie':'ⴱⴰⴷⴳⴻ ⴱⵔⵓⴼⴻⵙⵙⵉⵓⵏⵏⴻⵍ ⴼⴻⵔⵉⴼⵉⴻ',
  'Badge vendeur verifie':'ⴱⴰⴷⴳⴻ ⴼⴻⵏⴷⴻⵓⵔ ⴼⴻⵔⵉⴼⵉⴻ',
  'Bagages :':'ⴱⴰⴳⴰⴳⴻⵙ :',
  'Balearia':'ⴱⴰⵍⴻⴰⵔⵉⴰ',
  'Bannière Display':'ⴱⴰⵏⵏⵉⴻⵔⴻ ⴷⵉⵙⴱⵍⴰⵢ',
  'Banque privee, services digitaux developpes, cartes internationales.':'ⴱⴰⵏⵇⵓⴻ ⴱⵔⵉⴼⴻⴻ, ⵙⴻⵔⴼⵉⵙⴻⵙ ⴷⵉⴳⵉⵜⴰⵓⵅ ⴷⴻⴼⴻⵍⵓⴱⴱⴻⵙ, ⵙⴰⵔⵜⴻⵙ ⵉⵏⵜⴻⵔⵏⴰⵜⵉⵓⵏⴰⵍⴻⵙ.',
  'Banque publique de proximite, forte presence regionale.':'ⴱⴰⵏⵇⵓⴻ ⴱⵓⴱⵍⵉⵇⵓⴻ ⴷⴻ ⴱⵔⵓⵅⵉⵎⵉⵜⴻ, ⴼⵓⵔⵜⴻ ⴱⵔⴻⵙⴻⵏⵙⴻ ⵔⴻⴳⵉⵓⵏⴰⵍⴻ.',
  'Banque publique historique, large reseau d agences sur tout le territoire.':'ⴱⴰⵏⵇⵓⴻ ⴱⵓⴱⵍⵉⵇⵓⴻ ⵀⵉⵙⵜⵓⵔⵉⵇⵓⴻ, ⵍⴰⵔⴳⴻ ⵔⴻⵙⴻⴰⵓ ⴷ ⴰⴳⴻⵏⵙⴻⵙ ⵙⵓⵔ ⵜⵓⵓⵜ ⵍⴻ ⵜⴻⵔⵔⵉⵜⵓⵉⵔⴻ.',
  'Banque publique, services aux particuliers et entreprises.':'ⴱⴰⵏⵇⵓⴻ ⴱⵓⴱⵍⵉⵇⵓⴻ, ⵙⴻⵔⴼⵉⵙⴻⵙ ⴰⵓⵅ ⴱⴰⵔⵜⵉⵙⵓⵍⵉⴻⵔⵙ ⴻⵜ ⴻⵏⵜⵔⴻⴱⵔⵉⵙⴻⵙ.',
  'Banques internationales presentes en Algerie':'ⴱⴰⵏⵇⵓⴻⵙ ⵉⵏⵜⴻⵔⵏⴰⵜⵉⵓⵏⴰⵍⴻⵙ ⴱⵔⴻⵙⴻⵏⵜⴻⵙ ⴻⵏ ⴰⵍⴳⴻⵔⵉⴻ',
  'Banques islamiques proposant des produits conformes a la finance islamique.':'ⴱⴰⵏⵇⵓⴻⵙ ⵉⵙⵍⴰⵎⵉⵇⵓⴻⵙ ⴱⵔⵓⴱⵓⵙⴰⵏⵜ ⴷⴻⵙ ⴱⵔⵓⴷⵓⵉⵜⵙ ⵙⵓⵏⴼⵓⵔⵎⴻⵙ ⴰ ⵍⴰ ⴼⵉⵏⴰⵏⵙⴻ ⵉⵙⵍⴰⵎⵉⵇⵓⴻ.',
  'Banques nationales':'ⴱⴰⵏⵇⵓⴻⵙ ⵏⴰⵜⵉⵓⵏⴰⵍⴻⵙ',
  'Barika':'ⴱⴰⵔⵉⴽⴰ',
  'Batna':'ⴱⴰⵜⵏⴰ',
  'Bejaia':'ⴱⴻⵊⴰⵉⴰ',
  'Bejaia et la Corniche kabyle':'ⴱⴻⵊⴰⵉⴰ ⴻⵜ ⵍⴰ ⵙⵓⵔⵏⵉⵙⵀⴻ ⴽⴰⴱⵢⵍⴻ',
  'Bejaia — Corniche':'ⴱⴻⵊⴰⵉⴰ — ⵙⵓⵔⵏⵉⵙⵀⴻ',
  'Bien sous hypotheque':'ⴱⵉⴻⵏ ⵙⵓⵓⵙ ⵀⵢⴱⵓⵜⵀⴻⵇⵓⴻ',
  'Bienvenue sur':'ⴱⵉⴻⵏⴼⴻⵏⵓⴻ ⵙⵓⵔ',
  'Bir El Ater':'ⴱⵉⵔ ⴻⵍ ⴰⵜⴻⵔ',
  'Biskra':'ⴱⵉⵙⴽⵔⴰ',
  'Blida':'ⴱⵍⵉⴷⴰ',
  'Bon a savoir':'ⴱⵓⵏ ⴰ ⵙⴰⴼⵓⵉⵔ',
  'Booking.com':'ⴱⵓⵓⴽⵉⵏⴳ.ⵙⵓⵎ',
  'Bordj Badji Mokhtar':'ⴱⵓⵔⴷⵊ ⴱⴰⴷⵊⵉ ⵎⵓⴽⵀⵜⴰⵔ',
  'Bordj Bou Arréridj':'ⴱⵓⵔⴷⵊ ⴱⵓⵓ ⴰⵔⵔⴻⵔⵉⴷⵊ',
  'Bou Saada':'ⴱⵓⵓ ⵙⴰⴰⴷⴰ',
  'Bouira':'ⴱⵓⵓⵉⵔⴰ',
  'Boumerdès':'ⴱⵓⵓⵎⴻⵔⴷⴻⵙ',
  'Budget (DZD ou €)':'ⴱⵓⴷⴳⴻⵜ (ⴷⵣⴷ ⵓⵓ €)',
  'Béchar':'ⴱⴻⵙⵀⴰⵔ',
  'Béjaïa':'ⴱⴻⵊⴰⵉⴰ',
  'Béni Abbès':'ⴱⴻⵏⵉ ⴰⴱⴱⴻⵙ',
  'CASNOS — Non-salaries ↗':'ⵙⴰⵙⵏⵓⵙ — ⵏⵓⵏ-ⵙⴰⵍⴰⵔⵉⴻⵙ ↗',
  'CGU':'ⵙⴳⵓ',
  'CGU et mentions legales':'ⵙⴳⵓ ⴻⵜ ⵎⴻⵏⵜⵉⵓⵏⵙ ⵍⴻⴳⴰⵍⴻⵙ',
  'CGU et mentions legales — DZ Diaspora':'ⵙⴳⵓ ⴻⵜ ⵎⴻⵏⵜⵉⵓⵏⵙ ⵍⴻⴳⴰⵍⴻⵙ — ⴷⵣ ⴷⵉⴰⵙⴱⵓⵔⴰ',
  'CNAS — Salaries ↗':'ⵙⵏⴰⵙ — ⵙⴰⵍⴰⵔⵉⴻⵙ ↗',
  'CONTRAT D\'ABONNEMENT PROFESSIONNEL':'ⵙⵓⵏⵜⵔⴰⵜ ⴷ\'ⴰⴱⵓⵏⵏⴻⵎⴻⵏⵜ ⴱⵔⵓⴼⴻⵙⵙⵉⵓⵏⵏⴻⵍ',
  'CPA — Credit Populaire d Algerie':'ⵙⴱⴰ — ⵙⵔⴻⴷⵉⵜ ⴱⵓⴱⵓⵍⴰⵉⵔⴻ ⴷ ⴰⵍⴳⴻⵔⵉⴻ',
  'Ca fonctionne sur quel Android ?':'ⵙⴰ ⴼⵓⵏⵙⵜⵉⵓⵏⵏⴻ ⵙⵓⵔ ⵇⵓⴻⵍ ⴰⵏⴷⵔⵓⵉⴷ ?',
  'Cardiologue':'ⵙⴰⵔⴷⵉⵓⵍⵓⴳⵓⴻ',
  'Carte Chifa ↗':'ⵙⴰⵔⵜⴻ ⵙⵀⵉⴼⴰ ↗',
  'Carte bancaire EUR':'ⵙⴰⵔⵜⴻ ⴱⴰⵏⵙⴰⵉⵔⴻ ⴻⵓⵔ',
  'Casbah d Alger — UNESCO':'ⵙⴰⵙⴱⴰⵀ ⴷ ⴰⵍⴳⴻⵔ — ⵓⵏⴻⵙⵙⵓ',
  'Centre anti-poison':'ⵙⴻⵏⵜⵔⴻ ⴰⵏⵜⵉ-ⴱⵓⵉⵙⵓⵏ',
  'Centre d Alger — Visite guidee recommandee':'ⵙⴻⵏⵜⵔⴻ ⴷ ⴰⵍⴳⴻⵔ — ⴼⵉⵙⵉⵜⴻ ⴳⵓⵉⴷⴻⴻ ⵔⴻⵙⵓⵎⵎⴰⵏⴷⴻⴻ',
  'Change au square':'ⵙⵀⴰⵏⴳⴻ ⴰⵓ ⵙⵇⵓⴰⵔⴻ',
  'Changement de situation :':'ⵙⵀⴰⵏⴳⴻⵎⴻⵏⵜ ⴷⴻ ⵙⵉⵜⵓⴰⵜⵉⵓⵏ :',
  'Chargement des annonces...':'ⵙⵀⴰⵔⴳⴻⵎⴻⵏⵜ ⴷⴻⵙ ⴰⵏⵏⵓⵏⵙⴻⵙ...',
  'Chargement des devises...':'ⵙⵀⴰⵔⴳⴻⵎⴻⵏⵜ ⴷⴻⵙ ⴷⴻⴼⵉⵙⴻⵙ...',
  'Chargement des vols...':'ⵙⵀⴰⵔⴳⴻⵎⴻⵏⵜ ⴷⴻⵙ ⴼⵓⵍⵙ...',
  'Chargement devises...':'ⵙⵀⴰⵔⴳⴻⵎⴻⵏⵜ ⴷⴻⴼⵉⵙⴻⵙ...',
  'Chargement meteo...':'ⵙⵀⴰⵔⴳⴻⵎⴻⵏⵜ ⵎⴻⵜⴻⵓ...',
  'Chargement wilayas...':'ⵙⵀⴰⵔⴳⴻⵎⴻⵏⵜ ⵡⵉⵍⴰⵢⴰⵙ...',
  'Chargement...':'ⵙⵀⴰⵔⴳⴻⵎⴻⵏⵜ...',
  'Chemin Capitaine Hocine Slimane, Alger':'ⵙⵀⴻⵎⵉⵏ ⵙⴰⴱⵉⵜⴰⵉⵏⴻ ⵀⵓⵙⵉⵏⴻ ⵙⵍⵉⵎⴰⵏⴻ, ⴰⵍⴳⴻⵔ',
  'Chemin Cheikh Bachir El-Ibrahimi, El Biar, Alger':'ⵙⵀⴻⵎⵉⵏ ⵙⵀⴻⵉⴽⵀ ⴱⴰⵙⵀⵉⵔ ⴻⵍ-ⵉⴱⵔⴰⵀⵉⵎⵉ, ⴻⵍ ⴱⵉⴰⵔ, ⴰⵍⴳⴻⵔ',
  'Chlef':'ⵙⵀⵍⴻⴼ',
  'Choisir Starter — 14€':'ⵙⵀⵓⵉⵙⵉⵔ ⵙⵜⴰⵔⵜⴻⵔ — 14€',
  'Choisissez une date *':'ⵙⵀⵓⵉⵙⵉⵙⵙⴻⵣ ⵓⵏⴻ ⴷⴰⵜⴻ *',
  'Choisissez votre formule':'ⵙⵀⵓⵉⵙⵉⵙⵙⴻⵣ ⴼⵓⵜⵔⴻ ⴼⵓⵔⵎⵓⵍⴻ',
  'Chronopost':'ⵙⵀⵔⵓⵏⵓⴱⵓⵙⵜ',
  'Clauses du contrat / بنود العقد':'ⵙⵍⴰⵓⵙⴻⵙ ⴷⵓ ⵙⵓⵏⵜⵔⴰⵜ / بنود العقد',
  'Clients Algerie':'ⵙⵍⵉⴻⵏⵜⵙ ⴰⵍⴳⴻⵔⵉⴻ',
  'Clients en Algerie':'ⵙⵍⵉⴻⵏⵜⵙ ⴻⵏ ⴰⵍⴳⴻⵔⵉⴻ',
  'Cliquez pour uploader votre fichier':'ⵙⵍⵉⵇⵓⴻⵣ ⴱⵓⵓⵔ ⵓⴱⵍⵓⴰⴷⴻⵔ ⴼⵓⵜⵔⴻ ⴼⵉⵙⵀⵉⴻⵔ',
  'Cliquez sur le bouton bleu ci-dessus. Le fichier':'ⵙⵍⵉⵇⵓⴻⵣ ⵙⵓⵔ ⵍⴻ ⴱⵓⵓⵜⵓⵏ ⴱⵍⴻⵓ ⵙⵉ-ⴷⴻⵙⵙⵓⵙ. ⵍⴻ ⴼⵉⵙⵀⵉⴻⵔ',
  'Cliquez sur une étoile':'ⵙⵍⵉⵇⵓⴻⵣ ⵙⵓⵔ ⵓⵏⴻ ⴻⵜⵓⵉⵍⴻ',
  'Code PIN Admin':'ⵙⵓⴷⴻ ⴱⵉⵏ ⴰⴷⵎⵉⵏ',
  'Code incorrect.':'ⵙⵓⴷⴻ ⵉⵏⵙⵓⵔⵔⴻⵙⵜ.',
  'Commander un espace publicitaire — DZ Diaspora':'ⵙⵓⵎⵎⴰⵏⴷⴻⵔ ⵓⵏ ⴻⵙⴱⴰⵙⴻ ⴱⵓⴱⵍⵉⵙⵉⵜⴰⵉⵔⴻ — ⴷⵣ ⴷⵉⴰⵙⴱⵓⵔⴰ',
  'Commencer gratuitement':'ⵙⵓⵎⵎⴻⵏⵙⴻⵔ ⴳⵔⴰⵜⵓⵉⵜⴻⵎⴻⵏⵜ',
  'Commencez gratuitement avec 4 annonces offertes — aucune carte bancaire requise.':'ⵙⵓⵎⵎⴻⵏⵙⴻⵣ ⴳⵔⴰⵜⵓⵉⵜⴻⵎⴻⵏⵜ ⴰⴼⴻⵙ 4 ⴰⵏⵏⵓⵏⵙⴻⵙ ⵓⴼⴼⴻⵔⵜⴻⵙ — ⴰⵓⵙⵓⵏⴻ ⵙⴰⵔⵜⴻ ⴱⴰⵏⵙⴰⵉⵔⴻ ⵔⴻⵇⵓⵉⵙⴻ.',
  'Comment fonctionne le code secret ?':'ⵙⵓⵎⵎⴻⵏⵜ ⴼⵓⵏⵙⵜⵉⵓⵏⵏⴻ ⵍⴻ ⵙⵓⴷⴻ ⵙⴻⵙⵔⴻⵜ ?',
  'Comment fonctionnent les 4 annonces gratuites ?':'ⵙⵓⵎⵎⴻⵏⵜ ⴼⵓⵏⵙⵜⵉⵓⵏⵏⴻⵏⵜ ⵍⴻⵙ 4 ⴰⵏⵏⵓⵏⵙⴻⵙ ⴳⵔⴰⵜⵓⵉⵜⴻⵙ ?',
  'Comment retrouver votre objet ?':'ⵙⵓⵎⵎⴻⵏⵜ ⵔⴻⵜⵔⵓⵓⴼⴻⵔ ⴼⵓⵜⵔⴻ ⵓⴱⵊⴻⵜ ?',
  'Comment souhaitez-vous apparaitre ?':'ⵙⵓⵎⵎⴻⵏⵜ ⵙⵓⵓⵀⴰⵉⵜⴻⵣ-ⴼⵓⵓⵙ ⴰⴱⴱⴰⵔⴰⵉⵜⵔⴻ ?',
  'Comment voulez-vous être alerté quand un client cherche vos services ?':'ⵙⵓⵎⵎⴻⵏⵜ ⴼⵓⵓⵍⴻⵣ-ⴼⵓⵓⵙ ⴻⵜⵔⴻ ⴰⵍⴻⵔⵜⴻ ⵇⵓⴰⵏⴷ ⵓⵏ ⵙⵍⵉⴻⵏⵜ ⵙⵀⴻⵔⵙⵀⴻ ⴼⵓⵙ ⵙⴻⵔⴼⵉⵙⴻⵙ ?',
  'Compagnie nationale algerienne — reservation et enregistrement en ligne.':'ⵙⵓⵎⴱⴰⴳⵏⵉⴻ ⵏⴰⵜⵉⵓⵏⴰⵍⴻ ⴰⵍⴳⴻⵔⵉⴻⵏⵏⴻ — ⵔⴻⵙⴻⵔⴼⴰⵜⵉⵓⵏ ⴻⵜ ⴻⵏⵔⴻⴳⵉⵙⵜⵔⴻⵎⴻⵏⵜ ⴻⵏ ⵍⵉⴳⵏⴻ.',
  'Compare plusieurs transporteurs pour trouver le meilleur tarif vers l Algerie.':'ⵙⵓⵎⴱⴰⵔⴻ ⴱⵍⵓⵙⵉⴻⵓⵔⵙ ⵜⵔⴰⵏⵙⴱⵓⵔⵜⴻⵓⵔⵙ ⴱⵓⵓⵔ ⵜⵔⵓⵓⴼⴻⵔ ⵍⴻ ⵎⴻⵉⵍⵍⴻⵓⵔ ⵜⴰⵔⵉⴼ ⴼⴻⵔⵙ ⵍ ⴰⵍⴳⴻⵔⵉⴻ.',
  'Compare tous les ferries vers l Algerie pour trouver le meilleur tarif.':'ⵙⵓⵎⴱⴰⵔⴻ ⵜⵓⵓⵙ ⵍⴻⵙ ⴼⴻⵔⵔⵉⴻⵙ ⴼⴻⵔⵙ ⵍ ⴰⵍⴳⴻⵔⵉⴻ ⴱⵓⵓⵔ ⵜⵔⵓⵓⴼⴻⵔ ⵍⴻ ⵎⴻⵉⵍⵍⴻⵓⵔ ⵜⴰⵔⵉⴼ.',
  'Conditions cumulatives :':'ⵙⵓⵏⴷⵉⵜⵉⵓⵏⵙ ⵙⵓⵎⵓⵍⴰⵜⵉⴼⴻⵙ :',
  'Connectez-vous avec votre compte professionnel DZ Diaspora.':'ⵙⵓⵏⵏⴻⵙⵜⴻⵣ-ⴼⵓⵓⵙ ⴰⴼⴻⵙ ⴼⵓⵜⵔⴻ ⵙⵓⵎⴱⵜⴻ ⴱⵔⵓⴼⴻⵙⵙⵉⵓⵏⵏⴻⵍ ⴷⵣ ⴷⵉⴰⵙⴱⵓⵔⴰ.',
  'Connectez-vous pour voir vos commandes et l\'état de vos publicités.':'ⵙⵓⵏⵏⴻⵙⵜⴻⵣ-ⴼⵓⵓⵙ ⴱⵓⵓⵔ ⴼⵓⵉⵔ ⴼⵓⵙ ⵙⵓⵎⵎⴰⵏⴷⴻⵙ ⴻⵜ ⵍ\'ⴻⵜⴰⵜ ⴷⴻ ⴼⵓⵙ ⴱⵓⴱⵍⵉⵙⵉⵜⴻⵙ.',
  'Connectez-vous pour voir vos demandes.':'ⵙⵓⵏⵏⴻⵙⵜⴻⵣ-ⴼⵓⵓⵙ ⴱⵓⵓⵔ ⴼⵓⵉⵔ ⴼⵓⵙ ⴷⴻⵎⴰⵏⴷⴻⵙ.',
  'Connexion':'ⵙⵓⵏⵏⴻⵅⵉⵓⵏ',
  'Connexion — DZ Diaspora':'ⵙⵓⵏⵏⴻⵅⵉⵓⵏ — ⴷⵣ ⴷⵉⴰⵙⴱⵓⵔⴰ',
  'Connexions vers l Espagne au depart de plusieurs villes algeriennes.':'ⵙⵓⵏⵏⴻⵅⵉⵓⵏⵙ ⴼⴻⵔⵙ ⵍ ⴻⵙⴱⴰⴳⵏⴻ ⴰⵓ ⴷⴻⴱⴰⵔⵜ ⴷⴻ ⴱⵍⵓⵙⵉⴻⵓⵔⵙ ⴼⵉⵍⵍⴻⵙ ⴰⵍⴳⴻⵔⵉⴻⵏⵏⴻⵙ.',
  'Conseil important :':'ⵙⵓⵏⵙⴻⵉⵍ ⵉⵎⴱⵓⵔⵜⴰⵏⵜ :',
  'Conseils pratiques':'ⵙⵓⵏⵙⴻⵉⵍⵙ ⴱⵔⴰⵜⵉⵇⵓⴻⵙ',
  'Conservez tous les echanges ecrits':'ⵙⵓⵏⵙⴻⵔⴼⴻⵣ ⵜⵓⵓⵙ ⵍⴻⵙ ⴻⵙⵀⴰⵏⴳⴻⵙ ⴻⵙⵔⵉⵜⵙ',
  'Conservez une copie numerique de vos documents de voyage':'ⵙⵓⵏⵙⴻⵔⴼⴻⵣ ⵓⵏⴻ ⵙⵓⴱⵉⴻ ⵏⵓⵎⴻⵔⵉⵇⵓⴻ ⴷⴻ ⴼⵓⵙ ⴷⵓⵙⵓⵎⴻⵏⵜⵙ ⴷⴻ ⴼⵓⵢⴰⴳⴻ',
  'Constantine':'ⵙⵓⵏⵙⵜⴰⵏⵜⵉⵏⴻ',
  'Consultation payante':'ⵙⵓⵏⵙⵓⵍⵜⴰⵜⵉⵓⵏ ⴱⴰⵢⴰⵏⵜⴻ',
  'Consultez le cadastre':'ⵙⵓⵏⵙⵓⵍⵜⴻⵣ ⵍⴻ ⵙⴰⴷⴰⵙⵜⵔⴻ',
  'Contact':'ⵙⵓⵏⵜⴰⵙⵜ',
  'Contact (telephone ou email — reste cache jusqu au clic d un interesse)':'ⵙⵓⵏⵜⴰⵙⵜ (ⵜⴻⵍⴻⴱⵀⵓⵏⴻ ⵓⵓ ⴻⵎⴰⵉⵍ — ⵔⴻⵙⵜⴻ ⵙⴰⵙⵀⴻ ⵊⵓⵙⵇⵓ ⴰⵓ ⵙⵍⵉⵙ ⴷ ⵓⵏ ⵉⵏⵜⴻⵔⴻⵙⵙⴻ)',
  'Contact :':'ⵙⵓⵏⵜⴰⵙⵜ :',
  'Contact direct téléphone/email':'ⵙⵓⵏⵜⴰⵙⵜ ⴷⵉⵔⴻⵙⵜ ⵜⴻⵍⴻⴱⵀⵓⵏⴻ/ⴻⵎⴰⵉⵍ',
  'Contact — DZ Diaspora':'ⵙⵓⵏⵜⴰⵙⵜ — ⴷⵣ ⴷⵉⴰⵙⴱⵓⵔⴰ',
  'Contacter le support':'ⵙⵓⵏⵜⴰⵙⵜⴻⵔ ⵍⴻ ⵙⵓⴱⴱⵓⵔⵜ',
  'Contactez :':'ⵙⵓⵏⵜⴰⵙⵜⴻⵣ :',
  'Contactez directement notre commercial :':'ⵙⵓⵏⵜⴰⵙⵜⴻⵣ ⴷⵉⵔⴻⵙⵜⴻⵎⴻⵏⵜ ⵏⵓⵜⵔⴻ ⵙⵓⵎⵎⴻⵔⵙⵉⴰⵍ :',
  'Contactez immediatement la police (17) ou la gendarmerie (1055)':'ⵙⵓⵏⵜⴰⵙⵜⴻⵣ ⵉⵎⵎⴻⴷⵉⴰⵜⴻⵎⴻⵏⵜ ⵍⴰ ⴱⵓⵍⵉⵙⴻ (17) ⵓⵓ ⵍⴰ ⴳⴻⵏⴷⴰⵔⵎⴻⵔⵉⴻ (1055)',
  'Contactez notre commercial :':'ⵙⵓⵏⵜⴰⵙⵜⴻⵣ ⵏⵓⵜⵔⴻ ⵙⵓⵎⵎⴻⵔⵙⵉⴰⵍ :',
  'Contactez-nous':'ⵙⵓⵏⵜⴰⵙⵜⴻⵣ-ⵏⵓⵓⵙ',
  'Contenu publicitaire':'ⵙⵓⵏⵜⴻⵏⵓ ⴱⵓⴱⵍⵉⵙⵉⵜⴰⵉⵔⴻ',
  'Continu':'ⵙⵓⵏⵜⵉⵏⵓ',
  'Contrat Abonnement Pro — DZ Diaspora':'ⵙⵓⵏⵜⵔⴰⵜ ⴰⴱⵓⵏⵏⴻⵎⴻⵏⵜ ⴱⵔⵓ — ⴷⵣ ⴷⵉⴰⵙⴱⵓⵔⴰ',
  'Coordonnees et horaires affiches':'ⵙⵓⵓⵔⴷⵓⵏⵏⴻⴻⵙ ⴻⵜ ⵀⵓⵔⴰⵉⵔⴻⵙ ⴰⴼⴼⵉⵙⵀⴻⵙ',
  'Correspondances internationales via Istanbul.':'ⵙⵓⵔⵔⴻⵙⴱⵓⵏⴷⴰⵏⵙⴻⵙ ⵉⵏⵜⴻⵔⵏⴰⵜⵉⵓⵏⴰⵍⴻⵙ ⴼⵉⴰ ⵉⵙⵜⴰⵏⴱⵓⵍ.',
  'Corsica Linea':'ⵙⵓⵔⵙⵉⵙⴰ ⵍⵉⵏⴻⴰ',
  'Cotisation : 34,5% du salaire brut (9% salarie, 25,5% employeur)':'ⵙⵓⵜⵉⵙⴰⵜⵉⵓⵏ : 34,5% ⴷⵓ ⵙⴰⵍⴰⵉⵔⴻ ⴱⵔⵓⵜ (9% ⵙⴰⵍⴰⵔⵉⴻ, 25,5% ⴻⵎⴱⵍⵓⵢⴻⵓⵔ)',
  'Cotisation annuelle calculee sur le revenu declare':'ⵙⵓⵜⵉⵙⴰⵜⵉⵓⵏ ⴰⵏⵏⵓⴻⵍⵍⴻ ⵙⴰⵍⵙⵓⵍⴻⴻ ⵙⵓⵔ ⵍⴻ ⵔⴻⴼⴻⵏⵓ ⴷⴻⵙⵍⴰⵔⴻ',
  'Cour d appel':'ⵙⵓⵓⵔ ⴷ ⴰⴱⴱⴻⵍ',
  'Cour supreme':'ⵙⵓⵓⵔ ⵙⵓⴱⵔⴻⵎⴻ',
  'Coursa':'ⵙⵓⵓⵔⵙⴰ',
  'Court terme':'ⵙⵓⵓⵔⵜ ⵜⴻⵔⵎⴻ',
  'Cout :':'ⵙⵓⵓⵜ :',
  'Couvrez la victime':'ⵙⵓⵓⴼⵔⴻⵣ ⵍⴰ ⴼⵉⵙⵜⵉⵎⴻ',
  'Covoiturage / Bagages &amp; Objets Trouves':'ⵙⵓⴼⵓⵉⵜⵓⵔⴰⴳⴻ / ⴱⴰⴳⴰⴳⴻⵙ &ⴰⵎⴱ; ⵓⴱⵊⴻⵜⵙ ⵜⵔⵓⵓⴼⴻⵙ',
  'Covoiturage illimité':'ⵙⵓⴼⵓⵉⵜⵓⵔⴰⴳⴻ ⵉⵍⵍⵉⵎⵉⵜⴻ',
  'Créer un compte':'ⵙⵔⴻⴻⵔ ⵓⵏ ⵙⵓⵎⴱⵜⴻ',
  'Créneau horaire souhaité *':'ⵙⵔⴻⵏⴻⴰⵓ ⵀⵓⵔⴰⵉⵔⴻ ⵙⵓⵓⵀⴰⵉⵜⴻ *',
  'DHL Express':'ⴷⵀⵍ ⴻⵅⴱⵔⴻⵙⵙ',
  'DOUBLE EXEMPLAIRE / نسختان':'ⴷⵓⵓⴱⵍⴻ ⴻⵅⴻⵎⴱⵍⴰⵉⵔⴻ / نسختان',
  'DZ DIASPORA 🇩🇿':'ⴷⵣ ⴷⵉⴰⵙⴱⵓⵔⴰ 🇩🇿',
  'DZ Diaspora':'ⴷⵣ ⴷⵉⴰⵙⴱⵓⵔⴰ',
  'DZ Diaspora — NET-HABITA · SIRET 488 470 584 00043':'ⴷⵣ ⴷⵉⴰⵙⴱⵓⵔⴰ — ⵏⴻⵜ-ⵀⴰⴱⵉⵜⴰ · ⵙⵉⵔⴻⵜ 488 470 584 00043',
  'DZ Diaspora — Plateforme de référence de la diaspora algérienne':'ⴷⵣ ⴷⵉⴰⵙⴱⵓⵔⴰ — ⴱⵍⴰⵜⴻⴼⵓⵔⵎⴻ ⴷⴻ ⵔⴻⴼⴻⵔⴻⵏⵙⴻ ⴷⴻ ⵍⴰ ⴷⵉⴰⵙⴱⵓⵔⴰ ⴰⵍⴳⴻⵔⵉⴻⵏⵏⴻ',
  'DZ Diaspora — Tous droits reserves':'ⴷⵣ ⴷⵉⴰⵙⴱⵓⵔⴰ — ⵜⵓⵓⵙ ⴷⵔⵓⵉⵜⵙ ⵔⴻⵙⴻⵔⴼⴻⵙ',
  'DZ Diaspora — Tous droits réservés':'ⴷⵣ ⴷⵉⴰⵙⴱⵓⵔⴰ — ⵜⵓⵓⵙ ⴷⵔⵓⵉⵜⵙ ⵔⴻⵙⴻⵔⴼⴻⵙ',
  'Date de début / تاريخ البداية':'ⴷⴰⵜⴻ ⴷⴻ ⴷⴻⴱⵓⵜ / تاريخ البداية',
  'Date souhaitée':'ⴷⴰⵜⴻ ⵙⵓⵓⵀⴰⵉⵜⴻⴻ',
  'Declaration obligatoire a partir de 5000€ pour les etrangers':'ⴷⴻⵙⵍⴰⵔⴰⵜⵉⵓⵏ ⵓⴱⵍⵉⴳⴰⵜⵓⵉⵔⴻ ⴰ ⴱⴰⵔⵜⵉⵔ ⴷⴻ 5000€ ⴱⵓⵓⵔ ⵍⴻⵙ ⴻⵜⵔⴰⵏⴳⴻⵔⵙ',
  'Decouverte':'ⴷⴻⵙⵓⵓⴼⴻⵔⵜⴻ',
  'Delai de traitement :':'ⴷⴻⵍⴰⵉ ⴷⴻ ⵜⵔⴰⵉⵜⴻⵎⴻⵏⵜ :',
  'Delais 2026 :':'ⴷⴻⵍⴰⵉⵙ 2026 :',
  'Demandez le certificat d urbanisme et le permis de construire':'ⴷⴻⵎⴰⵏⴷⴻⵣ ⵍⴻ ⵙⴻⵔⵜⵉⴼⵉⵙⴰⵜ ⴷ ⵓⵔⴱⴰⵏⵉⵙⵎⴻ ⴻⵜ ⵍⴻ ⴱⴻⵔⵎⵉⵙ ⴷⴻ ⵙⵓⵏⵙⵜⵔⵓⵉⵔⴻ',
  'Dentiste':'ⴷⴻⵏⵜⵉⵙⵜⴻ',
  'Deposer une annonce — DZ Diaspora':'ⴷⴻⴱⵓⵙⴻⵔ ⵓⵏⴻ ⴰⵏⵏⵓⵏⵙⴻ — ⴷⵣ ⴷⵉⴰⵙⴱⵓⵔⴰ',
  'Deposer une plainte en ligne':'ⴷⴻⴱⵓⵙⴻⵔ ⵓⵏⴻ ⴱⵍⴰⵉⵏⵜⴻ ⴻⵏ ⵍⵉⴳⵏⴻ',
  'Dermatologue':'ⴷⴻⵔⵎⴰⵜⵓⵍⵓⴳⵓⴻ',
  'Derniere mise a jour : janvier 2026':'ⴷⴻⵔⵏⵉⴻⵔⴻ ⵎⵉⵙⴻ ⴰ ⵊⵓⵓⵔ : ⵊⴰⵏⴼⵉⴻⵔ 2026',
  'Des contenus publies par des utilisateurs ou des liens externes':'ⴷⴻⵙ ⵙⵓⵏⵜⴻⵏⵓⵙ ⴱⵓⴱⵍⵉⴻⵙ ⴱⴰⵔ ⴷⴻⵙ ⵓⵜⵉⵍⵉⵙⴰⵜⴻⵓⵔⵙ ⵓⵓ ⴷⴻⵙ ⵍⵉⴻⵏⵙ ⴻⵅⵜⴻⵔⵏⴻⵙ',
  'Des decisions prises sur la base des informations du site':'ⴷⴻⵙ ⴷⴻⵙⵉⵙⵉⵓⵏⵙ ⴱⵔⵉⵙⴻⵙ ⵙⵓⵔ ⵍⴰ ⴱⴰⵙⴻ ⴷⴻⵙ ⵉⵏⴼⵓⵔⵎⴰⵜⵉⵓⵏⵙ ⴷⵓ ⵙⵉⵜⴻ',
  'Des dommages directs ou indirects resultant de l utilisation du site':'ⴷⴻⵙ ⴷⵓⵎⵎⴰⴳⴻⵙ ⴷⵉⵔⴻⵙⵜⵙ ⵓⵓ ⵉⵏⴷⵉⵔⴻⵙⵜⵙ ⵔⴻⵙⵓⵍⵜⴰⵏⵜ ⴷⴻ ⵍ ⵓⵜⵉⵍⵉⵙⴰⵜⵉⵓⵏ ⴷⵓ ⵙⵉⵜⴻ',
  'Des interruptions de service ou pertes de donnees':'ⴷⴻⵙ ⵉⵏⵜⴻⵔⵔⵓⴱⵜⵉⵓⵏⵙ ⴷⴻ ⵙⴻⵔⴼⵉⵙⴻ ⵓⵓ ⴱⴻⵔⵜⴻⵙ ⴷⴻ ⴷⵓⵏⵏⴻⴻⵙ',
  'Description':'ⴷⴻⵙⵙⵔⵉⴱⵜⵉⵓⵏ',
  'Description de l objet *':'ⴷⴻⵙⵙⵔⵉⴱⵜⵉⵓⵏ ⴷⴻ ⵍ ⵓⴱⵊⴻⵜ *',
  'Description de votre activité / message publicitaire *':'ⴷⴻⵙⵙⵔⵉⴱⵜⵉⵓⵏ ⴷⴻ ⴼⵓⵜⵔⴻ ⴰⵙⵜⵉⴼⵉⵜⴻ / ⵎⴻⵙⵙⴰⴳⴻ ⴱⵓⴱⵍⵉⵙⵉⵜⴰⵉⵔⴻ *',
  'Description de votre recherche *':'ⴷⴻⵙⵙⵔⵉⴱⵜⵉⵓⵏ ⴷⴻ ⴼⵓⵜⵔⴻ ⵔⴻⵙⵀⴻⵔⵙⵀⴻ *',
  'Devenir Pro':'ⴷⴻⴼⴻⵏⵉⵔ ⴱⵔⵓ',
  'Devenir Pro Metier — 20€/mois':'ⴷⴻⴼⴻⵏⵉⵔ ⴱⵔⵓ ⵎⴻⵜⵉⴻⵔ — 20€/ⵎⵓⵉⵙ',
  'Devenir Pro — etre reference (medecin, avocat, notaire, pharmacien...)':'ⴷⴻⴼⴻⵏⵉⵔ ⴱⵔⵓ — ⴻⵜⵔⴻ ⵔⴻⴼⴻⵔⴻⵏⵙⴻ (ⵎⴻⴷⴻⵙⵉⵏ, ⴰⴼⵓⵙⴰⵜ, ⵏⵓⵜⴰⵉⵔⴻ, ⴱⵀⴰⵔⵎⴰⵙⵉⴻⵏ...)',
  'Devises :':'ⴷⴻⴼⵉⵙⴻⵙ :',
  'Direction Generale des Douanes — simulateur CCR':'ⴷⵉⵔⴻⵙⵜⵉⵓⵏ ⴳⴻⵏⴻⵔⴰⵍⴻ ⴷⴻⵙ ⴷⵓⵓⴰⵏⴻⵙ — ⵙⵉⵎⵓⵍⴰⵜⴻⵓⵔ ⵙⵙⵔ',
  'Disponible sur 69 wilayas':'ⴷⵉⵙⴱⵓⵏⵉⴱⵍⴻ ⵙⵓⵔ 69 ⵡⵉⵍⴰⵢⴰⵙ',
  'Djamaa El Djazair — Grande Mosquee d Alger':'ⴷⵊⴰⵎⴰⴰ ⴻⵍ ⴷⵊⴰⵣⴰⵉⵔ — ⴳⵔⴰⵏⴷⴻ ⵎⵓⵙⵇⵓⴻⴻ ⴷ ⴰⵍⴳⴻⵔ',
  'Djanet':'ⴷⵊⴰⵏⴻⵜ',
  'Djelfa':'ⴷⵊⴻⵍⴼⴰ',
  'Djemila — Site romain UNESCO':'ⴷⵊⴻⵎⵉⵍⴰ — ⵙⵉⵜⴻ ⵔⵓⵎⴰⵉⵏ ⵓⵏⴻⵙⵙⵓ',
  'Documents requis :':'ⴷⵓⵙⵓⵎⴻⵏⵜⵙ ⵔⴻⵇⵓⵉⵙ :',
  'Double vente':'ⴷⵓⵓⴱⵍⴻ ⴼⴻⵏⵜⴻ',
  'Droit commercial':'ⴷⵔⵓⵉⵜ ⵙⵓⵎⵎⴻⵔⵙⵉⴰⵍ',
  'Droit de la famille (divorce, héritage...)':'ⴷⵔⵓⵉⵜ ⴷⴻ ⵍⴰ ⴼⴰⵎⵉⵍⵍⴻ (ⴷⵉⴼⵓⵔⵙⴻ, ⵀⴻⵔⵉⵜⴰⴳⴻ...)',
  'Droit du travail':'ⴷⵔⵓⵉⵜ ⴷⵓ ⵜⵔⴰⴼⴰⵉⵍ',
  'Droit immobilier':'ⴷⵔⵓⵉⵜ ⵉⵎⵎⵓⴱⵉⵍⵉⴻⵔ',
  'Droit pénal':'ⴷⵔⵓⵉⵜ ⴱⴻⵏⴰⵍ',
  'Durée de la campagne':'ⴷⵓⵔⴻⴻ ⴷⴻ ⵍⴰ ⵙⴰⵎⴱⴰⴳⵏⴻ',
  'Décrivez brièvement votre situation':'ⴷⴻⵙⵔⵉⴼⴻⵣ ⴱⵔⵉⴻⴼⴻⵎⴻⵏⵜ ⴼⵓⵜⵔⴻ ⵙⵉⵜⵓⴰⵜⵉⵓⵏ',
  'Décrivez vos symptômes ou votre besoin *':'ⴷⴻⵙⵔⵉⴼⴻⵣ ⴼⵓⵙ ⵙⵢⵎⴱⵜⵓⵎⴻⵙ ⵓⵓ ⴼⵓⵜⵔⴻ ⴱⴻⵙⵓⵉⵏ *',
  'Décrivez votre situation *':'ⴷⴻⵙⵔⵉⴼⴻⵣ ⴼⵓⵜⵔⴻ ⵙⵉⵜⵓⴰⵜⵉⵓⵏ *',
  'Déposer une demande — DZ Diaspora':'ⴷⴻⴱⵓⵙⴻⵔ ⵓⵏⴻ ⴷⴻⵎⴰⵏⴷⴻ — ⴷⵣ ⴷⵉⴰⵙⴱⵓⵔⴰ',
  'Détails':'ⴷⴻⵜⴰⵉⵍⵙ',
  'El Abiodh Sidi Cheikh':'ⴻⵍ ⴰⴱⵉⵓⴷⵀ ⵙⵉⴷⵉ ⵙⵀⴻⵉⴽⵀ',
  'El Aricha':'ⴻⵍ ⴰⵔⵉⵙⵀⴰ',
  'El Bayadh':'ⴻⵍ ⴱⴰⵢⴰⴷⵀ',
  'El Kantara':'ⴻⵍ ⴽⴰⵏⵜⴰⵔⴰ',
  'El MGhair':'ⴻⵍ ⵎⴳⵀⴰⵉⵔ',
  'El Menia':'ⴻⵍ ⵎⴻⵏⵉⴰ',
  'El Oued':'ⴻⵍ ⵓⵓⴻⴷ',
  'El Tarf':'ⴻⵍ ⵜⴰⵔⴼ',
  'Email':'ⴻⵎⴰⵉⵍ',
  'Email (non publié)':'ⴻⵎⴰⵉⵍ (ⵏⵓⵏ ⴱⵓⴱⵍⵉⴻ)',
  'Email *':'ⴻⵎⴰⵉⵍ *',
  'Email / البريد':'ⴻⵎⴰⵉⵍ / البريد',
  'Email / البريد الإلكتروني':'ⴻⵎⴰⵉⵍ / البريد الالكتروني',
  'Email destinataire *':'ⴻⵎⴰⵉⵍ ⴷⴻⵙⵜⵉⵏⴰⵜⴰⵉⵔⴻ *',
  'En cabinet':'ⴻⵏ ⵙⴰⴱⵉⵏⴻⵜ',
  'En cas d accident de la route : la methode P.A.S':'ⴻⵏ ⵙⴰⵙ ⴷ ⴰⵙⵙⵉⴷⴻⵏⵜ ⴷⴻ ⵍⴰ ⵔⵓⵓⵜⴻ : ⵍⴰ ⵎⴻⵜⵀⵓⴷⴻ ⴱ.ⴰ.ⵙ',
  'En cas d agression : la methode P.A.S':'ⴻⵏ ⵙⴰⵙ ⴷ ⴰⴳⵔⴻⵙⵙⵉⵓⵏ : ⵍⴰ ⵎⴻⵜⵀⵓⴷⴻ ⴱ.ⴰ.ⵙ',
  'En nous contactant, vous acceptez nos':'ⴻⵏ ⵏⵓⵓⵙ ⵙⵓⵏⵜⴰⵙⵜⴰⵏⵜ, ⴼⵓⵓⵙ ⴰⵙⵙⴻⴱⵜⴻⵣ ⵏⵓⵙ',
  'En tête de l\'annuaire':'ⴻⵏ ⵜⴻⵜⴻ ⴷⴻ ⵍ\'ⴰⵏⵏⵓⴰⵉⵔⴻ',
  'En vous inscrivant, vous acceptez nos':'ⴻⵏ ⴼⵓⵓⵙ ⵉⵏⵙⵙⵔⵉⴼⴰⵏⵜ, ⴼⵓⵓⵙ ⴰⵙⵙⴻⴱⵜⴻⵣ ⵏⵓⵙ',
  'Entreprises algériennes':'ⴻⵏⵜⵔⴻⴱⵔⵉⵙⴻⵙ ⴰⵍⴳⴻⵔⵉⴻⵏⵏⴻⵙ',
  'Envoyer le message':'ⴻⵏⴼⵓⵢⴻⵔ ⵍⴻ ⵎⴻⵙⵙⴰⴳⴻ',
  'Envoyez un email à un pro ou un client — accès, confirmation, information...':'ⴻⵏⴼⵓⵢⴻⵣ ⵓⵏ ⴻⵎⴰⵉⵍ ⴰ ⵓⵏ ⴱⵔⵓ ⵓⵓ ⵓⵏ ⵙⵍⵉⴻⵏⵜ — ⴰⵙⵙⴻⵙ, ⵙⵓⵏⴼⵉⵔⵎⴰⵜⵉⵓⵏ, ⵉⵏⴼⵓⵔⵎⴰⵜⵉⵓⵏ...',
  'Espace Professionnel — DZ Diaspora':'ⴻⵙⴱⴰⵙⴻ ⴱⵔⵓⴼⴻⵙⵙⵉⵓⵏⵏⴻⵍ — ⴷⵣ ⴷⵉⴰⵙⴱⵓⵔⴰ',
  'Espace Publicitaire — DZ Diaspora':'ⴻⵙⴱⴰⵙⴻ ⴱⵓⴱⵍⵉⵙⵉⵜⴰⵉⵔⴻ — ⴷⵣ ⴷⵉⴰⵙⴱⵓⵔⴰ',
  'Espace pub':'ⴻⵙⴱⴰⵙⴻ ⴱⵓⴱ',
  'Espace réservé aux professionnels':'ⴻⵙⴱⴰⵙⴻ ⵔⴻⵙⴻⵔⴼⴻ ⴰⵓⵅ ⴱⵔⵓⴼⴻⵙⵙⵉⵓⵏⵏⴻⵍⵙ',
  'Espèces / نقدي':'ⴻⵙⴱⴻⵙⴻⵙ / نقدي',
  'Est-ce que c est dangereux d installer un APK ?':'ⴻⵙⵜ-ⵙⴻ ⵇⵓⴻ ⵙ ⴻⵙⵜ ⴷⴰⵏⴳⴻⵔⴻⵓⵅ ⴷ ⵉⵏⵙⵜⴰⵍⵍⴻⵔ ⵓⵏ ⴰⴱⴽ ?',
  'Etablissement de reference pour le credit immobilier en Algerie.':'ⴻⵜⴰⴱⵍⵉⵙⵙⴻⵎⴻⵏⵜ ⴷⴻ ⵔⴻⴼⴻⵔⴻⵏⵙⴻ ⴱⵓⵓⵔ ⵍⴻ ⵙⵔⴻⴷⵉⵜ ⵉⵎⵎⵓⴱⵉⵍⵉⴻⵔ ⴻⵏ ⴰⵍⴳⴻⵔⵉⴻ.',
  'Exemptions :':'ⴻⵅⴻⵎⴱⵜⵉⵓⵏⵙ :',
  'Fausses agences de voyage':'ⴼⴰⵓⵙⵙⴻⵙ ⴰⴳⴻⵏⵙⴻⵙ ⴷⴻ ⴼⵓⵢⴰⴳⴻ',
  'Fausses petites annonces':'ⴼⴰⵓⵙⵙⴻⵙ ⴱⴻⵜⵉⵜⴻⵙ ⴰⵏⵏⵓⵏⵙⴻⵙ',
  'Faux avocats':'ⴼⴰⵓⵅ ⴰⴼⵓⵙⴰⵜⵙ',
  'Faux concours et loteries':'ⴼⴰⵓⵅ ⵙⵓⵏⵙⵓⵓⵔⵙ ⴻⵜ ⵍⵓⵜⴻⵔⵉⴻⵙ',
  'Faux dossiers CCR':'ⴼⴰⵓⵅ ⴷⵓⵙⵙⵉⴻⵔⵙ ⵙⵙⵔ',
  'Faux guides touristiques':'ⴼⴰⵓⵅ ⴳⵓⵉⴷⴻⵙ ⵜⵓⵓⵔⵉⵙⵜⵉⵇⵓⴻⵙ',
  'Faux intermediaires consulaires':'ⴼⴰⵓⵅ ⵉⵏⵜⴻⵔⵎⴻⴷⵉⴰⵉⵔⴻⵙ ⵙⵓⵏⵙⵓⵍⴰⵉⵔⴻⵙ',
  'Faux investissements':'ⴼⴰⵓⵅ ⵉⵏⴼⴻⵙⵜⵉⵙⵙⴻⵎⴻⵏⵜⵙ',
  'Faux notaires':'ⴼⴰⵓⵅ ⵏⵓⵜⴰⵉⵔⴻⵙ',
  'Faux promoteurs':'ⴼⴰⵓⵅ ⴱⵔⵓⵎⵓⵜⴻⵓⵔⵙ',
  'Faux vendeurs':'ⴼⴰⵓⵅ ⴼⴻⵏⴷⴻⵓⵔⵙ',
  'Fiche Mise en Avant':'ⴼⵉⵙⵀⴻ ⵎⵉⵙⴻ ⴻⵏ ⴰⴼⴰⵏⵜ',
  'Fiche pro complète vérifiée ✅':'ⴼⵉⵙⵀⴻ ⴱⵔⵓ ⵙⵓⵎⴱⵍⴻⵜⴻ ⴼⴻⵔⵉⴼⵉⴻⴻ ✅',
  'Fiche professionnelle complete':'ⴼⵉⵙⵀⴻ ⴱⵔⵓⴼⴻⵙⵙⵉⵓⵏⵏⴻⵍⵍⴻ ⵙⵓⵎⴱⵍⴻⵜⴻ',
  'Fichier publicitaire (photo, vidéo, logo)':'ⴼⵉⵙⵀⵉⴻⵔ ⴱⵓⴱⵍⵉⵙⵉⵜⴰⵉⵔⴻ (ⴱⵀⵓⵜⵓ, ⴼⵉⴷⴻⵓ, ⵍⵓⴳⵓ)',
  'Filiale du groupe BNP Paribas, forte orientation entreprises.':'ⴼⵉⵍⵉⴰⵍⴻ ⴷⵓ ⴳⵔⵓⵓⴱⴻ ⴱⵏⴱ ⴱⴰⵔⵉⴱⴰⵙ, ⴼⵓⵔⵜⴻ ⵓⵔⵉⴻⵏⵜⴰⵜⵉⵓⵏ ⴻⵏⵜⵔⴻⴱⵔⵉⵙⴻⵙ.',
  'Filiale du groupe BPCE, services bancaires et financiers.':'ⴼⵉⵍⵉⴰⵍⴻ ⴷⵓ ⴳⵔⵓⵓⴱⴻ ⴱⴱⵙⴻ, ⵙⴻⵔⴼⵉⵙⴻⵙ ⴱⴰⵏⵙⴰⵉⵔⴻⵙ ⴻⵜ ⴼⵉⵏⴰⵏⵙⵉⴻⵔⵙ.',
  'Filiale du groupe francais, services complets particuliers et entreprises.':'ⴼⵉⵍⵉⴰⵍⴻ ⴷⵓ ⴳⵔⵓⵓⴱⴻ ⴼⵔⴰⵏⵙⴰⵉⵙ, ⵙⴻⵔⴼⵉⵙⴻⵙ ⵙⵓⵎⴱⵍⴻⵜⵙ ⴱⴰⵔⵜⵉⵙⵓⵍⵉⴻⵔⵙ ⴻⵜ ⴻⵏⵜⵔⴻⴱⵔⵉⵙⴻⵙ.',
  'Finance':'ⴼⵉⵏⴰⵏⵙⴻ',
  'Finance Algerie — Banques, devises et financement immobilier':'ⴼⵉⵏⴰⵏⵙⴻ ⴰⵍⴳⴻⵔⵉⴻ — ⴱⴰⵏⵇⵓⴻⵙ, ⴷⴻⴼⵉⵙⴻⵙ ⴻⵜ ⴼⵉⵏⴰⵏⵙⴻⵎⴻⵏⵜ ⵉⵎⵎⵓⴱⵉⵍⵉⴻⵔ',
  'Financement immobilier':'ⴼⵉⵏⴰⵏⵙⴻⵎⴻⵏⵜ ⵉⵎⵎⵓⴱⵉⵍⵉⴻⵔ',
  'Formalites douanieres et declaration de devises':'ⴼⵓⵔⵎⴰⵍⵉⵜⴻⵙ ⴷⵓⵓⴰⵏⵉⴻⵔⴻⵙ ⴻⵜ ⴷⴻⵙⵍⴰⵔⴰⵜⵉⵓⵏ ⴷⴻ ⴷⴻⴼⵉⵙⴻⵙ',
  'Format publicitaire':'ⴼⵓⵔⵎⴰⵜ ⴱⵓⴱⵍⵉⵙⵉⵜⴰⵉⵔⴻ',
  'Formulaire d inscription':'ⴼⵓⵔⵎⵓⵍⴰⵉⵔⴻ ⴷ ⵉⵏⵙⵙⵔⵉⴱⵜⵉⵓⵏ',
  'Formulaire de contact':'ⴼⵓⵔⵎⵓⵍⴰⵉⵔⴻ ⴷⴻ ⵙⵓⵏⵜⴰⵙⵜ',
  'Formule annuelle : 240€/an (2 mois offerts)':'ⴼⵓⵔⵎⵓⵍⴻ ⴰⵏⵏⵓⴻⵍⵍⴻ : 240€/ⴰⵏ (2 ⵎⵓⵉⵙ ⵓⴼⴼⴻⵔⵜⵙ)',
  'Français':'ⴼⵔⴰⵏⵙⴰⵉⵙ',
  'Fréquence d\'affichage':'ⴼⵔⴻⵇⵓⴻⵏⵙⴻ ⴷ\'ⴰⴼⴼⵉⵙⵀⴰⴳⴻ',
  'GNV':'ⴳⵏⴼ',
  'Gaz et electricite (Sonelgaz)':'ⴳⴰⵣ ⴻⵜ ⴻⵍⴻⵙⵜⵔⵉⵙⵉⵜⴻ (ⵙⵓⵏⴻⵍⴳⴰⵣ)',
  'Gendarmerie Nationale — urgences touristes':'ⴳⴻⵏⴷⴰⵔⵎⴻⵔⵉⴻ ⵏⴰⵜⵉⵓⵏⴰⵍⴻ — ⵓⵔⴳⴻⵏⵙⴻⵙ ⵜⵓⵓⵔⵉⵙⵜⴻⵙ',
  'Gendarmerie nationale':'ⴳⴻⵏⴷⴰⵔⵎⴻⵔⵉⴻ ⵏⴰⵜⵉⵓⵏⴰⵍⴻ',
  'Ghardaia':'ⴳⵀⴰⵔⴷⴰⵉⴰ',
  'Ghardaia — M Zab UNESCO':'ⴳⵀⴰⵔⴷⴰⵉⴰ — ⵎ ⵣⴰⴱ ⵓⵏⴻⵙⵙⵓ',
  'Ghardaïa':'ⴳⵀⴰⵔⴷⴰⵉⴰ',
  'Gratuit et sans engagement. Les pros vous contactent directement.':'ⴳⵔⴰⵜⵓⵉⵜ ⴻⵜ ⵙⴰⵏⵙ ⴻⵏⴳⴰⴳⴻⵎⴻⵏⵜ. ⵍⴻⵙ ⴱⵔⵓⵙ ⴼⵓⵓⵙ ⵙⵓⵏⵜⴰⵙⵜⴻⵏⵜ ⴷⵉⵔⴻⵙⵜⴻⵎⴻⵏⵜ.',
  'Gratuit à l utilisation':'ⴳⵔⴰⵜⵓⵉⵜ ⴰ ⵍ ⵓⵜⵉⵍⵉⵙⴰⵜⵉⵓⵏ',
  'Guelma':'ⴳⵓⴻⵍⵎⴰ',
  'Guide d installation en 5 etapes':'ⴳⵓⵉⴷⴻ ⴷ ⵉⵏⵙⵜⴰⵍⵍⴰⵜⵉⵓⵏ ⴻⵏ 5 ⴻⵜⴰⴱⴻⵙ',
  'Gulf Bank Algerie (AGB)':'ⴳⵓⵍⴼ ⴱⴰⵏⴽ ⴰⵍⴳⴻⵔⵉⴻ (ⴰⴳⴱ)',
  'Gynecologue':'ⴳⵢⵏⴻⵙⵓⵍⵓⴳⵓⴻ',
  'Gynécologue':'ⴳⵢⵏⴻⵙⵓⵍⵓⴳⵓⴻ',
  'Hebergements et parfois trajets combines pour votre sejour en Algerie.':'ⵀⴻⴱⴻⵔⴳⴻⵎⴻⵏⵜⵙ ⴻⵜ ⴱⴰⵔⴼⵓⵉⵙ ⵜⵔⴰⵊⴻⵜⵙ ⵙⵓⵎⴱⵉⵏⴻⵙ ⴱⵓⵓⵔ ⴼⵓⵜⵔⴻ ⵙⴻⵊⵓⵓⵔ ⴻⵏ ⴰⵍⴳⴻⵔⵉⴻ.',
  'Hebergeur :':'ⵀⴻⴱⴻⵔⴳⴻⵓⵔ :',
  'Heritiers caches (indivision)':'ⵀⴻⵔⵉⵜⵉⴻⵔⵙ ⵙⴰⵙⵀⴻⵙ (ⵉⵏⴷⵉⴼⵉⵙⵉⵓⵏ)',
  'Horaires de prière':'ⵀⵓⵔⴰⵉⵔⴻⵙ ⴷⴻ ⴱⵔⵉⴻⵔⴻ',
  'Il sera publié après validation sous 24h.':'ⵉⵍ ⵙⴻⵔⴰ ⴱⵓⴱⵍⵉⴻ ⴰⴱⵔⴻⵙ ⴼⴰⵍⵉⴷⴰⵜⵉⵓⵏ ⵙⵓⵓⵙ 24ⵀ.',
  'Illizi':'ⵉⵍⵍⵉⵣⵉ',
  'Ils nous font confiance':'ⵉⵍⵙ ⵏⵓⵓⵙ ⴼⵓⵏⵜ ⵙⵓⵏⴼⵉⴰⵏⵙⴻ',
  'Image / GIF':'ⵉⵎⴰⴳⴻ / ⴳⵉⴼ',
  'Image ou GIF animé':'ⵉⵎⴰⴳⴻ ⵓⵓ ⴳⵉⴼ ⴰⵏⵉⵎⴻ',
  'Immobilier':'ⵉⵎⵎⵓⴱⵉⵍⵉⴻⵔ',
  'Immobilier Algerie — Financement, AADL et prevention arnaques':'ⵉⵎⵎⵓⴱⵉⵍⵉⴻⵔ ⴰⵍⴳⴻⵔⵉⴻ — ⴼⵉⵏⴰⵏⵙⴻⵎⴻⵏⵜ, ⴰⴰⴷⵍ ⴻⵜ ⴱⵔⴻⴼⴻⵏⵜⵉⵓⵏ ⴰⵔⵏⴰⵇⵓⴻⵙ',
  'Immobilier, vehicules, covoiturage et services entre la diaspora et l Algerie.':'ⵉⵎⵎⵓⴱⵉⵍⵉⴻⵔ, ⴼⴻⵀⵉⵙⵓⵍⴻⵙ, ⵙⵓⴼⵓⵉⵜⵓⵔⴰⴳⴻ ⴻⵜ ⵙⴻⵔⴼⵉⵙⴻⵙ ⴻⵏⵜⵔⴻ ⵍⴰ ⴷⵉⴰⵙⴱⵓⵔⴰ ⴻⵜ ⵍ ⴰⵍⴳⴻⵔⵉⴻ.',
  'Important :':'ⵉⵎⴱⵓⵔⵜⴰⵏⵜ :',
  'In Guezzam':'ⵉⵏ ⴳⵓⴻⵣⵣⴰⵎ',
  'In Salah':'ⵉⵏ ⵙⴰⵍⴰⵀ',
  'Informations du Professionnel / معلومات المهني':'ⵉⵏⴼⵓⵔⵎⴰⵜⵉⵓⵏⵙ ⴷⵓ ⴱⵔⵓⴼⴻⵙⵙⵉⵓⵏⵏⴻⵍ / معلومات المهني',
  'Inscription':'ⵉⵏⵙⵙⵔⵉⴱⵜⵉⵓⵏ',
  'Inscription Professionnel — DZ Diaspora':'ⵉⵏⵙⵙⵔⵉⴱⵜⵉⵓⵏ ⴱⵔⵓⴼⴻⵙⵙⵉⵓⵏⵏⴻⵍ — ⴷⵣ ⴷⵉⴰⵙⴱⵓⵔⴰ',
  'Inscrivez-vous comme professionnel pour accéder aux demandes clients.':'ⵉⵏⵙⵙⵔⵉⴼⴻⵣ-ⴼⵓⵓⵙ ⵙⵓⵎⵎⴻ ⴱⵔⵓⴼⴻⵙⵙⵉⵓⵏⵏⴻⵍ ⴱⵓⵓⵔ ⴰⵙⵙⴻⴷⴻⵔ ⴰⵓⵅ ⴷⴻⵎⴰⵏⴷⴻⵙ ⵙⵍⵉⴻⵏⵜⵙ.',
  'Installer DZ Diaspora sur Android':'ⵉⵏⵙⵜⴰⵍⵍⴻⵔ ⴷⵣ ⴷⵉⴰⵙⴱⵓⵔⴰ ⵙⵓⵔ ⴰⵏⴷⵔⵓⵉⴷ',
  'Installer l application':'ⵉⵏⵙⵜⴰⵍⵍⴻⵔ ⵍ ⴰⴱⴱⵍⵉⵙⴰⵜⵉⵓⵏ',
  'Intégrée dans le fil presse':'ⵉⵏⵜⴻⴳⵔⴻⴻ ⴷⴰⵏⵙ ⵍⴻ ⴼⵉⵍ ⴱⵔⴻⵙⵙⴻ',
  'J accepte les':'ⵊ ⴰⵙⵙⴻⴱⵜⴻ ⵍⴻⵙ',
  'JPG, PNG, GIF, MP4 — max 50MB':'ⵊⴱⴳ, ⴱⵏⴳ, ⴳⵉⴼ, ⵎⴱ4 — ⵎⴰⵅ 50ⵎⴱ',
  'Je suis agence immobiliere — avez-vous des tarifs specifiques ?':'ⵊⴻ ⵙⵓⵉⵙ ⴰⴳⴻⵏⵙⴻ ⵉⵎⵎⵓⴱⵉⵍⵉⴻⵔⴻ — ⴰⴼⴻⵣ-ⴼⵓⵓⵙ ⴷⴻⵙ ⵜⴰⵔⵉⴼⵙ ⵙⴱⴻⵙⵉⴼⵉⵇⵓⴻⵙ ?',
  'Jijel':'ⵊⵉⵊⴻⵍ',
  'Juridique':'ⵊⵓⵔⵉⴷⵉⵇⵓⴻ',
  'Justice':'ⵊⵓⵙⵜⵉⵙⴻ',
  'Justice Algerie — Tribunaux, avocats et plainte en ligne':'ⵊⵓⵙⵜⵉⵙⴻ ⴰⵍⴳⴻⵔⵉⴻ — ⵜⵔⵉⴱⵓⵏⴰⵓⵅ, ⴰⴼⵓⵙⴰⵜⵙ ⴻⵜ ⴱⵍⴰⵉⵏⵜⴻ ⴻⵏ ⵍⵉⴳⵏⴻ',
  'Justificatifs :':'ⵊⵓⵙⵜⵉⴼⵉⵙⴰⵜⵉⴼⵙ :',
  'Kabyle':'ⴽⴰⴱⵢⵍⴻ',
  'Khenchela':'ⴽⵀⴻⵏⵙⵀⴻⵍⴰ',
  'Ksar Chellala':'ⴽⵙⴰⵔ ⵙⵀⴻⵍⵍⴰⵍⴰ',
  'Ksar El Boukhari':'ⴽⵙⴰⵔ ⴻⵍ ⴱⵓⵓⴽⵀⴰⵔⵉ',
  'L application se met-elle a jour automatiquement ?':'ⵍ ⴰⴱⴱⵍⵉⵙⴰⵜⵉⵓⵏ ⵙⴻ ⵎⴻⵜ-ⴻⵍⵍⴻ ⴰ ⵊⵓⵓⵔ ⴰⵓⵜⵓⵎⴰⵜⵉⵇⵓⴻⵎⴻⵏⵜ ?',
  'L editeur ne saurait etre tenu responsable :':'ⵍ ⴻⴷⵉⵜⴻⵓⵔ ⵏⴻ ⵙⴰⵓⵔⴰⵉⵜ ⴻⵜⵔⴻ ⵜⴻⵏⵓ ⵔⴻⵙⴱⵓⵏⵙⴰⴱⵍⴻ :',
  'LPP — Logement Promotionnel Public':'ⵍⴱⴱ — ⵍⵓⴳⴻⵎⴻⵏⵜ ⴱⵔⵓⵎⵓⵜⵉⵓⵏⵏⴻⵍ ⴱⵓⴱⵍⵉⵙ',
  'La promotion d activites illegales ou la vente de produits interdits':'ⵍⴰ ⴱⵔⵓⵎⵓⵜⵉⵓⵏ ⴷ ⴰⵙⵜⵉⴼⵉⵜⴻⵙ ⵉⵍⵍⴻⴳⴰⵍⴻⵙ ⵓⵓ ⵍⴰ ⴼⴻⵏⵜⴻ ⴷⴻ ⴱⵔⵓⴷⵓⵉⵜⵙ ⵉⵏⵜⴻⵔⴷⵉⵜⵙ',
  'Laghouat':'ⵍⴰⴳⵀⵓⵓⴰⵜ',
  'Laisser un avis — DZ Diaspora':'ⵍⴰⵉⵙⵙⴻⵔ ⵓⵏ ⴰⴼⵉⵙ — ⴷⵣ ⴷⵉⴰⵙⴱⵓⵔⴰ',
  'Lancer l application':'ⵍⴰⵏⵙⴻⵔ ⵍ ⴰⴱⴱⵍⵉⵙⴰⵜⵉⵓⵏ',
  'Langue de communication souhaitée':'ⵍⴰⵏⴳⵓⴻ ⴷⴻ ⵙⵓⵎⵎⵓⵏⵉⵙⴰⵜⵉⵓⵏ ⵙⵓⵓⵀⴰⵉⵜⴻⴻ',
  'Langue souhaitée':'ⵍⴰⵏⴳⵓⴻ ⵙⵓⵓⵀⴰⵉⵜⴻⴻ',
  'Langues':'ⵍⴰⵏⴳⵓⴻⵙ',
  'Langues (FR/AR/EN/中)':'ⵍⴰⵏⴳⵓⴻⵙ (ⴼⵔ/ⴰⵔ/ⴻⵏ/中)',
  'Langues parlees':'ⵍⴰⵏⴳⵓⴻⵙ ⴱⴰⵔⵍⴻⴻⵙ',
  'Langues parlées affichées':'ⵍⴰⵏⴳⵓⴻⵙ ⴱⴰⵔⵍⴻⴻⵙ ⴰⴼⴼⵉⵙⵀⴻⴻⵙ',
  'Le livret foncier':'ⵍⴻ ⵍⵉⴼⵔⴻⵜ ⴼⵓⵏⵙⵉⴻⵔ',
  'Le plan Starter : 1 annonce par jour, comment ca marche ?':'ⵍⴻ ⴱⵍⴰⵏ ⵙⵜⴰⵔⵜⴻⵔ : 1 ⴰⵏⵏⵓⵏⵙⴻ ⴱⴰⵔ ⵊⵓⵓⵔ, ⵙⵓⵎⵎⴻⵏⵜ ⵙⴰ ⵎⴰⵔⵙⵀⴻ ?',
  'Le portail N°1 de la':'ⵍⴻ ⴱⵓⵔⵜⴰⵉⵍ ⵏ°1 ⴷⴻ ⵍⴰ',
  'Le professionnel signe ci-dessous / يوقع المهني أدناه':'ⵍⴻ ⴱⵔⵓⴼⴻⵙⵙⵉⵓⵏⵏⴻⵍ ⵙⵉⴳⵏⴻ ⵙⵉ-ⴷⴻⵙⵙⵓⵓⵙ / يوقع المهني ادناه',
  'Le professionnel vous confirmera sous 24h par email ou téléphone.':'ⵍⴻ ⴱⵔⵓⴼⴻⵙⵙⵉⵓⵏⵏⴻⵍ ⴼⵓⵓⵙ ⵙⵓⵏⴼⵉⵔⵎⴻⵔⴰ ⵙⵓⵓⵙ 24ⵀ ⴱⴰⵔ ⴻⵎⴰⵉⵍ ⵓⵓ ⵜⴻⵍⴻⴱⵀⵓⵏⴻ.',
  'Le site':'ⵍⴻ ⵙⵉⵜⴻ',
  'Legalisation de documents francais :':'ⵍⴻⴳⴰⵍⵉⵙⴰⵜⵉⵓⵏ ⴷⴻ ⴷⵓⵙⵓⵎⴻⵏⵜⵙ ⴼⵔⴰⵏⵙⴰⵉⵙ :',
  'Les Sablettes — Alger':'ⵍⴻⵙ ⵙⴰⴱⵍⴻⵜⵜⴻⵙ — ⴰⵍⴳⴻⵔ',
  'Les annonces frauduleuses, trompeuses ou portant atteinte aux droits d autrui':'ⵍⴻⵙ ⴰⵏⵏⵓⵏⵙⴻⵙ ⴼⵔⴰⵓⴷⵓⵍⴻⵓⵙⴻⵙ, ⵜⵔⵓⵎⴱⴻⵓⵙⴻⵙ ⵓⵓ ⴱⵓⵔⵜⴰⵏⵜ ⴰⵜⵜⴻⵉⵏⵜⴻ ⴰⵓⵅ ⴷⵔⵓⵉⵜⵙ ⴷ ⴰⵓⵜⵔⵓⵉ',
  'Les clients vous contactent directement par telephone ou email.':'ⵍⴻⵙ ⵙⵍⵉⴻⵏⵜⵙ ⴼⵓⵓⵙ ⵙⵓⵏⵜⴰⵙⵜⴻⵏⵜ ⴷⵉⵔⴻⵙⵜⴻⵎⴻⵏⵜ ⴱⴰⵔ ⵜⴻⵍⴻⴱⵀⵓⵏⴻ ⵓⵓ ⴻⵎⴰⵉⵍ.',
  'Les professionnels concernés vont vous contacter sous 24-48h.':'ⵍⴻⵙ ⴱⵔⵓⴼⴻⵙⵙⵉⵓⵏⵏⴻⵍⵙ ⵙⵓⵏⵙⴻⵔⵏⴻⵙ ⴼⵓⵏⵜ ⴼⵓⵓⵙ ⵙⵓⵏⵜⴰⵙⵜⴻⵔ ⵙⵓⵓⵙ 24-48ⵀ.',
  'Liaisons Alger-Marseille, Oran-Marseille, Bejaia-Marseille.':'ⵍⵉⴰⵉⵙⵓⵏⵙ ⴰⵍⴳⴻⵔ-ⵎⴰⵔⵙⴻⵉⵍⵍⴻ, ⵓⵔⴰⵏ-ⵎⴰⵔⵙⴻⵉⵍⵍⴻ, ⴱⴻⵊⴰⵉⴰ-ⵎⴰⵔⵙⴻⵉⵍⵍⴻ.',
  'Liaisons au depart d Alicante vers l Algerie.':'ⵍⵉⴰⵉⵙⵓⵏⵙ ⴰⵓ ⴷⴻⴱⴰⵔⵜ ⴷ ⴰⵍⵉⵙⴰⵏⵜⴻ ⴼⴻⵔⵙ ⵍ ⴰⵍⴳⴻⵔⵉⴻ.',
  'Lien cliquable vers votre site':'ⵍⵉⴻⵏ ⵙⵍⵉⵇⵓⴰⴱⵍⴻ ⴼⴻⵔⵙ ⴼⵓⵜⵔⴻ ⵙⵉⵜⴻ',
  'Lien de destination (URL de votre site, WhatsApp, etc.)':'ⵍⵉⴻⵏ ⴷⴻ ⴷⴻⵙⵜⵉⵏⴰⵜⵉⵓⵏ (ⵓⵔⵍ ⴷⴻ ⴼⵓⵜⵔⴻ ⵙⵉⵜⴻ, ⵡⵀⴰⵜⵙⴰⴱⴱ, ⴻⵜⵙ.)',
  'Lien vers votre site ou WhatsApp':'ⵍⵉⴻⵏ ⴼⴻⵔⵙ ⴼⵓⵜⵔⴻ ⵙⵉⵜⴻ ⵓⵓ ⵡⵀⴰⵜⵙⴰⴱⴱ',
  'Lieu ou l objet a ete trouve *':'ⵍⵉⴻⵓ ⵓⵓ ⵍ ⵓⴱⵊⴻⵜ ⴰ ⴻⵜⴻ ⵜⵔⵓⵓⴼⴻ *',
  'Local commercial':'ⵍⵓⵙⴰⵍ ⵙⵓⵎⵎⴻⵔⵙⵉⴰⵍ',
  'Long terme':'ⵍⵓⵏⴳ ⵜⴻⵔⵎⴻ',
  'Lotissement Saidani Belkacem, Hydra, Alger':'ⵍⵓⵜⵉⵙⵙⴻⵎⴻⵏⵜ ⵙⴰⵉⴷⴰⵏⵉ ⴱⴻⵍⴽⴰⵙⴻⵎ, ⵀⵢⴷⵔⴰ, ⴰⵍⴳⴻⵔ',
  'Low cost — Alger, Oran, Constantine, Tlemcen depuis plusieurs villes francaises.':'ⵍⵓⵡ ⵙⵓⵙⵜ — ⴰⵍⴳⴻⵔ, ⵓⵔⴰⵏ, ⵙⵓⵏⵙⵜⴰⵏⵜⵉⵏⴻ, ⵜⵍⴻⵎⵙⴻⵏ ⴷⴻⴱⵓⵉⵙ ⴱⵍⵓⵙⵉⴻⵓⵔⵙ ⴼⵉⵍⵍⴻⵙ ⴼⵔⴰⵏⵙⴰⵉⵙⴻⵙ.',
  'MSila':'ⵎⵙⵉⵍⴰ',
  'Mascara':'ⵎⴰⵙⵙⴰⵔⴰ',
  'Medea':'ⵎⴻⴷⴻⴰ',
  'Medecin generaliste':'ⵎⴻⴷⴻⵙⵉⵏ ⴳⴻⵏⴻⵔⴰⵍⵉⵙⵜⴻ',
  'Meilleur rapport':'ⵎⴻⵉⵍⵍⴻⵓⵔ ⵔⴰⴱⴱⵓⵔⵜ',
  'Memorisez le signalement':'ⵎⴻⵎⵓⵔⵉⵙⴻⵣ ⵍⴻ ⵙⵉⴳⵏⴰⵍⴻⵎⴻⵏⵜ',
  'Mensuel':'ⵎⴻⵏⵙⵓⴻⵍ',
  'Mensuel — 20€/mois':'ⵎⴻⵏⵙⵓⴻⵍ — 20€/ⵎⵓⵉⵙ',
  'Mensuel — ~3 040 DZD':'ⵎⴻⵏⵙⵓⴻⵍ — ~3 040 ⴷⵣⴷ',
  'Mensuel — ~3 040 DZD (virement)':'ⵎⴻⵏⵙⵓⴻⵍ — ~3 040 ⴷⵣⴷ (ⴼⵉⵔⴻⵎⴻⵏⵜ)',
  'Mes demandes — DZ Diaspora':'ⵎⴻⵙ ⴷⴻⵎⴰⵏⴷⴻⵙ — ⴷⵣ ⴷⵉⴰⵙⴱⵓⵔⴰ',
  'Messaad':'ⵎⴻⵙⵙⴰⴰⴷ',
  'Message *':'ⵎⴻⵙⵙⴰⴳⴻ *',
  'Message/Appel':'ⵎⴻⵙⵙⴰⴳⴻ/ⴰⴱⴱⴻⵍ',
  'Mila':'ⵎⵉⵍⴰ',
  'Ministere de l Habitat':'ⵎⵉⵏⵉⵙⵜⴻⵔⴻ ⴷⴻ ⵍ ⵀⴰⴱⵉⵜⴰⵜ',
  'Ministere de l Interieur — wilayas et communes':'ⵎⵉⵏⵉⵙⵜⴻⵔⴻ ⴷⴻ ⵍ ⵉⵏⵜⴻⵔⵉⴻⵓⵔ — ⵡⵉⵍⴰⵢⴰⵙ ⴻⵜ ⵙⵓⵎⵎⵓⵏⴻⵙ',
  'Mise en avant dans les recherches':'ⵎⵉⵙⴻ ⴻⵏ ⴰⴼⴰⵏⵜ ⴷⴰⵏⵙ ⵍⴻⵙ ⵔⴻⵙⵀⴻⵔⵙⵀⴻⵙ',
  'Mise en avant des annonces':'ⵎⵉⵙⴻ ⴻⵏ ⴰⴼⴰⵏⵜ ⴷⴻⵙ ⴰⵏⵏⵓⵏⵙⴻⵙ',
  'Mode de paiement / طريقة الدفع':'ⵎⵓⴷⴻ ⴷⴻ ⴱⴰⵉⴻⵎⴻⵏⵜ / طريقة الدفع',
  'Moins de 100€':'ⵎⵓⵉⵏⵙ ⴷⴻ 100€',
  'Mon Espace — DZ Diaspora':'ⵎⵓⵏ ⴻⵙⴱⴰⵙⴻ — ⴷⵣ ⴷⵉⴰⵙⴱⵓⵔⴰ',
  'Mon nom':'ⵎⵓⵏ ⵏⵓⵎ',
  'Mon telephone dit que le fichier est dangereux. Que faire ?':'ⵎⵓⵏ ⵜⴻⵍⴻⴱⵀⵓⵏⴻ ⴷⵉⵜ ⵇⵓⴻ ⵍⴻ ⴼⵉⵙⵀⵉⴻⵔ ⴻⵙⵜ ⴷⴰⵏⴳⴻⵔⴻⵓⵅ. ⵇⵓⴻ ⴼⴰⵉⵔⴻ ?',
  'Mosquee Emir Abdelkader — Constantine':'ⵎⵓⵙⵇⵓⴻⴻ ⴻⵎⵉⵔ ⴰⴱⴷⴻⵍⴽⴰⴷⴻⵔ — ⵙⵓⵏⵙⵜⴰⵏⵜⵉⵏⴻ',
  'Mosquee Ketchaoua — Alger':'ⵎⵓⵙⵇⵓⴻⴻ ⴽⴻⵜⵙⵀⴰⵓⵓⴰ — ⴰⵍⴳⴻⵔ',
  'Mosquee historique de la Casbah d Alger, construite a l epoque ottomane.':'ⵎⵓⵙⵇⵓⴻⴻ ⵀⵉⵙⵜⵓⵔⵉⵇⵓⴻ ⴷⴻ ⵍⴰ ⵙⴰⵙⴱⴰⵀ ⴷ ⴰⵍⴳⴻⵔ, ⵙⵓⵏⵙⵜⵔⵓⵉⵜⴻ ⴰ ⵍ ⴻⴱⵓⵇⵓⴻ ⵓⵜⵜⵓⵎⴰⵏⴻ.',
  'Mostaganem':'ⵎⵓⵙⵜⴰⴳⴰⵏⴻⵎ',
  'Mot de passe':'ⵎⵓⵜ ⴷⴻ ⴱⴰⵙⵙⴻ',
  'Mot de passe (6 caracteres minimum)':'ⵎⵓⵜ ⴷⴻ ⴱⴰⵙⵙⴻ (6 ⵙⴰⵔⴰⵙⵜⴻⵔⴻⵙ ⵎⵉⵏⵉⵎⵓⵎ)',
  'Mot de passe oublie ?':'ⵎⵓⵜ ⴷⴻ ⴱⴰⵙⵙⴻ ⵓⵓⴱⵍⵉⴻ ?',
  'Motif du rendez-vous':'ⵎⵓⵜⵉⴼ ⴷⵓ ⵔⴻⵏⴷⴻⵣ-ⴼⵓⵓⵙ',
  'Médecin généraliste':'ⵎⴻⴷⴻⵙⵉⵏ ⴳⴻⵏⴻⵔⴰⵍⵉⵙⵜⴻ',
  'Médecins & Pharmaciens':'ⵎⴻⴷⴻⵙⵉⵏⵙ & ⴱⵀⴰⵔⵎⴰⵙⵉⴻⵏⵙ',
  'Médecins, spécialistes, dentistes':'ⵎⴻⴷⴻⵙⵉⵏⵙ, ⵙⴱⴻⵙⵉⴰⵍⵉⵙⵜⴻⵙ, ⴷⴻⵏⵜⵉⵙⵜⴻⵙ',
  'Médical':'ⵎⴻⴷⵉⵙⴰⵍ',
  'Médéa':'ⵎⴻⴷⴻⴰ',
  'N/A':'ⵏ/ⴰ',
  'NET-HABITA | SIRET : 488 470 584 00043':'ⵏⴻⵜ-ⵀⴰⴱⵉⵜⴰ | ⵙⵉⵔⴻⵜ : 488 470 584 00043',
  'NET-HABITA — Kourrak Habib':'ⵏⴻⵜ-ⵀⴰⴱⵉⵜⴰ — ⴽⵓⵓⵔⵔⴰⴽ ⵀⴰⴱⵉⴱ',
  'Nationalité / Visa':'ⵏⴰⵜⵉⵓⵏⴰⵍⵉⵜⴻ / ⴼⵉⵙⴰ',
  'Natixis Algerie':'ⵏⴰⵜⵉⵅⵉⵙ ⴰⵍⴳⴻⵔⵉⴻ',
  'Naâma':'ⵏⴰⴰⵎⴰ',
  'Ne deplacez pas les blesses graves':'ⵏⴻ ⴷⴻⴱⵍⴰⵙⴻⵣ ⴱⴰⵙ ⵍⴻⵙ ⴱⵍⴻⵙⵙⴻⵙ ⴳⵔⴰⴼⴻⵙ',
  'Ne donnez jamais a boire':'ⵏⴻ ⴷⵓⵏⵏⴻⵣ ⵊⴰⵎⴰⵉⵙ ⴰ ⴱⵓⵉⵔⴻ',
  'Ne resistez pas inutilement':'ⵏⴻ ⵔⴻⵙⵉⵙⵜⴻⵣ ⴱⴰⵙ ⵉⵏⵓⵜⵉⵍⴻⵎⴻⵏⵜ',
  'Ne touchez a rien':'ⵏⴻ ⵜⵓⵓⵙⵀⴻⵣ ⴰ ⵔⵉⴻⵏ',
  'Nom (Arabe)':'ⵏⵓⵎ (ⴰⵔⴰⴱⴻ)',
  'Nom (FR) / الاسم (FR)':'ⵏⵓⵎ (ⴼⵔ) / الاسم (ⴼⵔ)',
  'Nom (Français)':'ⵏⵓⵎ (ⴼⵔⴰⵏⵙⴰⵉⵙ)',
  'Nom *':'ⵏⵓⵎ *',
  'Nom / Entreprise *':'ⵏⵓⵎ / ⴻⵏⵜⵔⴻⴱⵔⵉⵙⴻ *',
  'Nom complet *':'ⵏⵓⵎ ⵙⵓⵎⴱⵍⴻⵜ *',
  'Nom du destinataire *':'ⵏⵓⵎ ⴷⵓ ⴷⴻⵙⵜⵉⵏⴰⵜⴰⵉⵔⴻ *',
  'Nom du site :':'ⵏⵓⵎ ⴷⵓ ⵙⵉⵜⴻ :',
  'Nombre de pièces':'ⵏⵓⵎⴱⵔⴻ ⴷⴻ ⴱⵉⴻⵙⴻⵙ',
  'Nos formats publicitaires':'ⵏⵓⵙ ⴼⵓⵔⵎⴰⵜⵙ ⴱⵓⴱⵍⵉⵙⵉⵜⴰⵉⵔⴻⵙ',
  'Nos offres':'ⵏⵓⵙ ⵓⴼⴼⵔⴻⵙ',
  'Nos tarifs':'ⵏⵓⵙ ⵜⴰⵔⵉⴼⵙ',
  'Notaire complice ou disparu':'ⵏⵓⵜⴰⵉⵔⴻ ⵙⵓⵎⴱⵍⵉⵙⴻ ⵓⵓ ⴷⵉⵙⴱⴰⵔⵓ',
  'Notes internes':'ⵏⵓⵜⴻⵙ ⵉⵏⵜⴻⵔⵏⴻⵙ',
  'Notez les vehicules impliques':'ⵏⵓⵜⴻⵣ ⵍⴻⵙ ⴼⴻⵀⵉⵙⵓⵍⴻⵙ ⵉⵎⴱⵍⵉⵇⵓⴻⵙ',
  'Notification aux utilisateurs':'ⵏⵓⵜⵉⴼⵉⵙⴰⵜⵉⵓⵏ ⴰⵓⵅ ⵓⵜⵉⵍⵉⵙⴰⵜⴻⵓⵔⵙ',
  'Notification push':'ⵏⵓⵜⵉⴼⵉⵙⴰⵜⵉⵓⵏ ⴱⵓⵙⵀ',
  'Notre audience':'ⵏⵓⵜⵔⴻ ⴰⵓⴷⵉⴻⵏⵙⴻ',
  'Notre equipe vous repond sous 24h.':'ⵏⵓⵜⵔⴻ ⴻⵇⵓⵉⴱⴻ ⴼⵓⵓⵙ ⵔⴻⴱⵓⵏⴷ ⵙⵓⵓⵙ 24ⵀ.',
  'Notre équipe vous contacte sous 48h pour valider et vous communiquer le tarif.':'ⵏⵓⵜⵔⴻ ⴻⵇⵓⵉⴱⴻ ⴼⵓⵓⵙ ⵙⵓⵏⵜⴰⵙⵜⴻ ⵙⵓⵓⵙ 48ⵀ ⴱⵓⵓⵔ ⴼⴰⵍⵉⴷⴻⵔ ⴻⵜ ⴼⵓⵓⵙ ⵙⵓⵎⵎⵓⵏⵉⵇⵓⴻⵔ ⵍⴻ ⵜⴰⵔⵉⴼ.',
  'Nous contacter':'ⵏⵓⵓⵙ ⵙⵓⵏⵜⴰⵙⵜⴻⵔ',
  'Numero d ordre (optionnel)':'ⵏⵓⵎⴻⵔⵓ ⴷ ⵓⵔⴷⵔⴻ (ⵓⴱⵜⵉⵓⵏⵏⴻⵍ)',
  'Numeros d urgence nationaux':'ⵏⵓⵎⴻⵔⵓⵙ ⴷ ⵓⵔⴳⴻⵏⵙⴻ ⵏⴰⵜⵉⵓⵏⴰⵓⵅ',
  'Numeros et portails utiles':'ⵏⵓⵎⴻⵔⵓⵙ ⴻⵜ ⴱⵓⵔⵜⴰⵉⵍⵙ ⵓⵜⵉⵍⴻⵙ',
  'Numeros utiles sante':'ⵏⵓⵎⴻⵔⵓⵙ ⵓⵜⵉⵍⴻⵙ ⵙⴰⵏⵜⴻ',
  'Numéro d\'ordre':'ⵏⵓⵎⴻⵔⵓ ⴷ\'ⵓⵔⴷⵔⴻ',
  'N° CNI ou Passeport / رقم الهوية':'ⵏ° ⵙⵏⵉ ⵓⵓ ⴱⴰⵙⵙⴻⴱⵓⵔⵜ / رقم الهوية',
  'N° CNI/Passeport / رقم الهوية':'ⵏ° ⵙⵏⵉ/ⴱⴰⵙⵙⴻⴱⵓⵔⵜ / رقم الهوية',
  'N° Ordre / رقم الانتساب':'ⵏ° ⵓⵔⴷⵔⴻ / رقم الانتساب',
  'N° d\'ordre professionnel / رقم الانتساب':'ⵏ° ⴷ\'ⵓⵔⴷⵔⴻ ⴱⵔⵓⴼⴻⵙⵙⵉⵓⵏⵏⴻⵍ / رقم الانتساب',
  'OPGI — Logement social (LPL)':'ⵓⴱⴳⵉ — ⵍⵓⴳⴻⵎⴻⵏⵜ ⵙⵓⵙⵉⴰⵍ (ⵍⴱⵍ)',
  'Objet':'ⵓⴱⵊⴻⵜ',
  'Objet de la consultation *':'ⵓⴱⵊⴻⵜ ⴷⴻ ⵍⴰ ⵙⵓⵏⵙⵓⵍⵜⴰⵜⵉⵓⵏ *',
  'Objets Trouves':'ⵓⴱⵊⴻⵜⵙ ⵜⵔⵓⵓⴼⴻⵙ',
  'Objets Trouves — DZ Diaspora':'ⵓⴱⵊⴻⵜⵙ ⵜⵔⵓⵓⴼⴻⵙ — ⴷⵣ ⴷⵉⴰⵙⴱⵓⵔⴰ',
  'Objets trouvés illimité':'ⵓⴱⵊⴻⵜⵙ ⵜⵔⵓⵓⴼⴻⵙ ⵉⵍⵍⵉⵎⵉⵜⴻ',
  'Office National du Tourisme (ONT)':'ⵓⴼⴼⵉⵙⴻ ⵏⴰⵜⵉⵓⵏⴰⵍ ⴷⵓ ⵜⵓⵓⵔⵉⵙⵎⴻ (ⵓⵏⵜ)',
  'Ophtalmologue':'ⵓⴱⵀⵜⴰⵍⵎⵓⵍⵓⴳⵓⴻ',
  'Oran':'ⵓⵔⴰⵏ',
  'Organisation judiciaire':'ⵓⵔⴳⴰⵏⵉⵙⴰⵜⵉⵓⵏ ⵊⵓⴷⵉⵙⵉⴰⵉⵔⴻ',
  'Ouargla':'ⵓⵓⴰⵔⴳⵍⴰ',
  'Ouled Djellal':'ⵓⵓⵍⴻⴷ ⴷⵊⴻⵍⵍⴰⵍ',
  'Oum El Bouaghi':'ⵓⵓⵎ ⴻⵍ ⴱⵓⵓⴰⴳⵀⵉ',
  'Ouvert tous les jours — Entree payante':'ⵓⵓⴼⴻⵔⵜ ⵜⵓⵓⵙ ⵍⴻⵙ ⵊⵓⵓⵔⵙ — ⴻⵏⵜⵔⴻⴻ ⴱⴰⵢⴰⵏⵜⴻ',
  'Ouvrir le fichier telecharge':'ⵓⵓⴼⵔⵉⵔ ⵍⴻ ⴼⵉⵙⵀⵉⴻⵔ ⵜⴻⵍⴻⵙⵀⴰⵔⴳⴻ',
  'Page administrateur uniquement':'ⴱⴰⴳⴻ ⴰⴷⵎⵉⵏⵉⵙⵜⵔⴰⵜⴻⵓⵔ ⵓⵏⵉⵇⵓⴻⵎⴻⵏⵜ',
  'Pages cibles (choix multiple)':'ⴱⴰⴳⴻⵙ ⵙⵉⴱⵍⴻⵙ (ⵙⵀⵓⵉⵅ ⵎⵓⵍⵜⵉⴱⵍⴻ)',
  'Paiement EUR ou virement DZD':'ⴱⴰⵉⴻⵎⴻⵏⵜ ⴻⵓⵔ ⵓⵓ ⴼⵉⵔⴻⵎⴻⵏⵜ ⴷⵣⴷ',
  'Paiement en DZD (Algérie)':'ⴱⴰⵉⴻⵎⴻⵏⵜ ⴻⵏ ⴷⵣⴷ (ⴰⵍⴳⴻⵔⵉⴻ)',
  'Paiement par virement bancaire DZD accepté':'ⴱⴰⵉⴻⵎⴻⵏⵜ ⴱⴰⵔ ⴼⵉⵔⴻⵎⴻⵏⵜ ⴱⴰⵏⵙⴰⵉⵔⴻ ⴷⵣⴷ ⴰⵙⵙⴻⴱⵜⴻ',
  'Paiement par virement bancaire DZD — Contactez directement :':'ⴱⴰⵉⴻⵎⴻⵏⵜ ⴱⴰⵔ ⴼⵉⵔⴻⵎⴻⵏⵜ ⴱⴰⵏⵙⴰⵉⵔⴻ ⴷⵣⴷ — ⵙⵓⵏⵜⴰⵙⵜⴻⵣ ⴷⵉⵔⴻⵙⵜⴻⵎⴻⵏⵜ :',
  'Paiement reçu':'ⴱⴰⵉⴻⵎⴻⵏⵜ ⵔⴻⵙⵓ',
  'Paiement securise par Stripe • Annulation en 1 clic • TVA incluse':'ⴱⴰⵉⴻⵎⴻⵏⵜ ⵙⴻⵙⵓⵔⵉⵙⴻ ⴱⴰⵔ ⵙⵜⵔⵉⴱⴻ • ⴰⵏⵏⵓⵍⴰⵜⵉⵓⵏ ⴻⵏ 1 ⵙⵍⵉⵙ • ⵜⴼⴰ ⵉⵏⵙⵍⵓⵙⴻ',
  'Parquet electronique (e-Nyaba)':'ⴱⴰⵔⵇⵓⴻⵜ ⴻⵍⴻⵙⵜⵔⵓⵏⵉⵇⵓⴻ (ⴻ-ⵏⵢⴰⴱⴰ)',
  'Partageable sur les réseaux sociaux':'ⴱⴰⵔⵜⴰⴳⴻⴰⴱⵍⴻ ⵙⵓⵔ ⵍⴻⵙ ⵔⴻⵙⴻⴰⵓⵅ ⵙⵓⵙⵉⴰⵓⵅ',
  'Partagez votre expérience avec ce professionnel pour aider la communauté.':'ⴱⴰⵔⵜⴰⴳⴻⵣ ⴼⵓⵜⵔⴻ ⴻⵅⴱⴻⵔⵉⴻⵏⵙⴻ ⴰⴼⴻⵙ ⵙⴻ ⴱⵔⵓⴼⴻⵙⵙⵉⵓⵏⵏⴻⵍ ⴱⵓⵓⵔ ⴰⵉⴷⴻⵔ ⵍⴰ ⵙⵓⵎⵎⵓⵏⴰⵓⵜⴻ.',
  'Partenariat / Presse':'ⴱⴰⵔⵜⴻⵏⴰⵔⵉⴰⵜ / ⴱⵔⴻⵙⵙⴻ',
  'Particuliers':'ⴱⴰⵔⵜⵉⵙⵓⵍⵉⴻⵔⵙ',
  'Pas encore inscrit ?':'ⴱⴰⵙ ⴻⵏⵙⵓⵔⴻ ⵉⵏⵙⵙⵔⵉⵜ ?',
  'Passer Pro — 60€/mois':'ⴱⴰⵙⵙⴻⵔ ⴱⵔⵓ — 60€/ⵎⵓⵉⵙ',
  'Passez systematiquement par un notaire':'ⴱⴰⵙⵙⴻⵣ ⵙⵢⵙⵜⴻⵎⴰⵜⵉⵇⵓⴻⵎⴻⵏⵜ ⴱⴰⵔ ⵓⵏ ⵏⵓⵜⴰⵉⵔⴻ',
  'Pays':'ⴱⴰⵢⵙ',
  'Pays de résidence':'ⴱⴰⵢⵙ ⴷⴻ ⵔⴻⵙⵉⴷⴻⵏⵙⴻ',
  'Pediatre':'ⴱⴻⴷⵉⴰⵜⵔⴻ',
  'Petites annonces Algerie — Immobilier, vehicules, covoiturage':'ⴱⴻⵜⵉⵜⴻⵙ ⴰⵏⵏⵓⵏⵙⴻⵙ ⴰⵍⴳⴻⵔⵉⴻ — ⵉⵎⵎⵓⴱⵉⵍⵉⴻⵔ, ⴼⴻⵀⵉⵙⵓⵍⴻⵙ, ⵙⵓⴼⵓⵉⵜⵓⵔⴰⴳⴻ',
  'Pharmacien':'ⴱⵀⴰⵔⵎⴰⵙⵉⴻⵏ',
  'Phishing':'ⴱⵀⵉⵙⵀⵉⵏⴳ',
  'Phishing bancaire':'ⴱⵀⵉⵙⵀⵉⵏⴳ ⴱⴰⵏⵙⴰⵉⵔⴻ',
  'Photos HD incluses':'ⴱⵀⵓⵜⵓⵙ ⵀⴷ ⵉⵏⵙⵍⵓⵙⴻⵙ',
  'Photos et liens inclus':'ⴱⵀⵓⵜⵓⵙ ⴻⵜ ⵍⵉⴻⵏⵙ ⵉⵏⵙⵍⵓⵙ',
  'Photos illimitees par annonce':'ⴱⵀⵓⵜⵓⵙ ⵉⵍⵍⵉⵎⵉⵜⴻⴻⵙ ⴱⴰⵔ ⴰⵏⵏⵓⵏⵙⴻ',
  'Photos incluses':'ⴱⵀⵓⵜⵓⵙ ⵉⵏⵙⵍⵓⵙⴻⵙ',
  'Plafond :':'ⴱⵍⴰⴼⵓⵏⴷ :',
  'Plage accessible depuis le centre d Alger, animee en ete.':'ⴱⵍⴰⴳⴻ ⴰⵙⵙⴻⵙⵙⵉⴱⵍⴻ ⴷⴻⴱⵓⵉⵙ ⵍⴻ ⵙⴻⵏⵜⵔⴻ ⴷ ⴰⵍⴳⴻⵔ, ⴰⵏⵉⵎⴻⴻ ⴻⵏ ⴻⵜⴻ.',
  'Plages de sable fin avec vue sur les montagnes kabyles.':'ⴱⵍⴰⴳⴻⵙ ⴷⴻ ⵙⴰⴱⵍⴻ ⴼⵉⵏ ⴰⴼⴻⵙ ⴼⵓⴻ ⵙⵓⵔ ⵍⴻⵙ ⵎⵓⵏⵜⴰⴳⵏⴻⵙ ⴽⴰⴱⵢⵍⴻⵙ.',
  'Plages tranquilles a 30 km d Alger, moins frequentees.':'ⴱⵍⴰⴳⴻⵙ ⵜⵔⴰⵏⵇⵓⵉⵍⵍⴻⵙ ⴰ 30 ⴽⵎ ⴷ ⴰⵍⴳⴻⵔ, ⵎⵓⵉⵏⵙ ⴼⵔⴻⵇⵓⴻⵏⵜⴻⴻⵙ.',
  'Plus de 500€':'ⴱⵍⵓⵙ ⴷⴻ 500€',
  'Plusieurs formats':'ⴱⵍⵓⵙⵉⴻⵓⵔⵙ ⴼⵓⵔⵎⴰⵜⵙ',
  'Police nationale':'ⴱⵓⵍⵉⵙⴻ ⵏⴰⵜⵉⵓⵏⴰⵍⴻ',
  'Police nationale — porter plainte':'ⴱⵓⵍⵉⵙⴻ ⵏⴰⵜⵉⵓⵏⴰⵍⴻ — ⴱⵓⵔⵜⴻⵔ ⴱⵍⴰⵉⵏⵜⴻ',
  'Portail national des actes d etat civil (CNRNE)':'ⴱⵓⵔⵜⴰⵉⵍ ⵏⴰⵜⵉⵓⵏⴰⵍ ⴷⴻⵙ ⴰⵙⵜⴻⵙ ⴷ ⴻⵜⴰⵜ ⵙⵉⴼⵉⵍ (ⵙⵏⵔⵏⴻ)',
  'Portail officiel CNAS (El Hana)':'ⴱⵓⵔⵜⴰⵉⵍ ⵓⴼⴼⵉⵙⵉⴻⵍ ⵙⵏⴰⵙ (ⴻⵍ ⵀⴰⵏⴰ)',
  'Portail officiel du tourisme algerien':'ⴱⵓⵔⵜⴰⵉⵍ ⵓⴼⴼⵉⵙⵉⴻⵍ ⴷⵓ ⵜⵓⵓⵔⵉⵙⵎⴻ ⴰⵍⴳⴻⵔⵉⴻⵏ',
  'Pour DZ Diaspora / لـ DZ Diaspora':'ⴱⵓⵓⵔ ⴷⵣ ⴷⵉⴰⵙⴱⵓⵔⴰ / لـ ⴷⵣ ⴷⵉⴰⵙⴱⵓⵔⴰ',
  'Pour exercer vos droits, contactez-nous a :':'ⴱⵓⵓⵔ ⴻⵅⴻⵔⵙⴻⵔ ⴼⵓⵙ ⴷⵔⵓⵉⵜⵙ, ⵙⵓⵏⵜⴰⵙⵜⴻⵣ-ⵏⵓⵓⵙ ⴰ :',
  'Pour qui est DZ Diaspora ?':'ⴱⵓⵓⵔ ⵇⵓⵉ ⴻⵙⵜ ⴷⵣ ⴷⵉⴰⵙⴱⵓⵔⴰ ?',
  'Pour toute question, reclamation ou demande relative aux presentes CGU :':'ⴱⵓⵓⵔ ⵜⵓⵓⵜⴻ ⵇⵓⴻⵙⵜⵉⵓⵏ, ⵔⴻⵙⵍⴰⵎⴰⵜⵉⵓⵏ ⵓⵓ ⴷⴻⵎⴰⵏⴷⴻ ⵔⴻⵍⴰⵜⵉⴼⴻ ⴰⵓⵅ ⴱⵔⴻⵙⴻⵏⵜⴻⵙ ⵙⴳⵓ :',
  'Pourquoi choisir DZ Diaspora ?':'ⴱⵓⵓⵔⵇⵓⵓⵉ ⵙⵀⵓⵉⵙⵉⵔ ⴷⵣ ⴷⵉⴰⵙⴱⵓⵔⴰ ?',
  'Pourquoi communiquer sur DZ Diaspora ?':'ⴱⵓⵓⵔⵇⵓⵓⵉ ⵙⵓⵎⵎⵓⵏⵉⵇⵓⴻⵔ ⵙⵓⵔ ⴷⵣ ⴷⵉⴰⵙⴱⵓⵔⴰ ?',
  'Pourquoi l application n est pas sur le Play Store ?':'ⴱⵓⵓⵔⵇⵓⵓⵉ ⵍ ⴰⴱⴱⵍⵉⵙⴰⵜⵉⵓⵏ ⵏ ⴻⵙⵜ ⴱⴰⵙ ⵙⵓⵔ ⵍⴻ ⴱⵍⴰⵢ ⵙⵜⵓⵔⴻ ?',
  'Pourquoi s inscrire ?':'ⴱⵓⵓⵔⵇⵓⵓⵉ ⵙ ⵉⵏⵙⵙⵔⵉⵔⴻ ?',
  'Pre-plainte en ligne (Gendarmerie)':'ⴱⵔⴻ-ⴱⵍⴰⵉⵏⵜⴻ ⴻⵏ ⵍⵉⴳⵏⴻ (ⴳⴻⵏⴷⴰⵔⵎⴻⵔⵉⴻ)',
  'Premier Portail Numérique de la Diaspora Algérienne':'ⴱⵔⴻⵎⵉⴻⵔ ⴱⵓⵔⵜⴰⵉⵍ ⵏⵓⵎⴻⵔⵉⵇⵓⴻ ⴷⴻ ⵍⴰ ⴷⵉⴰⵙⴱⵓⵔⴰ ⴰⵍⴳⴻⵔⵉⴻⵏⵏⴻ',
  'Premier contact / Renseignement':'ⴱⵔⴻⵎⵉⴻⵔ ⵙⵓⵏⵜⴰⵙⵜ / ⵔⴻⵏⵙⴻⵉⴳⵏⴻⵎⴻⵏⵜ',
  'Premiere immatriculation :':'ⴱⵔⴻⵎⵉⴻⵔⴻ ⵉⵎⵎⴰⵜⵔⵉⵙⵓⵍⴰⵜⵉⵓⵏ :',
  'Prendre un rendez-vous — DZ Diaspora':'ⴱⵔⴻⵏⴷⵔⴻ ⵓⵏ ⵔⴻⵏⴷⴻⵣ-ⴼⵓⵓⵙ — ⴷⵣ ⴷⵉⴰⵙⴱⵓⵔⴰ',
  'Prenom *':'ⴱⵔⴻⵏⵓⵎ *',
  'Presentation / Services':'ⴱⵔⴻⵙⴻⵏⵜⴰⵜⵉⵓⵏ / ⵙⴻⵔⴼⵉⵙⴻⵙ',
  'Pret a publier votre bien ?':'ⴱⵔⴻⵜ ⴰ ⴱⵓⴱⵍⵉⴻⵔ ⴼⵓⵜⵔⴻ ⴱⵉⴻⵏ ?',
  'Prise en charge directe des ordonnances ≤ 3000 DA':'ⴱⵔⵉⵙⴻ ⴻⵏ ⵙⵀⴰⵔⴳⴻ ⴷⵉⵔⴻⵙⵜⴻ ⴷⴻⵙ ⵓⵔⴷⵓⵏⵏⴰⵏⵙⴻⵙ ≤ 3000 ⴷⴰ',
  'Pro Illimite':'ⴱⵔⵓ ⵉⵍⵍⵉⵎⵉⵜⴻ',
  'Pro Metier':'ⴱⵔⵓ ⵎⴻⵜⵉⴻⵔ',
  'Probleme d installation ?':'ⴱⵔⵓⴱⵍⴻⵎⴻ ⴷ ⵉⵏⵙⵜⴰⵍⵍⴰⵜⵉⵓⵏ ?',
  'Procuration falsifiee':'ⴱⵔⵓⵙⵓⵔⴰⵜⵉⵓⵏ ⴼⴰⵍⵙⵉⴼⵉⴻⴻ',
  'Profession *':'ⴱⵔⵓⴼⴻⵙⵙⵉⵓⵏ *',
  'Profession / المهنة':'ⴱⵔⵓⴼⴻⵙⵙⵉⵓⵏ / المهنة',
  'Professionnel':'ⴱⵔⵓⴼⴻⵙⵙⵉⵓⵏⵏⴻⵍ',
  'Protection civile (pompiers)':'ⴱⵔⵓⵜⴻⵙⵜⵉⵓⵏ ⵙⵉⴼⵉⵍⴻ (ⴱⵓⵎⴱⵉⴻⵔⵙ)',
  'Proteger':'ⴱⵔⵓⵜⴻⴳⴻⵔ',
  'Prénom (Arabe)':'ⴱⵔⴻⵏⵓⵎ (ⴰⵔⴰⴱⴻ)',
  'Prénom (FR) / اللقب (FR)':'ⴱⵔⴻⵏⵓⵎ (ⴼⵔ) / اللقب (ⴼⵔ)',
  'Prénom (Français)':'ⴱⵔⴻⵏⵓⵎ (ⴼⵔⴰⵏⵙⴰⵉⵙ)',
  'Prénom *':'ⴱⵔⴻⵏⵓⵎ *',
  'Présentation':'ⴱⵔⴻⵙⴻⵏⵜⴰⵜⵉⵓⵏ',
  'Présentiel':'ⴱⵔⴻⵙⴻⵏⵜⵉⴻⵍ',
  'Prêt à rejoindre DZ Diaspora ?':'ⴱⵔⴻⵜ ⴰ ⵔⴻⵊⵓⵉⵏⴷⵔⴻ ⴷⵣ ⴷⵉⴰⵙⴱⵓⵔⴰ ?',
  'Psychiatre / Psychologue':'ⴱⵙⵢⵙⵀⵉⴰⵜⵔⴻ / ⴱⵙⵢⵙⵀⵓⵍⵓⴳⵓⴻ',
  'Publier':'ⴱⵓⴱⵍⵉⴻⵔ',
  'Publier maintenant':'ⴱⵓⴱⵍⵉⴻⵔ ⵎⴰⵉⵏⵜⴻⵏⴰⵏⵜ',
  'Publier une annonce':'ⴱⵓⴱⵍⵉⴻⵔ ⵓⵏⴻ ⴰⵏⵏⵓⵏⵙⴻ',
  'Publier une annonce immobiliere — DZ Diaspora':'ⴱⵓⴱⵍⵉⴻⵔ ⵓⵏⴻ ⴰⵏⵏⵓⵏⵙⴻ ⵉⵎⵎⵓⴱⵉⵍⵉⴻⵔⴻ — ⴷⵣ ⴷⵉⴰⵙⴱⵓⵔⴰ',
  'Puis-je annuler l abonnement Pro a tout moment ?':'ⴱⵓⵉⵙ-ⵊⴻ ⴰⵏⵏⵓⵍⴻⵔ ⵍ ⴰⴱⵓⵏⵏⴻⵎⴻⵏⵜ ⴱⵔⵓ ⴰ ⵜⵓⵓⵜ ⵎⵓⵎⴻⵏⵜ ?',
  'Pédiatre':'ⴱⴻⴷⵉⴰⵜⵔⴻ',
  'Quels types de biens puis-je publier ?':'ⵇⵓⴻⵍⵙ ⵜⵢⴱⴻⵙ ⴷⴻ ⴱⵉⴻⵏⵙ ⴱⵓⵉⵙ-ⵊⴻ ⴱⵓⴱⵍⵉⴻⵔ ?',
  'Question generale':'ⵇⵓⴻⵙⵜⵉⵓⵏ ⴳⴻⵏⴻⵔⴰⵍⴻ',
  'Questions frequentes':'ⵇⵓⴻⵙⵜⵉⵓⵏⵙ ⴼⵔⴻⵇⵓⴻⵏⵜⴻⵙ',
  'Questions fréquentes':'ⵇⵓⴻⵙⵜⵉⵓⵏⵙ ⴼⵔⴻⵇⵓⴻⵏⵜⴻⵙ',
  'Re-immatriculation :':'ⵔⴻ-ⵉⵎⵎⴰⵜⵔⵉⵙⵓⵍⴰⵜⵉⵓⵏ :',
  'Rejoignez notre annuaire et soyez visible par la diaspora algerienne.':'ⵔⴻⵊⵓⵉⴳⵏⴻⵣ ⵏⵓⵜⵔⴻ ⴰⵏⵏⵓⴰⵉⵔⴻ ⴻⵜ ⵙⵓⵢⴻⵣ ⴼⵉⵙⵉⴱⵍⴻ ⴱⴰⵔ ⵍⴰ ⴷⵉⴰⵙⴱⵓⵔⴰ ⴰⵍⴳⴻⵔⵉⴻⵏⵏⴻ.',
  'Relizane':'ⵔⴻⵍⵉⵣⴰⵏⴻ',
  'Remboursement a':'ⵔⴻⵎⴱⵓⵓⵔⵙⴻⵎⴻⵏⵜ ⴰ',
  'Remboursement standard :':'ⵔⴻⵎⴱⵓⵓⵔⵙⴻⵎⴻⵏⵜ ⵙⵜⴰⵏⴷⴰⵔⴷ :',
  'Rendre ma demande visible aux professionnels (recommandé)':'ⵔⴻⵏⴷⵔⴻ ⵎⴰ ⴷⴻⵎⴰⵏⴷⴻ ⴼⵉⵙⵉⴱⵍⴻ ⴰⵓⵅ ⴱⵔⵓⴼⴻⵙⵙⵉⵓⵏⵏⴻⵍⵙ (ⵔⴻⵙⵓⵎⵎⴰⵏⴷⴻ)',
  'Renouvellement :':'ⵔⴻⵏⵓⵓⴼⴻⵍⵍⴻⵎⴻⵏⵜ :',
  'Reste en ligne indéfiniment':'ⵔⴻⵙⵜⴻ ⴻⵏ ⵍⵉⴳⵏⴻ ⵉⵏⴷⴻⴼⵉⵏⵉⵎⴻⵏⵜ',
  'Retour definitif :':'ⵔⴻⵜⵓⵓⵔ ⴷⴻⴼⵉⵏⵉⵜⵉⴼ :',
  'Romance scam':'ⵔⵓⵎⴰⵏⵙⴻ ⵙⵙⴰⵎ',
  'Rotation':'ⵔⵓⵜⴰⵜⵉⵓⵏ',
  'Récapitulatif de votre commande':'ⵔⴻⵙⴰⴱⵉⵜⵓⵍⴰⵜⵉⴼ ⴷⴻ ⴼⵓⵜⵔⴻ ⵙⵓⵎⵎⴰⵏⴷⴻ',
  'Référence paiement / مرجع الدفع':'ⵔⴻⴼⴻⵔⴻⵏⵙⴻ ⴱⴰⵉⴻⵎⴻⵏⵜ / مرجع الدفع',
  'S inscrire':'ⵙ ⵉⵏⵙⵙⵔⵉⵔⴻ',
  'S inscrire maintenant':'ⵙ ⵉⵏⵙⵙⵔⵉⵔⴻ ⵎⴰⵉⵏⵜⴻⵏⴰⵏⵜ',
  'S\'inscrire comme professionnel':'ⵙ\'ⵉⵏⵙⵙⵔⵉⵔⴻ ⵙⵓⵎⵎⴻ ⴱⵔⵓⴼⴻⵙⵙⵉⵓⵏⵏⴻⵍ',
  'SAMU (urgences medicales)':'ⵙⴰⵎⵓ (ⵓⵔⴳⴻⵏⵙⴻⵙ ⵎⴻⴷⵉⵙⴰⵍⴻⵙ)',
  'SAMU — urgences medicales':'ⵙⴰⵎⵓ — ⵓⵔⴳⴻⵏⵙⴻⵙ ⵎⴻⴷⵉⵙⴰⵍⴻⵙ',
  'SMS':'ⵙⵎⵙ',
  'Sans engagement · Annulation à tout moment · Paiement sécurisé Stripe':'ⵙⴰⵏⵙ ⴻⵏⴳⴰⴳⴻⵎⴻⵏⵜ · ⴰⵏⵏⵓⵍⴰⵜⵉⵓⵏ ⴰ ⵜⵓⵓⵜ ⵎⵓⵎⴻⵏⵜ · ⴱⴰⵉⴻⵎⴻⵏⵜ ⵙⴻⵙⵓⵔⵉⵙⴻ ⵙⵜⵔⵉⴱⴻ',
  'Sans engagement — Annulation à tout moment':'ⵙⴰⵏⵙ ⴻⵏⴳⴰⴳⴻⵎⴻⵏⵜ — ⴰⵏⵏⵓⵍⴰⵜⵉⵓⵏ ⴰ ⵜⵓⵓⵜ ⵎⵓⵎⴻⵏⵜ',
  'Sante':'ⵙⴰⵏⵜⴻ',
  'Sante Algerie — CNAS, pharmacies et numeros utiles':'ⵙⴰⵏⵜⴻ ⴰⵍⴳⴻⵔⵉⴻ — ⵙⵏⴰⵙ, ⴱⵀⴰⵔⵎⴰⵙⵉⴻⵙ ⴻⵜ ⵏⵓⵎⴻⵔⵓⵙ ⵓⵜⵉⵍⴻⵙ',
  'Saïda':'ⵙⴰⵉⴷⴰ',
  'Se connecter':'ⵙⴻ ⵙⵓⵏⵏⴻⵙⵜⴻⵔ',
  'Securite':'ⵙⴻⵙⵓⵔⵉⵜⴻ',
  'Securite :':'ⵙⴻⵙⵓⵔⵉⵜⴻ :',
  'Securite Algerie — Urgences, ambassades et conseils':'ⵙⴻⵙⵓⵔⵉⵜⴻ ⴰⵍⴳⴻⵔⵉⴻ — ⵓⵔⴳⴻⵏⵙⴻⵙ, ⴰⵎⴱⴰⵙⵙⴰⴷⴻⵙ ⴻⵜ ⵙⵓⵏⵙⴻⵉⵍⵙ',
  'Securite sociale : CNAS et CASNOS':'ⵙⴻⵙⵓⵔⵉⵜⴻ ⵙⵓⵙⵉⴰⵍⴻ : ⵙⵏⴰⵙ ⴻⵜ ⵙⴰⵙⵏⵓⵙ',
  'Selectionnez une specialite :':'ⵙⴻⵍⴻⵙⵜⵉⵓⵏⵏⴻⵣ ⵓⵏⴻ ⵙⴱⴻⵙⵉⴰⵍⵉⵜⴻ :',
  'Selectionnez une wilaya pour voir les pharmacies de garde.':'ⵙⴻⵍⴻⵙⵜⵉⵓⵏⵏⴻⵣ ⵓⵏⴻ ⵡⵉⵍⴰⵢⴰ ⴱⵓⵓⵔ ⴼⵓⵉⵔ ⵍⴻⵙ ⴱⵀⴰⵔⵎⴰⵙⵉⴻⵙ ⴷⴻ ⴳⴰⵔⴷⴻ.',
  'Selectionnez votre wilaya :':'ⵙⴻⵍⴻⵙⵜⵉⵓⵏⵏⴻⵣ ⴼⵓⵜⵔⴻ ⵡⵉⵍⴰⵢⴰ :',
  'Setif':'ⵙⴻⵜⵉⴼ',
  'Si quelqu un a depose une fiche pour votre objet, entrez le':'ⵙⵉ ⵇⵓⴻⵍⵇⵓ ⵓⵏ ⴰ ⴷⴻⴱⵓⵙⴻ ⵓⵏⴻ ⴼⵉⵙⵀⴻ ⴱⵓⵓⵔ ⴼⵓⵜⵔⴻ ⵓⴱⵊⴻⵜ, ⴻⵏⵜⵔⴻⵣ ⵍⴻ',
  'Sidi Bel Abbes':'ⵙⵉⴷⵉ ⴱⴻⵍ ⴰⴱⴱⴻⵙ',
  'Sidi Bel Abbès':'ⵙⵉⴷⵉ ⴱⴻⵍ ⴰⴱⴱⴻⵙ',
  'Signalement d un probleme':'ⵙⵉⴳⵏⴰⵍⴻⵎⴻⵏⵜ ⴷ ⵓⵏ ⴱⵔⵓⴱⵍⴻⵎⴻ',
  'Signalez une arnaque sur DZ Diaspora':'ⵙⵉⴳⵏⴰⵍⴻⵣ ⵓⵏⴻ ⴰⵔⵏⴰⵇⵓⴻ ⵙⵓⵔ ⴷⵣ ⴷⵉⴰⵙⴱⵓⵔⴰ',
  'Signature du Professionnel / توقيع المهني':'ⵙⵉⴳⵏⴰⵜⵓⵔⴻ ⴷⵓ ⴱⵔⵓⴼⴻⵙⵙⵉⵓⵏⵏⴻⵍ / توقيع المهني',
  'Site + App':'ⵙⵉⵜⴻ + ⴰⴱⴱ',
  'Site + App Android':'ⵙⵉⵜⴻ + ⴰⴱⴱ ⴰⵏⴷⵔⵓⵉⴷ',
  'Site web + App Android':'ⵙⵉⵜⴻ ⵡⴻⴱ + ⴰⴱⴱ ⴰⵏⴷⵔⵓⵉⴷ',
  'Site web + application Android':'ⵙⵉⵜⴻ ⵡⴻⴱ + ⴰⴱⴱⵍⵉⵙⴰⵜⵉⵓⵏ ⴰⵏⴷⵔⵓⵉⴷ',
  'Site web uniquement':'ⵙⵉⵜⴻ ⵡⴻⴱ ⵓⵏⵉⵇⵓⴻⵎⴻⵏⵜ',
  'Skikda':'ⵙⴽⵉⴽⴷⴰ',
  'Societe Generale Algerie':'ⵙⵓⵙⵉⴻⵜⴻ ⴳⴻⵏⴻⵔⴰⵍⴻ ⴰⵍⴳⴻⵔⵉⴻ',
  'Sont strictement interdits :':'ⵙⵓⵏⵜ ⵙⵜⵔⵉⵙⵜⴻⵎⴻⵏⵜ ⵉⵏⵜⴻⵔⴷⵉⵜⵙ :',
  'Souk Ahras':'ⵙⵓⵓⴽ ⴰⵀⵔⴰⵙ',
  'Source':'ⵙⵓⵓⵔⵙⴻ',
  'Specialisee dans le financement immobilier et l habitat.':'ⵙⴱⴻⵙⵉⴰⵍⵉⵙⴻⴻ ⴷⴰⵏⵙ ⵍⴻ ⴼⵉⵏⴰⵏⵙⴻⵎⴻⵏⵜ ⵉⵎⵎⵓⴱⵉⵍⵉⴻⵔ ⴻⵜ ⵍ ⵀⴰⴱⵉⵜⴰⵜ.',
  'Specialisee dans les operations avec l etranger et le commerce international.':'ⵙⴱⴻⵙⵉⴰⵍⵉⵙⴻⴻ ⴷⴰⵏⵙ ⵍⴻⵙ ⵓⴱⴻⵔⴰⵜⵉⵓⵏⵙ ⴰⴼⴻⵙ ⵍ ⴻⵜⵔⴰⵏⴳⴻⵔ ⴻⵜ ⵍⴻ ⵙⵓⵎⵎⴻⵔⵙⴻ ⵉⵏⵜⴻⵔⵏⴰⵜⵉⵓⵏⴰⵍ.',
  'Specialite':'ⵙⴱⴻⵙⵉⴰⵍⵉⵜⴻ',
  'Spécialité':'ⵙⴱⴻⵙⵉⴰⵍⵉⵜⴻ',
  'Spécialité / التخصص':'ⵙⴱⴻⵙⵉⴰⵍⵉⵜⴻ / التخصص',
  'Spécialité recherchée *':'ⵙⴱⴻⵙⵉⴰⵍⵉⵜⴻ ⵔⴻⵙⵀⴻⵔⵙⵀⴻⴻ *',
  'Starter':'ⵙⵜⴰⵔⵜⴻⵔ',
  'Station balneaire kabyle avec eaux claires et ambiance familiale.':'ⵙⵜⴰⵜⵉⵓⵏ ⴱⴰⵍⵏⴻⴰⵉⵔⴻ ⴽⴰⴱⵢⵍⴻ ⴰⴼⴻⵙ ⴻⴰⵓⵅ ⵙⵍⴰⵉⵔⴻⵙ ⴻⵜ ⴰⵎⴱⵉⴰⵏⵙⴻ ⴼⴰⵎⵉⵍⵉⴰⵍⴻ.',
  'Statistiques completes':'ⵙⵜⴰⵜⵉⵙⵜⵉⵇⵓⴻⵙ ⵙⵓⵎⴱⵍⴻⵜⴻⵙ',
  'Statistiques de base':'ⵙⵜⴰⵜⵉⵙⵜⵉⵇⵓⴻⵙ ⴷⴻ ⴱⴰⵙⴻ',
  'Statistiques de vues':'ⵙⵜⴰⵜⵉⵙⵜⵉⵇⵓⴻⵙ ⴷⴻ ⴼⵓⴻⵙ',
  'Studio':'ⵙⵜⵓⴷⵉⵓ',
  'Succession / Héritage':'ⵙⵓⵙⵙⴻⵙⵙⵉⵓⵏ / ⵀⴻⵔⵉⵜⴰⴳⴻ',
  'Suivez les instructions':'ⵙⵓⵉⴼⴻⵣ ⵍⴻⵙ ⵉⵏⵙⵜⵔⵓⵙⵜⵉⵓⵏⵙ',
  'Suivi de dossier':'ⵙⵓⵉⴼⵉ ⴷⴻ ⴷⵓⵙⵙⵉⴻⵔ',
  'Sujet *':'ⵙⵓⵊⴻⵜ *',
  'Support de diffusion':'ⵙⵓⴱⴱⵓⵔⵜ ⴷⴻ ⴷⵉⴼⴼⵓⵙⵉⵓⵏ',
  'Support prioritaire':'ⵙⵓⴱⴱⵓⵔⵜ ⴱⵔⵉⵓⵔⵉⵜⴰⵉⵔⴻ',
  'Support prioritaire sous 24h':'ⵙⵓⴱⴱⵓⵔⵜ ⴱⵔⵉⵓⵔⵉⵜⴰⵉⵔⴻ ⵙⵓⵓⵙ 24ⵀ',
  'Surface souhaitée':'ⵙⵓⵔⴼⴰⵙⴻ ⵙⵓⵓⵀⴰⵉⵜⴻⴻ',
  'Sécurisé & Vérifié':'ⵙⴻⵙⵓⵔⵉⵙⴻ & ⴼⴻⵔⵉⴼⵉⴻ',
  'Sétif':'ⵙⴻⵜⵉⴼ',
  'TSA, El Khabar, Ennahar — les dernières news algériennes en français et arabe.':'ⵜⵙⴰ, ⴻⵍ ⴽⵀⴰⴱⴰⵔ, ⴻⵏⵏⴰⵀⴰⵔ — ⵍⴻⵙ ⴷⴻⵔⵏⵉⴻⵔⴻⵙ ⵏⴻⵡⵙ ⴰⵍⴳⴻⵔⵉⴻⵏⵏⴻⵙ ⴻⵏ ⴼⵔⴰⵏⵙⴰⵉⵙ ⴻⵜ ⴰⵔⴰⴱⴻ.',
  'Tamanrasset':'ⵜⴰⵎⴰⵏⵔⴰⵙⵙⴻⵜ',
  'Tarif premium':'ⵜⴰⵔⵉⴼ ⴱⵔⴻⵎⵉⵓⵎ',
  'Tarif standard':'ⵜⴰⵔⵉⴼ ⵙⵜⴰⵏⴷⴰⵔⴷ',
  'Tarif sur devis':'ⵜⴰⵔⵉⴼ ⵙⵓⵔ ⴷⴻⴼⵉⵙ',
  'Tarifs':'ⵜⴰⵔⵉⴼⵙ',
  'Tassili n Ajjer — UNESCO':'ⵜⴰⵙⵙⵉⵍⵉ ⵏ ⴰⵊⵊⴻⵔ — ⵓⵏⴻⵙⵙⵓ',
  'Taux de remboursement':'ⵜⴰⵓⵅ ⴷⴻ ⵔⴻⵎⴱⵓⵓⵔⵙⴻⵎⴻⵏⵜ',
  'Taxis aeroport':'ⵜⴰⵅⵉⵙ ⴰⴻⵔⵓⴱⵓⵔⵜ',
  'Taxis non agrees':'ⵜⴰⵅⵉⵙ ⵏⵓⵏ ⴰⴳⵔⴻⴻⵙ',
  'Tel : +213 21 98 17 17':'ⵜⴻⵍ : +213 21 98 17 17',
  'Telechargements':'ⵜⴻⵍⴻⵙⵀⴰⵔⴳⴻⵎⴻⵏⵜⵙ',
  'Telecharger le fichier APK':'ⵜⴻⵍⴻⵙⵀⴰⵔⴳⴻⵔ ⵍⴻ ⴼⵉⵙⵀⵉⴻⵔ ⴰⴱⴽ',
  'Telephone (optionnel)':'ⵜⴻⵍⴻⴱⵀⵓⵏⴻ (ⵓⴱⵜⵉⵓⵏⵏⴻⵍ)',
  'Telephone *':'ⵜⴻⵍⴻⴱⵀⵓⵏⴻ *',
  'Temtem':'ⵜⴻⵎⵜⴻⵎ',
  'Terrain':'ⵜⴻⵔⵔⴰⵉⵏ',
  'Terrain non constructible':'ⵜⴻⵔⵔⴰⵉⵏ ⵏⵓⵏ ⵙⵓⵏⵙⵜⵔⵓⵙⵜⵉⴱⵍⴻ',
  'Texte + photo':'ⵜⴻⵅⵜⴻ + ⴱⵀⵓⵜⵓ',
  'Tiaret':'ⵜⵉⴰⵔⴻⵜ',
  'Tigzirt — Tizi Ouzou':'ⵜⵉⴳⵣⵉⵔⵜ — ⵜⵉⵣⵉ ⵓⵓⵣⵓⵓ',
  'Timgad — Cite romaine UNESCO':'ⵜⵉⵎⴳⴰⴷ — ⵙⵉⵜⴻ ⵔⵓⵎⴰⵉⵏⴻ ⵓⵏⴻⵙⵙⵓ',
  'Timimoun':'ⵜⵉⵎⵉⵎⵓⵓⵏ',
  'Tindouf':'ⵜⵉⵏⴷⵓⵓⴼ',
  'Tipaza':'ⵜⵉⴱⴰⵣⴰ',
  'Tissemsilt':'ⵜⵉⵙⵙⴻⵎⵙⵉⵍⵜ',
  'Titre *':'ⵜⵉⵜⵔⴻ *',
  'Tizi Ouzou':'ⵜⵉⵣⵉ ⵓⵓⵣⵓⵓ',
  'Tlemcen':'ⵜⵍⴻⵎⵙⴻⵏ',
  'Totalement gratuit :':'ⵜⵓⵜⴰⵍⴻⵎⴻⵏⵜ ⴳⵔⴰⵜⵓⵉⵜ :',
  'Touggourt':'ⵜⵓⵓⴳⴳⵓⵓⵔⵜ',
  'Toujours affiché':'ⵜⵓⵓⵊⵓⵓⵔⵙ ⴰⴼⴼⵉⵙⵀⴻ',
  'Tourisme':'ⵜⵓⵓⵔⵉⵙⵎⴻ',
  'Tourisme Algerie — Sites a visiter, hotels et conseils':'ⵜⵓⵓⵔⵉⵙⵎⴻ ⴰⵍⴳⴻⵔⵉⴻ — ⵙⵉⵜⴻⵙ ⴰ ⴼⵉⵙⵉⵜⴻⵔ, ⵀⵓⵜⴻⵍⵙ ⴻⵜ ⵙⵓⵏⵙⴻⵉⵍⵙ',
  'Tous':'ⵜⵓⵓⵙ',
  'Toutes':'ⵜⵓⵓⵜⴻⵙ',
  'Traduction certifiee :':'ⵜⵔⴰⴷⵓⵙⵜⵉⵓⵏ ⵙⴻⵔⵜⵉⴼⵉⴻⴻ :',
  'Transaction *':'ⵜⵔⴰⵏⵙⴰⵙⵜⵉⵓⵏ *',
  'Transavia':'ⵜⵔⴰⵏⵙⴰⴼⵉⴰ',
  'Transferts non autorises':'ⵜⵔⴰⵏⵙⴼⴻⵔⵜⵙ ⵏⵓⵏ ⴰⵓⵜⵓⵔⵉⵙⴻⵙ',
  'Transport':'ⵜⵔⴰⵏⵙⴱⵓⵔⵜ',
  'Transport Algerie — Vols, ferries, taxi et fret diaspora':'ⵜⵔⴰⵏⵙⴱⵓⵔⵜ ⴰⵍⴳⴻⵔⵉⴻ — ⴼⵓⵍⵙ, ⴼⴻⵔⵔⵉⴻⵙ, ⵜⴰⵅⵉ ⴻⵜ ⴼⵔⴻⵜ ⴷⵉⴰⵙⴱⵓⵔⴰ',
  'Transporteurs specialises diaspora':'ⵜⵔⴰⵏⵙⴱⵓⵔⵜⴻⵓⵔⵙ ⵙⴱⴻⵙⵉⴰⵍⵉⵙⴻⵙ ⴷⵉⴰⵙⴱⵓⵔⴰ',
  'Traversees avec possibilite de transport de vehicule.':'ⵜⵔⴰⴼⴻⵔⵙⴻⴻⵙ ⴰⴼⴻⵙ ⴱⵓⵙⵙⵉⴱⵉⵍⵉⵜⴻ ⴷⴻ ⵜⵔⴰⵏⵙⴱⵓⵔⵜ ⴷⴻ ⴼⴻⵀⵉⵙⵓⵍⴻ.',
  'Tribunal (1er degre)':'ⵜⵔⵉⴱⵓⵏⴰⵍ (1ⴻⵔ ⴷⴻⴳⵔⴻ)',
  'Tribunal administratif':'ⵜⵔⵉⴱⵓⵏⴰⵍ ⴰⴷⵎⵉⵏⵉⵙⵜⵔⴰⵜⵉⴼ',
  'Très fort taux d\'engagement':'ⵜⵔⴻⵙ ⴼⵓⵔⵜ ⵜⴰⵓⵅ ⴷ\'ⴻⵏⴳⴰⴳⴻⵎⴻⵏⵜ',
  'Turkish Airlines':'ⵜⵓⵔⴽⵉⵙⵀ ⴰⵉⵔⵍⵉⵏⴻⵙ',
  'Type d objet *':'ⵜⵢⴱⴻ ⴷ ⵓⴱⵊⴻⵜ *',
  'Type d objet perdu':'ⵜⵢⴱⴻ ⴷ ⵓⴱⵊⴻⵜ ⴱⴻⵔⴷⵓ',
  'Type d\'alerte':'ⵜⵢⴱⴻ ⴷ\'ⴰⵍⴻⵔⵜⴻ',
  'Type de bien *':'ⵜⵢⴱⴻ ⴷⴻ ⴱⵉⴻⵏ *',
  'Type de consultation *':'ⵜⵢⴱⴻ ⴷⴻ ⵙⵓⵏⵙⵓⵍⵜⴰⵜⵉⵓⵏ *',
  'Type de droit *':'ⵜⵢⴱⴻ ⴷⴻ ⴷⵔⵓⵉⵜ *',
  'Type de rendez-vous':'ⵜⵢⴱⴻ ⴷⴻ ⵔⴻⵏⴷⴻⵣ-ⴼⵓⵓⵙ',
  'Tébessa':'ⵜⴻⴱⴻⵙⵙⴰ',
  'Téléphone':'ⵜⴻⵍⴻⴱⵀⵓⵏⴻ',
  'Téléphone *':'ⵜⴻⵍⴻⴱⵀⵓⵏⴻ *',
  'Téléphone / WhatsApp':'ⵜⴻⵍⴻⴱⵀⵓⵏⴻ / ⵡⵀⴰⵜⵙⴰⴱⴱ',
  'Téléphone / الهاتف':'ⵜⴻⵍⴻⴱⵀⵓⵏⴻ / الهاتف',
  'URL :':'ⵓⵔⵍ :',
  'Un pseudo':'ⵓⵏ ⴱⵙⴻⵓⴷⵓ',
  'Une fenetre d installation apparait avec le nom':'ⵓⵏⴻ ⴼⴻⵏⴻⵜⵔⴻ ⴷ ⵉⵏⵙⵜⴰⵍⵍⴰⵜⵉⵓⵏ ⴰⴱⴱⴰⵔⴰⵉⵜ ⴰⴼⴻⵙ ⵍⴻ ⵏⵓⵎ',
  'Une fois installe, appuyez sur':'ⵓⵏⴻ ⴼⵓⵉⵙ ⵉⵏⵙⵜⴰⵍⵍⴻ, ⴰⴱⴱⵓⵢⴻⵣ ⵙⵓⵔ',
  'Upela (comparateur)':'ⵓⴱⴻⵍⴰ (ⵙⵓⵎⴱⴰⵔⴰⵜⴻⵓⵔ)',
  'Urgence':'ⵓⵔⴳⴻⵏⵙⴻ',
  'Usage unique :':'ⵓⵙⴰⴳⴻ ⵓⵏⵉⵇⵓⴻ :',
  'VTC 100% algerien, Alger et environs (Tipaza, Blida, Boumerdes) et Oran.':'ⴼⵜⵙ 100% ⴰⵍⴳⴻⵔⵉⴻⵏ, ⴰⵍⴳⴻⵔ ⴻⵜ ⴻⵏⴼⵉⵔⵓⵏⵙ (ⵜⵉⴱⴰⵣⴰ, ⴱⵍⵉⴷⴰ, ⴱⵓⵓⵎⴻⵔⴷⴻⵙ) ⴻⵜ ⵓⵔⴰⵏ.',
  'VTC a Alger, Oran et Constantine. Prix fixe annonce avant la course.':'ⴼⵜⵙ ⴰ ⴰⵍⴳⴻⵔ, ⵓⵔⴰⵏ ⴻⵜ ⵙⵓⵏⵙⵜⴰⵏⵜⵉⵏⴻ. ⴱⵔⵉⵅ ⴼⵉⵅⴻ ⴰⵏⵏⵓⵏⵙⴻ ⴰⴼⴰⵏⵜ ⵍⴰ ⵙⵓⵓⵔⵙⴻ.',
  'Valable sans limite de temps':'ⴼⴰⵍⴰⴱⵍⴻ ⵙⴰⵏⵙ ⵍⵉⵎⵉⵜⴻ ⴷⴻ ⵜⴻⵎⴱⵙ',
  'Valider':'ⴼⴰⵍⵉⴷⴻⵔ',
  'Validite :':'ⴼⴰⵍⵉⴷⵉⵜⴻ :',
  'Vehicule eligible :':'ⴼⴻⵀⵉⵙⵓⵍⴻ ⴻⵍⵉⴳⵉⴱⵍⴻ :',
  'Verifiez auprès de la Conservation Fonciere':'ⴼⴻⵔⵉⴼⵉⴻⵣ ⴰⵓⴱⵔⴻⵙ ⴷⴻ ⵍⴰ ⵙⵓⵏⵙⴻⵔⴼⴰⵜⵉⵓⵏ ⴼⵓⵏⵙⵉⴻⵔⴻ',
  'Verifiez les franchises bagages avant de partir pour eviter les surtaxes':'ⴼⴻⵔⵉⴼⵉⴻⵣ ⵍⴻⵙ ⴼⵔⴰⵏⵙⵀⵉⵙⴻⵙ ⴱⴰⴳⴰⴳⴻⵙ ⴰⴼⴰⵏⵜ ⴷⴻ ⴱⴰⵔⵜⵉⵔ ⴱⵓⵓⵔ ⴻⴼⵉⵜⴻⵔ ⵍⴻⵙ ⵙⵓⵔⵜⴰⵅⴻⵙ',
  'Version 1.0.0 — Compatible Android 8.0 et superieur':'ⴼⴻⵔⵙⵉⵓⵏ 1.0.0 — ⵙⵓⵎⴱⴰⵜⵉⴱⵍⴻ ⴰⵏⴷⵔⵓⵉⴷ 8.0 ⴻⵜ ⵙⵓⴱⴻⵔⵉⴻⵓⵔ',
  'Vidéo 15 à 60 secondes':'ⴼⵉⴷⴻⵓ 15 ⴰ 60 ⵙⴻⵙⵓⵏⴷⴻⵙ',
  'Vidéo Sponsorisée':'ⴼⵉⴷⴻⵓ ⵙⴱⵓⵏⵙⵓⵔⵉⵙⴻⴻ',
  'Villa / Maison':'ⴼⵉⵍⵍⴰ / ⵎⴰⵉⵙⵓⵏ',
  'Virement bancaire DZD':'ⴼⵉⵔⴻⵎⴻⵏⵜ ⴱⴰⵏⵙⴰⵉⵔⴻ ⴷⵣⴷ',
  'Visibilite standard':'ⴼⵉⵙⵉⴱⵉⵍⵉⵜⴻ ⵙⵜⴰⵏⴷⴰⵔⴷ',
  'Visibilite sur la page de votre specialite':'ⴼⵉⵙⵉⴱⵉⵍⵉⵜⴻ ⵙⵓⵔ ⵍⴰ ⴱⴰⴳⴻ ⴷⴻ ⴼⵓⵜⵔⴻ ⵙⴱⴻⵙⵉⴰⵍⵉⵜⴻ',
  'Visibilité mondiale':'ⴼⵉⵙⵉⴱⵉⵍⵉⵜⴻ ⵎⵓⵏⴷⵉⴰⵍⴻ',
  'Visible site + app':'ⴼⵉⵙⵉⴱⵍⴻ ⵙⵉⵜⴻ + ⴰⴱⴱ',
  'Visible sur 69 wilayas':'ⴼⵉⵙⵉⴱⵍⴻ ⵙⵓⵔ 69 ⵡⵉⵍⴰⵢⴰⵙ',
  'Visible sur site + app Android':'ⴼⵉⵙⵉⴱⵍⴻ ⵙⵓⵔ ⵙⵉⵜⴻ + ⴰⴱⴱ ⴰⵏⴷⵔⵓⵉⴷ',
  'Visible sur toutes les pages':'ⴼⵉⵙⵉⴱⵍⴻ ⵙⵓⵔ ⵜⵓⵓⵜⴻⵙ ⵍⴻⵙ ⴱⴰⴳⴻⵙ',
  'Visioconférence':'ⴼⵉⵙⵉⵓⵙⵓⵏⴼⴻⵔⴻⵏⵙⴻ',
  'Voir toutes les wilayas →':'ⴼⵓⵉⵔ ⵜⵓⵓⵜⴻⵙ ⵍⴻⵙ ⵡⵉⵍⴰⵢⴰⵙ →',
  'Vols annulés, ferries ENTMV, grèves — la communauté est informée instantanément.':'ⴼⵓⵍⵙ ⴰⵏⵏⵓⵍⴻⵙ, ⴼⴻⵔⵔⵉⴻⵙ ⴻⵏⵜⵎⴼ, ⴳⵔⴻⴼⴻⵙ — ⵍⴰ ⵙⵓⵎⵎⵓⵏⴰⵓⵜⴻ ⴻⵙⵜ ⵉⵏⴼⵓⵔⵎⴻⴻ ⵉⵏⵙⵜⴰⵏⵜⴰⵏⴻⵎⴻⵏⵜ.',
  'Vols depuis Paris, Marseille, Nice vers Alger et autres villes algeriennes.':'ⴼⵓⵍⵙ ⴷⴻⴱⵓⵉⵙ ⴱⴰⵔⵉⵙ, ⵎⴰⵔⵙⴻⵉⵍⵍⴻ, ⵏⵉⵙⴻ ⴼⴻⵔⵙ ⴰⵍⴳⴻⵔ ⴻⵜ ⴰⵓⵜⵔⴻⵙ ⴼⵉⵍⵍⴻⵙ ⴰⵍⴳⴻⵔⵉⴻⵏⵏⴻⵙ.',
  'Vols en temps reel':'ⴼⵓⵍⵙ ⴻⵏ ⵜⴻⵎⴱⵙ ⵔⴻⴻⵍ',
  'Vols entre l Algerie et le reste du monde, horaires mis a jour automatiquement.':'ⴼⵓⵍⵙ ⴻⵏⵜⵔⴻ ⵍ ⴰⵍⴳⴻⵔⵉⴻ ⴻⵜ ⵍⴻ ⵔⴻⵙⵜⴻ ⴷⵓ ⵎⵓⵏⴷⴻ, ⵀⵓⵔⴰⵉⵔⴻⵙ ⵎⵉⵙ ⴰ ⵊⵓⵓⵔ ⴰⵓⵜⵓⵎⴰⵜⵉⵇⵓⴻⵎⴻⵏⵜ.',
  'Vos coordonnees de contact (visibles uniquement si le code est correct) :':'ⴼⵓⵙ ⵙⵓⵓⵔⴷⵓⵏⵏⴻⴻⵙ ⴷⴻ ⵙⵓⵏⵜⴰⵙⵜ (ⴼⵉⵙⵉⴱⵍⴻⵙ ⵓⵏⵉⵇⵓⴻⵎⴻⵏⵜ ⵙⵉ ⵍⴻ ⵙⵓⴷⴻ ⴻⵙⵜ ⵙⵓⵔⵔⴻⵙⵜ) :',
  'Vos coordonnées':'ⴼⵓⵙ ⵙⵓⵓⵔⴷⵓⵏⵏⴻⴻⵙ',
  'Vos demandes publiées et les réponses des professionnels.':'ⴼⵓⵙ ⴷⴻⵎⴰⵏⴷⴻⵙ ⴱⵓⴱⵍⵉⴻⴻⵙ ⴻⵜ ⵍⴻⵙ ⵔⴻⴱⵓⵏⵙⴻⵙ ⴷⴻⵙ ⴱⵔⵓⴼⴻⵙⵙⵉⵓⵏⵏⴻⵍⵙ.',
  'Votre avis *':'ⴼⵓⵜⵔⴻ ⴰⴼⵉⵙ *',
  'Votre avis sera vérifié avant publication.':'ⴼⵓⵜⵔⴻ ⴰⴼⵉⵙ ⵙⴻⵔⴰ ⴼⴻⵔⵉⴼⵉⴻ ⴰⴼⴰⵏⵜ ⴱⵓⴱⵍⵉⵙⴰⵜⵉⵓⵏ.',
  'Votre bannière ici — 728x90px':'ⴼⵓⵜⵔⴻ ⴱⴰⵏⵏⵉⴻⵔⴻ ⵉⵙⵉ — 728ⵅ90ⴱⵅ',
  'Votre cabinet / entreprise':'ⴼⵓⵜⵔⴻ ⵙⴰⴱⵉⵏⴻⵜ / ⴻⵏⵜⵔⴻⴱⵔⵉⵙⴻ',
  'Votre email':'ⴼⵓⵜⵔⴻ ⴻⵎⴰⵉⵍ',
  'Votre fiche apparait aussi sur l application Android DZ Diaspora.':'ⴼⵓⵜⵔⴻ ⴼⵉⵙⵀⴻ ⴰⴱⴱⴰⵔⴰⵉⵜ ⴰⵓⵙⵙⵉ ⵙⵓⵔ ⵍ ⴰⴱⴱⵍⵉⵙⴰⵜⵉⵓⵏ ⴰⵏⴷⵔⵓⵉⴷ ⴷⵣ ⴷⵉⴰⵙⴱⵓⵔⴰ.',
  'Votre message':'ⴼⵓⵜⵔⴻ ⵎⴻⵙⵙⴰⴳⴻ',
  'Votre nom':'ⴼⵓⵜⵔⴻ ⵏⵓⵎ',
  'Votre nom *':'ⴼⵓⵜⵔⴻ ⵏⵓⵎ *',
  'Votre nom ou prenom *':'ⴼⵓⵜⵔⴻ ⵏⵓⵎ ⵓⵓ ⴱⵔⴻⵏⵓⵎ *',
  'Votre note *':'ⴼⵓⵜⵔⴻ ⵏⵓⵜⴻ *',
  'Vous etes professionnel ?':'ⴼⵓⵓⵙ ⴻⵜⴻⵙ ⴱⵔⵓⴼⴻⵙⵙⵉⵓⵏⵏⴻⵍ ?',
  'Vous etes une agence ? Contactez-nous':'ⴼⵓⵓⵙ ⴻⵜⴻⵙ ⵓⵏⴻ ⴰⴳⴻⵏⵙⴻ ? ⵙⵓⵏⵜⴰⵙⵜⴻⵣ-ⵏⵓⵓⵙ',
  'Vueling':'ⴼⵓⴻⵍⵉⵏⴳ',
  'Véhicules, services, emploi':'ⴼⴻⵀⵉⵙⵓⵍⴻⵙ, ⵙⴻⵔⴼⵉⵙⴻⵙ, ⴻⵎⴱⵍⵓⵉ',
  'Vérification identité':'ⴼⴻⵔⵉⴼⵉⵙⴰⵜⵉⵓⵏ ⵉⴷⴻⵏⵜⵉⵜⴻ',
  'Vérification numéro d\'ordre':'ⴼⴻⵔⵉⴼⵉⵙⴰⵜⵉⵓⵏ ⵏⵓⵎⴻⵔⵓ ⴷ\'ⵓⵔⴷⵔⴻ',
  'WhatsApp':'ⵡⵀⴰⵜⵙⴰⴱⴱ',
  'Wilaya':'ⵡⵉⵍⴰⵢⴰ',
  'Wilaya *':'ⵡⵉⵍⴰⵢⴰ *',
  'Wilaya / الولاية':'ⵡⵉⵍⴰⵢⴰ / الولاية',
  'Wilaya concernée':'ⵡⵉⵍⴰⵢⴰ ⵙⵓⵏⵙⴻⵔⵏⴻⴻ',
  'Wilaya de Djanet — Guide obligatoire':'ⵡⵉⵍⴰⵢⴰ ⴷⴻ ⴷⵊⴰⵏⴻⵜ — ⴳⵓⵉⴷⴻ ⵓⴱⵍⵉⴳⴰⵜⵓⵉⵔⴻ',
  'Wilaya de Ghardaia — 600 km au sud d Alger':'ⵡⵉⵍⴰⵢⴰ ⴷⴻ ⴳⵀⴰⵔⴷⴰⵉⴰ — 600 ⴽⵎ ⴰⵓ ⵙⵓⴷ ⴷ ⴰⵍⴳⴻⵔ',
  'Wilayas':'ⵡⵉⵍⴰⵢⴰⵙ',
  'Wilayas couvertes':'ⵡⵉⵍⴰⵢⴰⵙ ⵙⵓⵓⴼⴻⵔⵜⴻⵙ',
  'Wilayas d Algerie — Les 69 wilayas officielles':'ⵡⵉⵍⴰⵢⴰⵙ ⴷ ⴰⵍⴳⴻⵔⵉⴻ — ⵍⴻⵙ 69 ⵡⵉⵍⴰⵢⴰⵙ ⵓⴼⴼⵉⵙⵉⴻⵍⵍⴻⵙ',
  'Yassir':'ⵢⴰⵙⵙⵉⵔ',
  'a l inscription pour : Immobilier, Vehicules, Services, Emploi':'ⴰ ⵍ ⵉⵏⵙⵙⵔⵉⴱⵜⵉⵓⵏ ⴱⵓⵓⵔ : ⵉⵎⵎⵓⴱⵉⵍⵉⴻⵔ, ⴼⴻⵀⵉⵙⵓⵍⴻⵙ, ⵙⴻⵔⴼⵉⵙⴻⵙ, ⴻⵎⴱⵍⵓⵉ',
  'a une victime, meme si elle le demande':'ⴰ ⵓⵏⴻ ⴼⵉⵙⵜⵉⵎⴻ, ⵎⴻⵎⴻ ⵙⵉ ⴻⵍⵍⴻ ⵍⴻ ⴷⴻⵎⴰⵏⴷⴻ',
  'chez le notaire et la verification complete des titres de propriete':'ⵙⵀⴻⵣ ⵍⴻ ⵏⵓⵜⴰⵉⵔⴻ ⴻⵜ ⵍⴰ ⴼⴻⵔⵉⴼⵉⵙⴰⵜⵉⵓⵏ ⵙⵓⵎⴱⵍⴻⵜⴻ ⴷⴻⵙ ⵜⵉⵜⵔⴻⵙ ⴷⴻ ⴱⵔⵓⴱⵔⵉⴻⵜⴻ',
  'cnas.dz':'ⵙⵏⴰⵙ.ⴷⵣ',
  'cnrne.mjustice.dz':'ⵙⵏⵔⵏⴻ.ⵎⵊⵓⵙⵜⵉⵙⴻ.ⴷⵣ',
  'contacter notre commercial':'ⵙⵓⵏⵜⴰⵙⵜⴻⵔ ⵏⵓⵜⵔⴻ ⵙⵓⵎⵎⴻⵔⵙⵉⴰⵍ',
  'de DZ Diaspora *':'ⴷⴻ ⴷⵣ ⴷⵉⴰⵙⴱⵓⵔⴰ *',
  'de l agresseur : taille, corpulence, vetements, signes particuliers':'ⴷⴻ ⵍ ⴰⴳⵔⴻⵙⵙⴻⵓⵔ : ⵜⴰⵉⵍⵍⴻ, ⵙⵓⵔⴱⵓⵍⴻⵏⵙⴻ, ⴼⴻⵜⴻⵎⴻⵏⵜⵙ, ⵙⵉⴳⵏⴻⵙ ⴱⴰⵔⵜⵉⵙⵓⵍⵉⴻⵔⵙ',
  'de l operateur au telephone et ne raccrochez jamais le premier':'ⴷⴻ ⵍ ⵓⴱⴻⵔⴰⵜⴻⵓⵔ ⴰⵓ ⵜⴻⵍⴻⴱⵀⵓⵏⴻ ⴻⵜ ⵏⴻ ⵔⴰⵙⵙⵔⵓⵙⵀⴻⵣ ⵊⴰⵎⴰⵉⵙ ⵍⴻ ⴱⵔⴻⵎⵉⴻⵔ',
  'delivrance gratuite':'ⴷⴻⵍⵉⴼⵔⴰⵏⵙⴻ ⴳⵔⴰⵜⵓⵉⵜⴻ',
  'diaspora algérienne':'ⴷⵉⴰⵙⴱⵓⵔⴰ ⴰⵍⴳⴻⵔⵉⴻⵏⵏⴻ',
  'douane.gov.dz':'ⴷⵓⵓⴰⵏⴻ.ⴳⵓⴼ.ⴷⵣ',
  'du tarif reglementaire (20% restent a votre charge)':'ⴷⵓ ⵜⴰⵔⵉⴼ ⵔⴻⴳⵍⴻⵎⴻⵏⵜⴰⵉⵔⴻ (20% ⵔⴻⵙⵜⴻⵏⵜ ⴰ ⴼⵓⵜⵔⴻ ⵙⵀⴰⵔⴳⴻ)',
  'dzdiaspora.online':'ⴷⵣⴷⵉⴰⵙⴱⵓⵔⴰ.ⵓⵏⵍⵉⵏⴻ',
  'e-Nyaba':'ⴻ-ⵏⵢⴰⴱⴰ',
  'est edite a titre informatif par un editeur independant.':'ⴻⵙⵜ ⴻⴷⵉⵜⴻ ⴰ ⵜⵉⵜⵔⴻ ⵉⵏⴼⵓⵔⵎⴰⵜⵉⴼ ⴱⴰⵔ ⵓⵏ ⴻⴷⵉⵜⴻⵓⵔ ⵉⵏⴷⴻⴱⴻⵏⴷⴰⵏⵜ.',
  'et l icone de l application. Appuyez sur':'ⴻⵜ ⵍ ⵉⵙⵓⵏⴻ ⴷⴻ ⵍ ⴰⴱⴱⵍⵉⵙⴰⵜⵉⵓⵏ. ⴰⴱⴱⵓⵢⴻⵣ ⵙⵓⵔ',
  'et restez disponible pour leur intervention':'ⴻⵜ ⵔⴻⵙⵜⴻⵣ ⴷⵉⵙⴱⵓⵏⵉⴱⵍⴻ ⴱⵓⵓⵔ ⵍⴻⵓⵔ ⵉⵏⵜⴻⵔⴼⴻⵏⵜⵉⵓⵏ',
  'generalement 3 a 8 semaines au consulat':'ⴳⴻⵏⴻⵔⴰⵍⴻⵎⴻⵏⵜ 3 ⴰ 8 ⵙⴻⵎⴰⵉⵏⴻⵙ ⴰⵓ ⵙⵓⵏⵙⵓⵍⴰⵜ',
  'interieur.gov.dz':'ⵉⵏⵜⴻⵔⵉⴻⵓⵔ.ⴳⵓⴼ.ⴷⵣ',
  'kourrak.habib@hotmail.com':'ⴽⵓⵓⵔⵔⴰⴽ.ⵀⴰⴱⵉⴱ@ⵀⵓⵜⵎⴰⵉⵍ.ⵙⵓⵎ',
  'kourrak.habib@hotmail.com | +213 (0) 799 87 28 90':'ⴽⵓⵓⵔⵔⴰⴽ.ⵀⴰⴱⵉⴱ@ⵀⵓⵜⵎⴰⵉⵍ.ⵙⵓⵎ | +213 (0) 799 87 28 90',
  'la franchise CCR n est accordee qu une seule fois par foyer, pas par personne':'ⵍⴰ ⴼⵔⴰⵏⵙⵀⵉⵙⴻ ⵙⵙⵔ ⵏ ⴻⵙⵜ ⴰⵙⵙⵓⵔⴷⴻⴻ ⵇⵓ ⵓⵏⴻ ⵙⴻⵓⵍⴻ ⴼⵓⵉⵙ ⴱⴰⵔ ⴼⵓⵢⴻⵔ, ⴱⴰⵙ ⴱⴰⵔ ⴱⴻⵔⵙⵓⵏⵏⴻ',
  'mfa.gov.dz':'ⵎⴼⴰ.ⴳⵓⴼ.ⴷⵣ',
  'ont.dz':'ⵓⵏⵜ.ⴷⵣ',
  'ou 240€/an — ~3 040 DZD/mois':'ⵓⵓ 240€/ⴰⵏ — ~3 040 ⴷⵣⴷ/ⵎⵓⵉⵙ',
  'ou 60€/mois illimité':'ⵓⵓ 60€/ⵎⵓⵉⵙ ⵉⵍⵍⵉⵎⵉⵜⴻ',
  'pour tout achat sur plan ou de terrain a batir':'ⴱⵓⵓⵔ ⵜⵓⵓⵜ ⴰⵙⵀⴰⵜ ⵙⵓⵔ ⴱⵍⴰⵏ ⵓⵓ ⴷⴻ ⵜⴻⵔⵔⴰⵉⵏ ⴰ ⴱⴰⵜⵉⵔ',
  'si possible : couleur, marque, immatriculation, direction de fuite':'ⵙⵉ ⴱⵓⵙⵙⵉⴱⵍⴻ : ⵙⵓⵓⵍⴻⵓⵔ, ⵎⴰⵔⵇⵓⴻ, ⵉⵎⵎⴰⵜⵔⵉⵙⵓⵍⴰⵜⵉⵓⵏ, ⴷⵉⵔⴻⵙⵜⵉⵓⵏ ⴷⴻ ⴼⵓⵉⵜⴻ',
  'signe distinctif secret':'ⵙⵉⴳⵏⴻ ⴷⵉⵙⵜⵉⵏⵙⵜⵉⴼ ⵙⴻⵙⵔⴻⵜ',
  'sur la scene apres les faits, pour preserver les indices':'ⵙⵓⵔ ⵍⴰ ⵙⵙⴻⵏⴻ ⴰⴱⵔⴻⵙ ⵍⴻⵙ ⴼⴰⵉⵜⵙ, ⴱⵓⵓⵔ ⴱⵔⴻⵙⴻⵔⴼⴻⵔ ⵍⴻⵙ ⵉⵏⴷⵉⵙⴻⵙ',
  'voir les tarifs':'ⴼⵓⵉⵔ ⵍⴻⵙ ⵜⴰⵔⵉⴼⵙ',
  '~3 040 DZD/mois':'~3 040 ⴷⵣⴷ/ⵎⵓⵉⵙ',
  '~36 475 DZD/an':'~36 475 ⴷⵣⴷ/ⴰⵏ',
  'À distance':'ⴰ ⴷⵉⵙⵜⴰⵏⵙⴻ',
  'Équipements souhaités':'ⴻⵇⵓⵉⴱⴻⵎⴻⵏⵜⵙ ⵙⵓⵓⵀⴰⵉⵜⴻⵙ',
  'الأمير عبد القادر':'الامير عبد القادر',
  'الاسم (AR)':'الاسم (ⴰⵔ)',
  'الاسم (بالعربية)':'الاسم (بالعربية)',
  'الاسم (بالفرنسية)':'الاسم (بالفرنسية)',
  'اللقب (AR)':'اللقب (ⴰⵔ)',
  'اللقب (بالعربية)':'اللقب (بالعربية)',
  'اللقب (بالفرنسية)':'اللقب (بالفرنسية)',
  'بوابة الجالية الجزائرية الرقمية الأولى':'بوابة الجالية الجزايرية الرقمية الاولى',
  'عربي':'عربي',
  'عقد الاشتراك المهني':'عقد الاشتراك المهني',
  'م. 1 — الأخلاق والأصالة:':'م. 1 — الاخلاق والاصالة:',
  'م. 2 — الالتزامات:':'م. 2 — الالتزامات:',
  'م. 3 — الفسخ:':'م. 3 — الفسخ:',
  'م. 4 — الملاحقة القضائية:':'م. 4 — الملاحقة القضايية:',
  '— Paiement par virement bancaire DZD disponible.':'— ⴱⴰⵉⴻⵎⴻⵏⵜ ⴱⴰⵔ ⴼⵉⵔⴻⵎⴻⵏⵜ ⴱⴰⵏⵙⴰⵉⵔⴻ ⴷⵣⴷ ⴷⵉⵙⴱⵓⵏⵉⴱⵍⴻ.',
  '— Tous droits reserves':'— ⵜⵓⵓⵙ ⴷⵔⵓⵉⵜⵙ ⵔⴻⵙⴻⵔⴼⴻⵙ',
  '— criez aussi fort que possible pour attirer l attention':'— ⵙⵔⵉⴻⵣ ⴰⵓⵙⵙⵉ ⴼⵓⵔⵜ ⵇⵓⴻ ⴱⵓⵙⵙⵉⴱⵍⴻ ⴱⵓⵓⵔ ⴰⵜⵜⵉⵔⴻⵔ ⵍ ⴰⵜⵜⴻⵏⵜⵉⵓⵏ',
  '— une personne en etat de choc a souvent froid':'— ⵓⵏⴻ ⴱⴻⵔⵙⵓⵏⵏⴻ ⴻⵏ ⴻⵜⴰⵜ ⴷⴻ ⵙⵀⵓⵙ ⴰ ⵙⵓⵓⴼⴻⵏⵜ ⴼⵔⵓⵉⴷ',
  '— votre securite prime sur vos biens materiels':'— ⴼⵓⵜⵔⴻ ⵙⴻⵙⵓⵔⵉⵜⴻ ⴱⵔⵉⵎⴻ ⵙⵓⵔ ⴼⵓⵙ ⴱⵉⴻⵏⵙ ⵎⴰⵜⴻⵔⵉⴻⵍⵙ',
  'ℹ️ Information générale':'ℹ ⵉⵏⴼⵓⵔⵎⴰⵜⵉⵓⵏ ⴳⴻⵏⴻⵔⴰⵍⴻ',
  '← Retour':'← ⵔⴻⵜⵓⵓⵔ',
  '← Retour à l\'accueil':'← ⵔⴻⵜⵓⵓⵔ ⴰ ⵍ\'ⴰⵙⵙⵓⴻⵉⵍ',
  '⏱️ Delai de reponse':'⏱ ⴷⴻⵍⴰⵉ ⴷⴻ ⵔⴻⴱⵓⵏⵙⴻ',
  '⏳ Chargement des annonces disponibles...':'⏳ ⵙⵀⴰⵔⴳⴻⵎⴻⵏⵜ ⴷⴻⵙ ⴰⵏⵏⵓⵏⵙⴻⵙ ⴷⵉⵙⴱⵓⵏⵉⴱⵍⴻⵙ...',
  '⏳ Chargement des demandes...':'⏳ ⵙⵀⴰⵔⴳⴻⵎⴻⵏⵜ ⴷⴻⵙ ⴷⴻⵎⴰⵏⴷⴻⵙ...',
  '⏳ Chargement des professionnels...':'⏳ ⵙⵀⴰⵔⴳⴻⵎⴻⵏⵜ ⴷⴻⵙ ⴱⵔⵓⴼⴻⵙⵙⵉⵓⵏⵏⴻⵍⵙ...',
  '⏳ Chargement...':'⏳ ⵙⵀⴰⵔⴳⴻⵎⴻⵏⵜ...',
  '⏳ En attente':'⏳ ⴻⵏ ⴰⵜⵜⴻⵏⵜⴻ',
  '⏳ En cours':'⏳ ⴻⵏ ⵙⵓⵓⵔⵙ',
  '⏳ Inscription en traitement':'⏳ ⵉⵏⵙⵙⵔⵉⴱⵜⵉⵓⵏ ⴻⵏ ⵜⵔⴰⵉⵜⴻⵎⴻⵏⵜ',
  '⚖️ Avocat':'⚖ ⴰⴼⵓⵙⴰⵜ',
  '⚖️ Avocat / محامي':'⚖ ⴰⴼⵓⵙⴰⵜ / محامي',
  '⚖️ Avocats':'⚖ ⴰⴼⵓⵙⴰⵜⵙ',
  '⚖️ Consulter la page Justice':'⚖ ⵙⵓⵏⵙⵓⵍⵜⴻⵔ ⵍⴰ ⴱⴰⴳⴻ ⵊⵓⵙⵜⵉⵙⴻ',
  '⚖️ En cas de litige':'⚖ ⴻⵏ ⵙⴰⵙ ⴷⴻ ⵍⵉⵜⵉⴳⴻ',
  '⚖️ Huissier de justice':'⚖ ⵀⵓⵉⵙⵙⵉⴻⵔ ⴷⴻ ⵊⵓⵙⵜⵉⵙⴻ',
  '⚖️ Juridique':'⚖ ⵊⵓⵔⵉⴷⵉⵇⵓⴻ',
  '⚖️ Justice':'⚖ ⵊⵓⵙⵜⵉⵙⴻ',
  '⚖️ Maître Benali — Avocat, Alger':'⚖ ⵎⴰⵉⵜⵔⴻ ⴱⴻⵏⴰⵍⵉ — ⴰⴼⵓⵙⴰⵜ, ⴰⵍⴳⴻⵔ',
  '⚖️ Votre demande juridique':'⚖ ⴼⵓⵜⵔⴻ ⴷⴻⵎⴰⵏⴷⴻ ⵊⵓⵔⵉⴷⵉⵇⵓⴻ',
  '⚠️ Anti-Arnaques':'⚠ ⴰⵏⵜⵉ-ⴰⵔⵏⴰⵇⵓⴻⵙ',
  '⚠️ Arnaques immobilieres courantes — comment se proteger':'⚠ ⴰⵔⵏⴰⵇⵓⴻⵙ ⵉⵎⵎⵓⴱⵉⵍⵉⴻⵔⴻⵙ ⵙⵓⵓⵔⴰⵏⵜⴻⵙ — ⵙⵓⵎⵎⴻⵏⵜ ⵙⴻ ⴱⵔⵓⵜⴻⴳⴻⵔ',
  '⚠️ Grève / Perturbation':'⚠ ⴳⵔⴻⴼⴻ / ⴱⴻⵔⵜⵓⵔⴱⴰⵜⵉⵓⵏ',
  '⚠️ عقد في نسختين — نسخة للمهني، نسخة تحتفظ بها DZ Diaspora':'⚠ عقد في نسختين — نسخة للمهني، نسخة تحتفظ بها ⴷⵣ ⴷⵉⴰⵙⴱⵓⵔⴰ',
  '⚡ Combien de temps pour apparaître dans l annuaire ?':'⚡ ⵙⵓⵎⴱⵉⴻⵏ ⴷⴻ ⵜⴻⵎⴱⵙ ⴱⵓⵓⵔ ⴰⴱⴱⴰⵔⴰⵉⵜⵔⴻ ⴷⴰⵏⵙ ⵍ ⴰⵏⵏⵓⴰⵉⵔⴻ ?',
  '⛴️ Ferry ENTMV':'⛴ ⴼⴻⵔⵔⵢ ⴻⵏⵜⵎⴼ',
  '⛴️ Lignes maritimes':'⛴ ⵍⵉⴳⵏⴻⵙ ⵎⴰⵔⵉⵜⵉⵎⴻⵙ',
  '✅ Accès espace pro validé':'✅ ⴰⵙⵙⴻⵙ ⴻⵙⴱⴰⵙⴻ ⴱⵔⵓ ⴼⴰⵍⵉⴷⴻ',
  '✅ Alerte publiée !':'✅ ⴰⵍⴻⵔⵜⴻ ⴱⵓⴱⵍⵉⴻⴻ !',
  '✅ Badge verifie':'✅ ⴱⴰⴷⴳⴻ ⴼⴻⵔⵉⴼⵉⴻ',
  '✅ CNI vérifiée':'✅ ⵙⵏⵉ ⴼⴻⵔⵉⴼⵉⴻⴻ',
  '✅ Confirmés':'✅ ⵙⵓⵏⴼⵉⵔⵎⴻⵙ',
  '✅ Email envoyé avec succès !':'✅ ⴻⵎⴰⵉⵍ ⴻⵏⴼⵓⵢⴻ ⴰⴼⴻⵙ ⵙⵓⵙⵙⴻⵙ !',
  '✅ Numéro d\'ordre vérifié':'✅ ⵏⵓⵎⴻⵔⵓ ⴷ\'ⵓⵔⴷⵔⴻ ⴼⴻⵔⵉⴼⵉⴻ',
  '✅ Objet trouve ! Contactez le depositaire :':'✅ ⵓⴱⵊⴻⵜ ⵜⵔⵓⵓⴼⴻ ! ⵙⵓⵏⵜⴰⵙⵜⴻⵣ ⵍⴻ ⴷⴻⴱⵓⵙⵉⵜⴰⵉⵔⴻ :',
  '✅ Passeport vérifié':'✅ ⴱⴰⵙⵙⴻⴱⵓⵔⵜ ⴼⴻⵔⵉⴼⵉⴻ',
  '✅ Professionnel publié dans l\'annuaire !':'✅ ⴱⵔⵓⴼⴻⵙⵙⵉⵓⵏⵏⴻⵍ ⴱⵓⴱⵍⵉⴻ ⴷⴰⵏⵙ ⵍ\'ⴰⵏⵏⵓⴰⵉⵔⴻ !',
  '✅ Publier dans l\'annuaire':'✅ ⴱⵓⴱⵍⵉⴻⵔ ⴷⴰⵏⵙ ⵍ\'ⴰⵏⵏⵓⴰⵉⵔⴻ',
  '✅ Validées':'✅ ⴼⴰⵍⵉⴷⴻⴻⵙ',
  '✅ Votre client email va s ouvrir avec votre message pre-rempli.':'✅ ⴼⵓⵜⵔⴻ ⵙⵍⵉⴻⵏⵜ ⴻⵎⴰⵉⵍ ⴼⴰ ⵙ ⵓⵓⴼⵔⵉⵔ ⴰⴼⴻⵙ ⴼⵓⵜⵔⴻ ⵎⴻⵙⵙⴰⴳⴻ ⴱⵔⴻ-ⵔⴻⵎⴱⵍⵉ.',
  '✅ Votre demande a été envoyée ! Nous vous répondons sous 48h.':'✅ ⴼⵓⵜⵔⴻ ⴷⴻⵎⴰⵏⴷⴻ ⴰ ⴻⵜⴻ ⴻⵏⴼⵓⵢⴻⴻ ! ⵏⵓⵓⵙ ⴼⵓⵓⵙ ⵔⴻⴱⵓⵏⴷⵓⵏⵙ ⵙⵓⵓⵙ 48ⵀ.',
  '✅ Votre demande a été publiée !':'✅ ⴼⵓⵜⵔⴻ ⴷⴻⵎⴰⵏⴷⴻ ⴰ ⴻⵜⴻ ⴱⵓⴱⵍⵉⴻⴻ !',
  '✅ Vérifié DZ Diaspora':'✅ ⴼⴻⵔⵉⴼⵉⴻ ⴷⵣ ⴷⵉⴰⵙⴱⵓⵔⴰ',
  '✈️ Arnaques voyage et tourisme':'✈ ⴰⵔⵏⴰⵇⵓⴻⵙ ⴼⵓⵢⴰⴳⴻ ⴻⵜ ⵜⵓⵓⵔⵉⵙⵎⴻ',
  '✈️ Samira B. — Diaspora, Lyon':'✈ ⵙⴰⵎⵉⵔⴰ ⴱ. — ⴷⵉⴰⵙⴱⵓⵔⴰ, ⵍⵢⵓⵏ',
  '✈️ Sites officiels des compagnies aeriennes':'✈ ⵙⵉⵜⴻⵙ ⵓⴼⴼⵉⵙⵉⴻⵍⵙ ⴷⴻⵙ ⵙⵓⵎⴱⴰⴳⵏⵉⴻⵙ ⴰⴻⵔⵉⴻⵏⵏⴻⵙ',
  '✈️ Transport':'✈ ⵜⵔⴰⵏⵙⴱⵓⵔⵜ',
  '✈️ Vol Air Algérie':'✈ ⴼⵓⵍ ⴰⵉⵔ ⴰⵍⴳⴻⵔⵉⴻ',
  '✉️ Contact':'✉ ⵙⵓⵏⵜⴰⵙⵜ',
  '✍️ Signature électronique / التوقيع الإلكتروني':'✍ ⵙⵉⴳⵏⴰⵜⵓⵔⴻ ⴻⵍⴻⵙⵜⵔⵓⵏⵉⵇⵓⴻ / التوقيع الالكتروني',
  '✏️ Sujet personnalisé...':'✏ ⵙⵓⵊⴻⵜ ⴱⴻⵔⵙⵓⵏⵏⴰⵍⵉⵙⴻ...',
  '❌ Annulés':'❌ ⴰⵏⵏⵓⵍⴻⵙ',
  '❌ Inscription refusée':'❌ ⵉⵏⵙⵙⵔⵉⴱⵜⵉⵓⵏ ⵔⴻⴼⵓⵙⴻⴻ',
  '❌ Puis-je annuler mon abonnement ?':'❌ ⴱⵓⵉⵙ-ⵊⴻ ⴰⵏⵏⵓⵍⴻⵔ ⵎⵓⵏ ⴰⴱⵓⵏⵏⴻⵎⴻⵏⵜ ?',
  '❌ Refusées':'❌ ⵔⴻⴼⵓⵙⴻⴻⵙ',
  '➕ Deposer une annonce':'➕ ⴷⴻⴱⵓⵙⴻⵔ ⵓⵏⴻ ⴰⵏⵏⵓⵏⵙⴻ',
  '⭐ Au-dela, abonnement Pro necessaire —':'⭐ ⴰⵓ-ⴷⴻⵍⴰ, ⴰⴱⵓⵏⵏⴻⵎⴻⵏⵜ ⴱⵔⵓ ⵏⴻⵙⴻⵙⵙⴰⵉⵔⴻ —',
  '⭐ Avis clients à valider':'⭐ ⴰⴼⵉⵙ ⵙⵍⵉⴻⵏⵜⵙ ⴰ ⴼⴰⵍⵉⴷⴻⵔ',
  '⭐ Fiche Mise en Avant':'⭐ ⴼⵉⵙⵀⴻ ⵎⵉⵙⴻ ⴻⵏ ⴰⴼⴰⵏⵜ',
  '⭐ Laisser un avis':'⭐ ⵍⴰⵉⵙⵙⴻⵔ ⵓⵏ ⴰⴼⵉⵙ',
  '⭐ Le plus populaire':'⭐ ⵍⴻ ⴱⵍⵓⵙ ⴱⵓⴱⵓⵍⴰⵉⵔⴻ',
  '⭐ Merci pour votre avis !':'⭐ ⵎⴻⵔⵙⵉ ⴱⵓⵓⵔ ⴼⵓⵜⵔⴻ ⴰⴼⵉⵙ !',
  '⭐ PARTENAIRE OFFICIEL':'⭐ ⴱⴰⵔⵜⴻⵏⴰⵉⵔⴻ ⵓⴼⴼⵉⵙⵉⴻⵍ',
  '⭐ Premium DZ Diaspora':'⭐ ⴱⵔⴻⵎⵉⵓⵎ ⴷⵣ ⴷⵉⴰⵙⴱⵓⵔⴰ',
  '⭐ Publier mon avis':'⭐ ⴱⵓⴱⵍⵉⴻⵔ ⵎⵓⵏ ⴰⴼⵉⵙ',
  'ⵣ Kab':'ⵣ ⴽⴰⴱ',
  '🆓 Particulier':'🆓 ⴱⴰⵔⵜⵉⵙⵓⵍⵉⴻⵔ',
  '🆕 Renouvellement du passeport en ligne':'🆕 ⵔⴻⵏⵓⵓⴼⴻⵍⵍⴻⵎⴻⵏⵜ ⴷⵓ ⴱⴰⵙⵙⴻⴱⵓⵔⵜ ⴻⵏ ⵍⵉⴳⵏⴻ',
  '🆘 Que faire si vous etes victime ?':'🆘 ⵇⵓⴻ ⴼⴰⵉⵔⴻ ⵙⵉ ⴼⵓⵓⵙ ⴻⵜⴻⵙ ⴼⵉⵙⵜⵉⵎⴻ ?',
  '🇧🇪 Belgique':'🇧🇪 ⴱⴻⵍⴳⵉⵇⵓⴻ',
  '🇨🇦 Ambassade du Canada':'🇨🇦 ⴰⵎⴱⴰⵙⵙⴰⴷⴻ ⴷⵓ ⵙⴰⵏⴰⴷⴰ',
  '🇨🇦 Canada':'🇨🇦 ⵙⴰⵏⴰⴷⴰ',
  '🇩🇿 Algérie':'🇩🇿 ⴰⵍⴳⴻⵔⵉⴻ',
  '🇩🇿 Algérie (virement bancaire DZD)':'🇩🇿 ⴰⵍⴳⴻⵔⵉⴻ (ⴼⵉⵔⴻⵎⴻⵏⵜ ⴱⴰⵏⵙⴰⵉⵔⴻ ⴷⵣⴷ)',
  '🇩🇿 Annonceurs en Algérie':'🇩🇿 ⴰⵏⵏⵓⵏⵙⴻⵓⵔⵙ ⴻⵏ ⴰⵍⴳⴻⵔⵉⴻ',
  '🇩🇿 Clients en Algérie — Paiement par virement bancaire DZD':'🇩🇿 ⵙⵍⵉⴻⵏⵜⵙ ⴻⵏ ⴰⵍⴳⴻⵔⵉⴻ — ⴱⴰⵉⴻⵎⴻⵏⵜ ⴱⴰⵔ ⴼⵉⵔⴻⵎⴻⵏⵜ ⴱⴰⵏⵙⴰⵉⵔⴻ ⴷⵣⴷ',
  '🇩🇿 DZ DIASPORA':'🇩🇿 ⴷⵣ ⴷⵉⴰⵙⴱⵓⵔⴰ',
  '🇩🇿 DZ Diaspora':'🇩🇿 ⴷⵣ ⴷⵉⴰⵙⴱⵓⵔⴰ',
  '🇩🇿 Paiement par virement bancaire DZD':'🇩🇿 ⴱⴰⵉⴻⵎⴻⵏⵜ ⴱⴰⵔ ⴼⵉⵔⴻⵎⴻⵏⵜ ⴱⴰⵏⵙⴰⵉⵔⴻ ⴷⵣⴷ',
  '🇪🇸 Ambassade d Espagne':'🇪🇸 ⴰⵎⴱⴰⵙⵙⴰⴷⴻ ⴷ ⴻⵙⴱⴰⴳⵏⴻ',
  '🇫🇷 Ambassade de France':'🇫🇷 ⴰⵎⴱⴰⵙⵙⴰⴷⴻ ⴷⴻ ⴼⵔⴰⵏⵙⴻ',
  '🇫🇷 France':'🇫🇷 ⴼⵔⴰⵏⵙⴻ',
  '🇬🇧 Ambassade du Royaume-Uni':'🇬🇧 ⴰⵎⴱⴰⵙⵙⴰⴷⴻ ⴷⵓ ⵔⵓⵢⴰⵓⵎⴻ-ⵓⵏⵉ',
  '🇲🇦 Ambassade du Maroc':'🇲🇦 ⴰⵎⴱⴰⵙⵙⴰⴷⴻ ⴷⵓ ⵎⴰⵔⵓⵙ',
  '🇹🇳 Ambassade de Tunisie':'🇹🇳 ⴰⵎⴱⴰⵙⵙⴰⴷⴻ ⴷⴻ ⵜⵓⵏⵉⵙⵉⴻ',
  '🇹🇷 Ambassade de Turquie':'🇹🇷 ⴰⵎⴱⴰⵙⵙⴰⴷⴻ ⴷⴻ ⵜⵓⵔⵇⵓⵉⴻ',
  '🇺🇸 Ambassade des Etats-Unis':'🇺🇸 ⴰⵎⴱⴰⵙⵙⴰⴷⴻ ⴷⴻⵙ ⴻⵜⴰⵜⵙ-ⵓⵏⵉⵙ',
  '🌊 Vue mer':'🌊 ⴼⵓⴻ ⵎⴻⵔ',
  '🌍 Dans quels pays suis-je visible ?':'🌍 ⴷⴰⵏⵙ ⵇⵓⴻⵍⵙ ⴱⴰⵢⵙ ⵙⵓⵉⵙ-ⵊⴻ ⴼⵉⵙⵉⴱⵍⴻ ?',
  '🌍 Portée mondiale':'🌍 ⴱⵓⵔⵜⴻⴻ ⵎⵓⵏⴷⵉⴰⵍⴻ',
  '🌍 Visibilite mondiale':'🌍 ⴼⵉⵙⵉⴱⵉⵍⵉⵜⴻ ⵎⵓⵏⴷⵉⴰⵍⴻ',
  '🌐 Toutes les pages':'🌐 ⵜⵓⵓⵜⴻⵙ ⵍⴻⵙ ⴱⴰⴳⴻⵙ',
  '🌟 Sites incontournables':'🌟 ⵙⵉⵜⴻⵙ ⵉⵏⵙⵓⵏⵜⵓⵓⵔⵏⴰⴱⵍⴻⵙ',
  '🌿 Jardin':'🌿 ⵊⴰⵔⴷⵉⵏ',
  '🎉 Votre demande a été envoyée avec succès !':'🎉 ⴼⵓⵜⵔⴻ ⴷⴻⵎⴰⵏⴷⴻ ⴰ ⴻⵜⴻ ⴻⵏⴼⵓⵢⴻⴻ ⴰⴼⴻⵙ ⵙⵓⵙⵙⴻⵙ !',
  '🎬 Vidéo Sponsorisée':'🎬 ⴼⵉⴷⴻⵓ ⵙⴱⵓⵏⵙⵓⵔⵉⵙⴻⴻ',
  '🎯 Audience ciblée':'🎯 ⴰⵓⴷⵉⴻⵏⵙⴻ ⵙⵉⴱⵍⴻⴻ',
  '🏁 Terminés':'🏁 ⵜⴻⵔⵎⵉⵏⴻⵙ',
  '🏅 Badge':'🏅 ⴱⴰⴷⴳⴻ',
  '🏅 Certifié DZ Diaspora':'🏅 ⵙⴻⵔⵜⵉⴼⵉⴻ ⴷⵣ ⴷⵉⴰⵙⴱⵓⵔⴰ',
  '🏊 Piscine':'🏊 ⴱⵉⵙⵙⵉⵏⴻ',
  '🏖️ Plages et littoral':'🏖 ⴱⵍⴰⴳⴻⵙ ⴻⵜ ⵍⵉⵜⵜⵓⵔⴰⵍ',
  '🏛️ Programmes de logement public':'🏛 ⴱⵔⵓⴳⵔⴰⵎⵎⴻⵙ ⴷⴻ ⵍⵓⴳⴻⵎⴻⵏⵜ ⴱⵓⴱⵍⵉⵙ',
  '🏛️ Tourisme en Algerie':'🏛 ⵜⵓⵓⵔⵉⵙⵎⴻ ⴻⵏ ⴰⵍⴳⴻⵔⵉⴻ',
  '🏛️ Trouver le tribunal de votre wilaya':'🏛 ⵜⵔⵓⵓⴼⴻⵔ ⵍⴻ ⵜⵔⵉⴱⵓⵏⴰⵍ ⴷⴻ ⴼⵓⵜⵔⴻ ⵡⵉⵍⴰⵢⴰ',
  '🏠 Accueil':'🏠 ⴰⵙⵙⵓⴻⵉⵍ',
  '🏠 Arnaques immobilieres':'🏠 ⴰⵔⵏⴰⵇⵓⴻⵙ ⵉⵎⵎⵓⴱⵉⵍⵉⴻⵔⴻⵙ',
  '🏠 Immobilier':'🏠 ⵉⵎⵎⵓⴱⵉⵍⵉⴻⵔ',
  '🏠 Karim D. — Particulier, Oran':'🏠 ⴽⴰⵔⵉⵎ ⴷ. — ⴱⴰⵔⵜⵉⵙⵓⵍⵉⴻⵔ, ⵓⵔⴰⵏ',
  '🏠 Publiez vos annonces immobilieres':'🏠 ⴱⵓⴱⵍⵉⴻⵣ ⴼⵓⵙ ⴰⵏⵏⵓⵏⵙⴻⵙ ⵉⵎⵎⵓⴱⵉⵍⵉⴻⵔⴻⵙ',
  '🏠 Votre recherche immobilière':'🏠 ⴼⵓⵜⵔⴻ ⵔⴻⵙⵀⴻⵔⵙⵀⴻ ⵉⵎⵎⵓⴱⵉⵍⵉⴻⵔⴻ',
  '🏠 À domicile':'🏠 ⴰ ⴷⵓⵎⵉⵙⵉⵍⴻ',
  '🏢 En cabinet (présentiel)':'🏢 ⴻⵏ ⵙⴰⴱⵉⵏⴻⵜ (ⴱⵔⴻⵙⴻⵏⵜⵉⴻⵍ)',
  '🏥 Medecin generaliste':'🏥 ⵎⴻⴷⴻⵙⵉⵏ ⴳⴻⵏⴻⵔⴰⵍⵉⵙⵜⴻ',
  '🏥 Medecin specialiste':'🏥 ⵎⴻⴷⴻⵙⵉⵏ ⵙⴱⴻⵙⵉⴰⵍⵉⵙⵜⴻ',
  '🏥 Medecins':'🏥 ⵎⴻⴷⴻⵙⵉⵏⵙ',
  '🏥 Médecin généraliste':'🏥 ⵎⴻⴷⴻⵙⵉⵏ ⴳⴻⵏⴻⵔⴰⵍⵉⵙⵜⴻ',
  '🏥 Médecin spécialiste':'🏥 ⵎⴻⴷⴻⵙⵉⵏ ⵙⴱⴻⵙⵉⴰⵍⵉⵙⵜⴻ',
  '🏥 Médical':'🏥 ⵎⴻⴷⵉⵙⴰⵍ',
  '🏥 Sante':'🏥 ⵙⴰⵏⵜⴻ',
  '🏥 Santé':'🏥 ⵙⴰⵏⵜⴻ',
  '🏥 Votre demande médicale':'🏥 ⴼⵓⵜⵔⴻ ⴷⴻⵎⴰⵏⴷⴻ ⵎⴻⴷⵉⵙⴰⵍⴻ',
  '🏦 Financement bancaire':'🏦 ⴼⵉⵏⴰⵏⵙⴻⵎⴻⵏⵜ ⴱⴰⵏⵙⴰⵉⵔⴻ',
  '🏫 Proche école':'🏫 ⴱⵔⵓⵙⵀⴻ ⴻⵙⵓⵍⴻ',
  '🏷️ Achat':'🏷 ⴰⵙⵀⴰⵜ',
  '👁️ Consulter':'👁 ⵙⵓⵏⵙⵓⵍⵜⴻⵔ',
  '👜 Sac / portefeuille':'👜 ⵙⴰⵙ / ⴱⵓⵔⵜⴻⴼⴻⵓⵉⵍⵍⴻ',
  '👜 Sac, cabas, valise, portefeuille':'👜 ⵙⴰⵙ, ⵙⴰⴱⴰⵙ, ⴼⴰⵍⵉⵙⴻ, ⴱⵓⵔⵜⴻⴼⴻⵓⵉⵍⵍⴻ',
  '👤 Informations du professionnel':'👤 ⵉⵏⴼⵓⵔⵎⴰⵜⵉⵓⵏⵙ ⴷⵓ ⴱⵔⵓⴼⴻⵙⵙⵉⵓⵏⵏⴻⵍ',
  '👤 Mon Espace':'👤 ⵎⵓⵏ ⴻⵙⴱⴰⵙⴻ',
  '👤 Se connecter':'👤 ⵙⴻ ⵙⵓⵏⵏⴻⵙⵜⴻⵔ',
  '👨‍⚕️ Ajouter un professionnel':'👨‍⚕ ⴰⵊⵓⵓⵜⴻⵔ ⵓⵏ ⴱⵔⵓⴼⴻⵙⵙⵉⵓⵏⵏⴻⵍ',
  '👨‍⚕️ Espace Pro':'👨‍⚕ ⴻⵙⴱⴰⵙⴻ ⴱⵔⵓ',
  '👨‍⚕️ Espace Professionnel':'👨‍⚕ ⴻⵙⴱⴰⵙⴻ ⴱⵔⵓⴼⴻⵙⵙⵉⵓⵏⵏⴻⵍ',
  '👨‍⚕️ Inscription Pro':'👨‍⚕ ⵉⵏⵙⵙⵔⵉⴱⵜⵉⵓⵏ ⴱⵔⵓ',
  '👨‍⚕️ Inscription Professionnel':'👨‍⚕ ⵉⵏⵙⵙⵔⵉⴱⵜⵉⵓⵏ ⴱⵔⵓⴼⴻⵙⵙⵉⵓⵏⵏⴻⵍ',
  '👨‍⚕️ Inscrire mon cabinet':'👨‍⚕ ⵉⵏⵙⵙⵔⵉⵔⴻ ⵎⵓⵏ ⵙⴰⴱⵉⵏⴻⵜ',
  '👨‍⚕️ Inscrire mon cabinet — 20€/mois':'👨‍⚕ ⵉⵏⵙⵙⵔⵉⵔⴻ ⵎⵓⵏ ⵙⴰⴱⵉⵏⴻⵜ — 20€/ⵎⵓⵉⵙ',
  '👨‍⚕️ Ma fiche pro':'👨‍⚕ ⵎⴰ ⴼⵉⵙⵀⴻ ⴱⵔⵓ',
  '👨‍⚕️ Medecins specialistes — consultation et RDV':'👨‍⚕ ⵎⴻⴷⴻⵙⵉⵏⵙ ⵙⴱⴻⵙⵉⴰⵍⵉⵙⵜⴻⵙ — ⵙⵓⵏⵙⵓⵍⵜⴰⵜⵉⵓⵏ ⴻⵜ ⵔⴷⴼ',
  '👨‍⚕️ Professionnel':'👨‍⚕ ⴱⵔⵓⴼⴻⵙⵙⵉⵓⵏⵏⴻⵍ',
  '👨‍⚕️ S inscrire':'👨‍⚕ ⵙ ⵉⵏⵙⵙⵔⵉⵔⴻ',
  '👨‍⚕️ S inscrire dans l annuaire':'👨‍⚕ ⵙ ⵉⵏⵙⵙⵔⵉⵔⴻ ⴷⴰⵏⵙ ⵍ ⴰⵏⵏⵓⴰⵉⵔⴻ',
  '👨‍⚕️ S\'inscrire comme professionnel':'👨‍⚕ ⵙ\'ⵉⵏⵙⵙⵔⵉⵔⴻ ⵙⵓⵎⵎⴻ ⴱⵔⵓⴼⴻⵙⵙⵉⵓⵏⵏⴻⵍ',
  '👨‍⚖️ Avocats, notaires et mediateurs':'👨‍⚖ ⴰⴼⵓⵙⴰⵜⵙ, ⵏⵓⵜⴰⵉⵔⴻⵙ ⴻⵜ ⵎⴻⴷⵉⴰⵜⴻⵓⵔⵙ',
  '💊 Pharmacien':'💊 ⴱⵀⴰⵔⵎⴰⵙⵉⴻⵏ',
  '💊 Pharmacien / صيدلاني':'💊 ⴱⵀⴰⵔⵎⴰⵙⵉⴻⵏ / صيدلاني',
  '💊 Pharmaciens':'💊 ⴱⵀⴰⵔⵎⴰⵙⵉⴻⵏⵙ',
  '💊 Pharmacies de garde par wilaya':'💊 ⴱⵀⴰⵔⵎⴰⵙⵉⴻⵙ ⴷⴻ ⴳⴰⵔⴷⴻ ⴱⴰⵔ ⵡⵉⵍⴰⵢⴰ',
  '💍 Bijou':'💍 ⴱⵉⵊⵓⵓ',
  '💍 Bijou, montre, accessoire de valeur':'💍 ⴱⵉⵊⵓⵓ, ⵎⵓⵏⵜⵔⴻ, ⴰⵙⵙⴻⵙⵙⵓⵉⵔⴻ ⴷⴻ ⴼⴰⵍⴻⵓⵔ',
  '💡 Conseils pratiques pour les visiteurs':'💡 ⵙⵓⵏⵙⴻⵉⵍⵙ ⴱⵔⴰⵜⵉⵇⵓⴻⵙ ⴱⵓⵓⵔ ⵍⴻⵙ ⴼⵉⵙⵉⵜⴻⵓⵔⵙ',
  '💬 4 Langues':'💬 4 ⵍⴰⵏⴳⵓⴻⵙ',
  '💰 Arnaques financieres':'💰 ⴰⵔⵏⴰⵇⵓⴻⵙ ⴼⵉⵏⴰⵏⵙⵉⴻⵔⴻⵙ',
  '💰 Finance':'💰 ⴼⵉⵏⴰⵏⵙⴻ',
  '💰 Vente (je vends)':'💰 ⴼⴻⵏⵜⴻ (ⵊⴻ ⴼⴻⵏⴷⵙ)',
  '💳 Comment payer si je suis en Algérie ?':'💳 ⵙⵓⵎⵎⴻⵏⵜ ⴱⴰⵢⴻⵔ ⵙⵉ ⵊⴻ ⵙⵓⵉⵙ ⴻⵏ ⴰⵍⴳⴻⵔⵉⴻ ?',
  '💳 Paiement confirmé':'💳 ⴱⴰⵉⴻⵎⴻⵏⵜ ⵙⵓⵏⴼⵉⵔⵎⴻ',
  '💻 Arnaques en ligne':'💻 ⴰⵔⵏⴰⵇⵓⴻⵙ ⴻⵏ ⵍⵉⴳⵏⴻ',
  '💻 Téléconsultation (vidéo)':'💻 ⵜⴻⵍⴻⵙⵓⵏⵙⵓⵍⵜⴰⵜⵉⵓⵏ (ⴼⵉⴷⴻⵓ)',
  '💼 Expert comptable':'💼 ⴻⵅⴱⴻⵔⵜ ⵙⵓⵎⴱⵜⴰⴱⵍⴻ',
  '📄 Administratif':'📄 ⴰⴷⵎⵉⵏⵉⵙⵜⵔⴰⵜⵉⴼ',
  '📄 Document':'📄 ⴷⵓⵙⵓⵎⴻⵏⵜ',
  '📄 Document (CNI, passeport, permis de conduire, carte consulaire...)':'📄 ⴷⵓⵙⵓⵎⴻⵏⵜ (ⵙⵏⵉ, ⴱⴰⵙⵙⴻⴱⵓⵔⵜ, ⴱⴻⵔⵎⵉⵙ ⴷⴻ ⵙⵓⵏⴷⵓⵉⵔⴻ, ⵙⴰⵔⵜⴻ ⵙⵓⵏⵙⵓⵍⴰⵉⵔⴻ...)',
  '📄 Faux documents et demarches':'📄 ⴼⴰⵓⵅ ⴷⵓⵙⵓⵎⴻⵏⵜⵙ ⴻⵜ ⴷⴻⵎⴰⵔⵙⵀⴻⵙ',
  '📄 Guide informatif (consultation)':'📄 ⴳⵓⵉⴷⴻ ⵉⵏⴼⵓⵔⵎⴰⵜⵉⴼ (ⵙⵓⵏⵙⵓⵍⵜⴰⵜⵉⵓⵏ)',
  '📅 Abonnement choisi / الاشتراك المختار':'📅 ⴰⴱⵓⵏⵏⴻⵎⴻⵏⵜ ⵙⵀⵓⵉⵙⵉ / الاشتراك المختار',
  '📅 Admin — Rendez-vous':'📅 ⴰⴷⵎⵉⵏ — ⵔⴻⵏⴷⴻⵣ-ⴼⵓⵓⵙ',
  '📅 Confirmer la demande de RDV':'📅 ⵙⵓⵏⴼⵉⵔⵎⴻⵔ ⵍⴰ ⴷⴻⵎⴰⵏⴷⴻ ⴷⴻ ⵔⴷⴼ',
  '📅 Gérer les RDV':'📅 ⴳⴻⵔⴻⵔ ⵍⴻⵙ ⵔⴷⴼ',
  '📅 Prendre un rendez-vous':'📅 ⴱⵔⴻⵏⴷⵔⴻ ⵓⵏ ⵔⴻⵏⴷⴻⵣ-ⴼⵓⵓⵙ',
  '📅 RDV confirmé':'📅 ⵔⴷⴼ ⵙⵓⵏⴼⵉⵔⵎⴻ',
  '📅 Votre demande de rendez-vous a été envoyée !':'📅 ⴼⵓⵜⵔⴻ ⴷⴻⵎⴰⵏⴷⴻ ⴷⴻ ⵔⴻⵏⴷⴻⵣ-ⴼⵓⵓⵙ ⴰ ⴻⵜⴻ ⴻⵏⴼⵓⵢⴻⴻ !',
  '📋 Admin Pro':'📋 ⴰⴷⵎⵉⵏ ⴱⵔⵓ',
  '📋 Administration DZ Diaspora':'📋 ⴰⴷⵎⵉⵏⵉⵙⵜⵔⴰⵜⵉⵓⵏ ⴷⵣ ⴷⵉⴰⵙⴱⵓⵔⴰ',
  '📋 Annonces':'📋 ⴰⵏⵏⵓⵏⵙⴻⵙ',
  '📋 Autre':'📋 ⴰⵓⵜⵔⴻ',
  '📋 Autre / أخرى':'📋 ⴰⵓⵜⵔⴻ / اخرى',
  '📋 Contrat d\'Abonnement Professionnel':'📋 ⵙⵓⵏⵜⵔⴰⵜ ⴷ\'ⴰⴱⵓⵏⵏⴻⵎⴻⵏⵜ ⴱⵔⵓⴼⴻⵙⵙⵉⵓⵏⵏⴻⵍ',
  '📋 Demandes d\'inscription pro en attente':'📋 ⴷⴻⵎⴰⵏⴷⴻⵙ ⴷ\'ⵉⵏⵙⵙⵔⵉⴱⵜⵉⵓⵏ ⴱⵔⵓ ⴻⵏ ⴰⵜⵜⴻⵏⵜⴻ',
  '📋 Deposer la fiche':'📋 ⴷⴻⴱⵓⵙⴻⵔ ⵍⴰ ⴼⵉⵙⵀⴻ',
  '📋 Deposer un objet trouve':'📋 ⴷⴻⴱⵓⵙⴻⵔ ⵓⵏ ⵓⴱⵊⴻⵜ ⵜⵔⵓⵓⴼⴻ',
  '📋 Déposer une demande':'📋 ⴷⴻⴱⵓⵙⴻⵔ ⵓⵏⴻ ⴷⴻⵎⴰⵏⴷⴻ',
  '📋 Envoyer ma demande':'📋 ⴻⵏⴼⵓⵢⴻⵔ ⵎⴰ ⴷⴻⵎⴰⵏⴷⴻ',
  '📋 Mes demandes':'📋 ⵎⴻⵙ ⴷⴻⵎⴰⵏⴷⴻⵙ',
  '📋 Publier ma demande':'📋 ⴱⵓⴱⵍⵉⴻⵔ ⵎⴰ ⴷⴻⵎⴰⵏⴷⴻ',
  '📋 Suivre mes demandes':'📋 ⵙⵓⵉⴼⵔⴻ ⵎⴻⵙ ⴷⴻⵎⴰⵏⴷⴻⵙ',
  '📕 Passeport biometrique':'📕 ⴱⴰⵙⵙⴻⴱⵓⵔⵜ ⴱⵉⵓⵎⴻⵜⵔⵉⵇⵓⴻ',
  '📖 Annuaire':'📖 ⴰⵏⵏⵓⴰⵉⵔⴻ',
  '📖 Annuaire Pro':'📖 ⴰⵏⵏⵓⴰⵉⵔⴻ ⴱⵔⵓ',
  '📖 Annuaire Professionnels':'📖 ⴰⵏⵏⵓⴰⵉⵔⴻ ⴱⵔⵓⴼⴻⵙⵙⵉⵓⵏⵏⴻⵍⵙ',
  '📜 Actes d etat civil et legalisation de documents':'📜 ⴰⵙⵜⴻⵙ ⴷ ⴻⵜⴰⵜ ⵙⵉⴼⵉⵍ ⴻⵜ ⵍⴻⴳⴰⵍⵉⵙⴰⵜⵉⵓⵏ ⴷⴻ ⴷⵓⵙⵓⵎⴻⵏⵜⵙ',
  '📜 Conditions generales d utilisation et mentions legales':'📜 ⵙⵓⵏⴷⵉⵜⵉⵓⵏⵙ ⴳⴻⵏⴻⵔⴰⵍⴻⵙ ⴷ ⵓⵜⵉⵍⵉⵙⴰⵜⵉⵓⵏ ⴻⵜ ⵎⴻⵏⵜⵉⵓⵏⵙ ⵍⴻⴳⴰⵍⴻⵙ',
  '📜 Notaire':'📜 ⵏⵓⵜⴰⵉⵔⴻ',
  '📜 Notaire / موثق':'📜 ⵏⵓⵜⴰⵉⵔⴻ / موثق',
  '📜 Notaires':'📜 ⵏⵓⵜⴰⵉⵔⴻⵙ',
  '📜 Objets recents':'📜 ⵓⴱⵊⴻⵜⵙ ⵔⴻⵙⴻⵏⵜⵙ',
  '📝 Formulaire officiel Mod.295 (a remplir)':'📝 ⴼⵓⵔⵎⵓⵍⴰⵉⵔⴻ ⵓⴼⴼⵉⵙⵉⴻⵍ ⵎⵓⴷ.295 (ⴰ ⵔⴻⵎⴱⵍⵉⵔ)',
  '📞 Appeler le commercial : +213 (0) 799 87 28 90':'📞 ⴰⴱⴱⴻⵍⴻⵔ ⵍⴻ ⵙⵓⵎⵎⴻⵔⵙⵉⴰⵍ : +213 (0) 799 87 28 90',
  '📞 Contact direct':'📞 ⵙⵓⵏⵜⴰⵙⵜ ⴷⵉⵔⴻⵙⵜ',
  '📞 Contacts utiles tourisme':'📞 ⵙⵓⵏⵜⴰⵙⵜⵙ ⵓⵜⵉⵍⴻⵙ ⵜⵓⵓⵔⵉⵙⵎⴻ',
  '📞 Nous contacter':'📞 ⵏⵓⵓⵙ ⵙⵓⵏⵜⴰⵙⵜⴻⵔ',
  '📞 Vos coordonnées':'📞 ⴼⵓⵙ ⵙⵓⵓⵔⴷⵓⵏⵏⴻⴻⵙ',
  '📢 Annonces':'📢 ⴰⵏⵏⵓⵏⵙⴻⵙ',
  '📢 Annonces Pro':'📢 ⴰⵏⵏⵓⵏⵙⴻⵙ ⴱⵔⵓ',
  '📢 Publier l\'alerte':'📢 ⴱⵓⴱⵍⵉⴻⵔ ⵍ\'ⴰⵍⴻⵔⵜⴻ',
  '📢 Publier une alerte transport':'📢 ⴱⵓⴱⵍⵉⴻⵔ ⵓⵏⴻ ⴰⵍⴻⵔⵜⴻ ⵜⵔⴰⵏⵙⴱⵓⵔⵜ',
  '📢 Publier une annonce':'📢 ⴱⵓⴱⵍⵉⴻⵔ ⵓⵏⴻ ⴰⵏⵏⵓⵏⵙⴻ',
  '📣 Admin Pub':'📣 ⴰⴷⵎⵉⵏ ⴱⵓⴱ',
  '📣 Admin — Commandes Pub':'📣 ⴰⴷⵎⵉⵏ — ⵙⵓⵎⵎⴰⵏⴷⴻⵙ ⴱⵓⴱ',
  '📣 Commander cet espace':'📣 ⵙⵓⵎⵎⴰⵏⴷⴻⵔ ⵙⴻⵜ ⴻⵙⴱⴰⵙⴻ',
  '📣 Commander un espace maintenant':'📣 ⵙⵓⵎⵎⴰⵏⴷⴻⵔ ⵓⵏ ⴻⵙⴱⴰⵙⴻ ⵎⴰⵉⵏⵜⴻⵏⴰⵏⵜ',
  '📣 Commander un espace publicitaire':'📣 ⵙⵓⵎⵎⴰⵏⴷⴻⵔ ⵓⵏ ⴻⵙⴱⴰⵙⴻ ⴱⵓⴱⵍⵉⵙⵉⵜⴰⵉⵔⴻ',
  '📣 Commander un nouvel espace':'📣 ⵙⵓⵎⵎⴰⵏⴷⴻⵔ ⵓⵏ ⵏⵓⵓⴼⴻⵍ ⴻⵙⴱⴰⵙⴻ',
  '📣 Envoyer ma demande':'📣 ⴻⵏⴼⵓⵢⴻⵔ ⵎⴰ ⴷⴻⵎⴰⵏⴷⴻ',
  '📣 Espace Publicitaire':'📣 ⴻⵙⴱⴰⵙⴻ ⴱⵓⴱⵍⵉⵙⵉⵜⴰⵉⵔⴻ',
  '📣 Espace pub':'📣 ⴻⵙⴱⴰⵙⴻ ⴱⵓⴱ',
  '📣 Gérer les pubs':'📣 ⴳⴻⵔⴻⵔ ⵍⴻⵙ ⴱⵓⴱⵙ',
  '📣 Mes pubs':'📣 ⵎⴻⵙ ⴱⵓⴱⵙ',
  '📣 Pub en ligne':'📣 ⴱⵓⴱ ⴻⵏ ⵍⵉⴳⵏⴻ',
  '📣 Publiées':'📣 ⴱⵓⴱⵍⵉⴻⴻⵙ',
  '📤 Publier l annonce':'📤 ⴱⵓⴱⵍⵉⴻⵔ ⵍ ⴰⵏⵏⵓⵏⵙⴻ',
  '📥 Telecharger':'📥 ⵜⴻⵍⴻⵙⵀⴰⵔⴳⴻⵔ',
  '📥 Telecharger DZ Diaspora (APK — 60 MB)':'📥 ⵜⴻⵍⴻⵙⵀⴰⵔⴳⴻⵔ ⴷⵣ ⴷⵉⴰⵙⴱⵓⵔⴰ (ⴰⴱⴽ — 60 ⵎⴱ)',
  '📥 Télécharger contrat vierge':'📥 ⵜⴻⵍⴻⵙⵀⴰⵔⴳⴻⵔ ⵙⵓⵏⵜⵔⴰⵜ ⴼⵉⴻⵔⴳⴻ',
  '📥 Télécharger la plaquette':'📥 ⵜⴻⵍⴻⵙⵀⴰⵔⴳⴻⵔ ⵍⴰ ⴱⵍⴰⵇⵓⴻⵜⵜⴻ',
  '📦 Autre':'📦 ⴰⵓⵜⵔⴻ',
  '📦 Autre objet':'📦 ⴰⵓⵜⵔⴻ ⵓⴱⵊⴻⵜ',
  '📦 Envoi de colis et fret':'📦 ⴻⵏⴼⵓⵉ ⴷⴻ ⵙⵓⵍⵉⵙ ⴻⵜ ⴼⵔⴻⵜ',
  '📧 Email direct':'📧 ⴻⵎⴰⵉⵍ ⴷⵉⵔⴻⵙⵜ',
  '📧 Envoyer l\'email':'📧 ⴻⵏⴼⵓⵢⴻⵔ ⵍ\'ⴻⵎⴰⵉⵍ',
  '📧 Envoyer un email':'📧 ⴻⵏⴼⵓⵢⴻⵔ ⵓⵏ ⴻⵎⴰⵉⵍ',
  '📩 Demander un devis':'📩 ⴷⴻⵎⴰⵏⴷⴻⵔ ⵓⵏ ⴷⴻⴼⵉⵙ',
  '📩 Envoyer ma demande de devis':'📩 ⴻⵏⴼⵓⵢⴻⵔ ⵎⴰ ⴷⴻⵎⴰⵏⴷⴻ ⴷⴻ ⴷⴻⴼⵉⵙ',
  '📰 Article Sponsorisé':'📰 ⴰⵔⵜⵉⵙⵍⴻ ⵙⴱⵓⵏⵙⵓⵔⵉⵙⴻ',
  '📰 Presse/Actualités':'📰 ⴱⵔⴻⵙⵙⴻ/ⴰⵙⵜⵓⴰⵍⵉⵜⴻⵙ',
  '📱 App mobile':'📱 ⴰⴱⴱ ⵎⵓⴱⵉⵍⴻ',
  '📱 Electronique':'📱 ⴻⵍⴻⵙⵜⵔⵓⵏⵉⵇⵓⴻ',
  '📱 Installer DZ Diaspora sur Android':'📱 ⵉⵏⵙⵜⴰⵍⵍⴻⵔ ⴷⵣ ⴷⵉⴰⵙⴱⵓⵔⴰ ⵙⵓⵔ ⴰⵏⴷⵔⵓⵉⴷ',
  '📱 Mon cabinet apparaît-il sur l application ?':'📱 ⵎⵓⵏ ⵙⴰⴱⵉⵏⴻⵜ ⴰⴱⴱⴰⵔⴰⵉⵜ-ⵉⵍ ⵙⵓⵔ ⵍ ⴰⴱⴱⵍⵉⵙⴰⵜⵉⵓⵏ ?',
  '📱 Site + Application':'📱 ⵙⵉⵜⴻ + ⴰⴱⴱⵍⵉⵙⴰⵜⵉⵓⵏ',
  '📱 Telecharger l app':'📱 ⵜⴻⵍⴻⵙⵀⴰⵔⴳⴻⵔ ⵍ ⴰⴱⴱ',
  '📱 Telephone, tablette, ordinateur, appareil photo':'📱 ⵜⴻⵍⴻⴱⵀⵓⵏⴻ, ⵜⴰⴱⵍⴻⵜⵜⴻ, ⵓⵔⴷⵉⵏⴰⵜⴻⵓⵔ, ⴰⴱⴱⴰⵔⴻⵉⵍ ⴱⵀⵓⵜⵓ',
  '🔍 Objets Trouves':'🔍 ⵓⴱⵊⴻⵜⵙ ⵜⵔⵓⵓⴼⴻⵙ',
  '🔍 Rechercher mon tribunal sur mjustice.dz':'🔍 ⵔⴻⵙⵀⴻⵔⵙⵀⴻⵔ ⵎⵓⵏ ⵜⵔⵉⴱⵓⵏⴰⵍ ⵙⵓⵔ ⵎⵊⵓⵙⵜⵉⵙⴻ.ⴷⵣ',
  '🔍 Verifications essentielles avant tout achat':'🔍 ⴼⴻⵔⵉⴼⵉⵙⴰⵜⵉⵓⵏⵙ ⴻⵙⵙⴻⵏⵜⵉⴻⵍⵍⴻⵙ ⴰⴼⴰⵏⵜ ⵜⵓⵓⵜ ⴰⵙⵀⴰⵜ',
  '🔍 Vérification professionnelle':'🔍 ⴼⴻⵔⵉⴼⵉⵙⴰⵜⵉⵓⵏ ⴱⵔⵓⴼⴻⵙⵙⵉⵓⵏⵏⴻⵍⵍⴻ',
  '🔎 Rechercher mon objet':'🔎 ⵔⴻⵙⵀⴻⵔⵙⵀⴻⵔ ⵎⵓⵏ ⵓⴱⵊⴻⵜ',
  '🔐 Admin Pro':'🔐 ⴰⴷⵎⵉⵏ ⴱⵔⵓ',
  '🔐 Code secret (signe distinctif connu du seul proprietaire) *':'🔐 ⵙⵓⴷⴻ ⵙⴻⵙⵔⴻⵜ (ⵙⵉⴳⵏⴻ ⴷⵉⵙⵜⵉⵏⵙⵜⵉⴼ ⵙⵓⵏⵏⵓ ⴷⵓ ⵙⴻⵓⵍ ⴱⵔⵓⴱⵔⵉⴻⵜⴰⵉⵔⴻ) *',
  '🔐 Mon compte':'🔐 ⵎⵓⵏ ⵙⵓⵎⴱⵜⴻ',
  '🔐 Page Admin — Accès restreint':'🔐 ⴱⴰⴳⴻ ⴰⴷⵎⵉⵏ — ⴰⵙⵙⴻⵙ ⵔⴻⵙⵜⵔⴻⵉⵏⵜ',
  '🔐 Votre code secret (signe distinctif) *':'🔐 ⴼⵓⵜⵔⴻ ⵙⵓⴷⴻ ⵙⴻⵙⵔⴻⵜ (ⵙⵉⴳⵏⴻ ⴷⵉⵙⵜⵉⵏⵙⵜⵉⴼ) *',
  '🔑 Cles':'🔑 ⵙⵍⴻⵙ',
  '🔑 Cles (voiture, maison, cadenas...)':'🔑 ⵙⵍⴻⵙ (ⴼⵓⵉⵜⵓⵔⴻ, ⵎⴰⵉⵙⵓⵏ, ⵙⴰⴷⴻⵏⴰⵙ...)',
  '🔑 Location':'🔑 ⵍⵓⵙⴰⵜⵉⵓⵏ',
  '🔒 Application 100% securisee':'🔒 ⴰⴱⴱⵍⵉⵙⴰⵜⵉⵓⵏ 100% ⵙⴻⵙⵓⵔⵉⵙⴻⴻ',
  '🔒 Gardien':'🔒 ⴳⴰⵔⴷⵉⴻⵏ',
  '🔒 Mes coordonnées sont-elles protégées ?':'🔒 ⵎⴻⵙ ⵙⵓⵓⵔⴷⵓⵏⵏⴻⴻⵙ ⵙⵓⵏⵜ-ⴻⵍⵍⴻⵙ ⴱⵔⵓⵜⴻⴳⴻⴻⵙ ?',
  '🔔 Préférences de notification *':'🔔 ⴱⵔⴻⴼⴻⵔⴻⵏⵙⴻⵙ ⴷⴻ ⵏⵓⵜⵉⴼⵉⵙⴰⵜⵉⵓⵏ *',
  '🔥 Firebase Console':'🔥 ⴼⵉⵔⴻⴱⴰⵙⴻ ⵙⵓⵏⵙⵓⵍⴻ',
  '🔧 Service':'🔧 ⵙⴻⵔⴼⵉⵙⴻ',
  '🔧 Services':'🔧 ⵙⴻⵔⴼⵉⵙⴻⵙ',
  '🕌 Tourisme religieux':'🕌 ⵜⵓⵓⵔⵉⵙⵎⴻ ⵔⴻⵍⵉⴳⵉⴻⵓⵅ',
  '🖨️ Générer et imprimer le contrat / طباعة العقد':'🖨 ⴳⴻⵏⴻⵔⴻⵔ ⴻⵜ ⵉⵎⴱⵔⵉⵎⴻⵔ ⵍⴻ ⵙⵓⵏⵜⵔⴰⵜ / طباعة العقد',
  '🖨️ Imprimer':'🖨 ⵉⵎⴱⵔⵉⵎⴻⵔ',
  '🖼️ Bannière Display':'🖼 ⴱⴰⵏⵏⵉⴻⵔⴻ ⴷⵉⵙⴱⵍⴰⵢ',
  '🗑️ Effacer la signature / مسح التوقيع':'🗑 ⴻⴼⴼⴰⵙⴻⵔ ⵍⴰ ⵙⵉⴳⵏⴰⵜⵓⵔⴻ / مسح التوقيع',
  '🗑️ Vider le formulaire':'🗑 ⴼⵉⴷⴻⵔ ⵍⴻ ⴼⵓⵔⵎⵓⵍⴰⵉⵔⴻ',
  '🗺️ Les 69 Wilayas d Algerie':'🗺 ⵍⴻⵙ 69 ⵡⵉⵍⴰⵢⴰⵙ ⴷ ⴰⵍⴳⴻⵔⵉⴻ',
  '🗺️ Wilayas':'🗺 ⵡⵉⵍⴰⵢⴰⵙ',
  '🚀 Nos offres':'🚀 ⵏⵓⵙ ⵓⴼⴼⵔⴻⵙ',
  '🚌 Bus international':'🚌 ⴱⵓⵙ ⵉⵏⵜⴻⵔⵏⴰⵜⵉⵓⵏⴰⵍ',
  '🚌 Proche transport':'🚌 ⴱⵔⵓⵙⵀⴻ ⵜⵔⴰⵏⵙⴱⵓⵔⵜ',
  '🚖 Taxi et VTC':'🚖 ⵜⴰⵅⵉ ⴻⵜ ⴼⵜⵙ',
  '🚗 Parking':'🚗 ⴱⴰⵔⴽⵉⵏⴳ',
  '🚗 Retour definitif — CCR et franchise douaniere vehicule':'🚗 ⵔⴻⵜⵓⵓⵔ ⴷⴻⴼⵉⵏⵉⵜⵉⴼ — ⵙⵙⵔ ⴻⵜ ⴼⵔⴰⵏⵙⵀⵉⵙⴻ ⴷⵓⵓⴰⵏⵉⴻⵔⴻ ⴼⴻⵀⵉⵙⵓⵍⴻ',
  '🚗 Vehicule':'🚗 ⴼⴻⵀⵉⵙⵓⵍⴻ',
  '🚨 Regle d or':'🚨 ⵔⴻⴳⵍⴻ ⴷ ⵓⵔ',
  '🚨 Securite':'🚨 ⵙⴻⵙⵓⵔⵉⵜⴻ',
  '🚨 Urgent':'🚨 ⵓⵔⴳⴻⵏⵜ',
  '🚩 Signaler une erreur':'🚩 ⵙⵉⴳⵏⴰⵍⴻⵔ ⵓⵏⴻ ⴻⵔⵔⴻⵓⵔ',
  '🛗 Ascenseur':'🛗 ⴰⵙⵙⴻⵏⵙⴻⵓⵔ',
  '🦷 Dentiste':'🦷 ⴷⴻⵏⵜⵉⵙⵜⴻ',
  '🦷 Dentiste / طبيب أسنان':'🦷 ⴷⴻⵏⵜⵉⵙⵜⴻ / طبيب اسنان',
  '🦷 Dentistes':'🦷 ⴷⴻⵏⵜⵉⵙⵜⴻⵙ',
  '🧠 Psychologue':'🧠 ⴱⵙⵢⵙⵀⵓⵍⵓⴳⵓⴻ',
  '🧳 Covoiturage':'🧳 ⵙⵓⴼⵓⵉⵜⵓⵔⴰⴳⴻ',
  '🧳 Covoiturage / Bagages':'🧳 ⵙⵓⴼⵓⵉⵜⵓⵔⴰⴳⴻ / ⴱⴰⴳⴰⴳⴻⵙ',
  '🧳 Douane — devises et bagages':'🧳 ⴷⵓⵓⴰⵏⴻ — ⴷⴻⴼⵉⵙⴻⵙ ⴻⵜ ⴱⴰⴳⴰⴳⴻⵙ',
  '🩺 Infirmier libéral':'🩺 ⵉⵏⴼⵉⵔⵎⵉⴻⵔ ⵍⵉⴱⴻⵔⴰⵍ',
  '🪪 Carte consulaire (immatriculation)':'🪪 ⵙⴰⵔⵜⴻ ⵙⵓⵏⵙⵓⵍⴰⵉⵔⴻ (ⵉⵎⵎⴰⵜⵔⵉⵙⵓⵍⴰⵜⵉⵓⵏ)',
};



// Observer les changements DOM pour traduire le contenu dynamique
var _kabActif = false;
var _observer = new MutationObserver(function(mutations) {
  if (_kabActif) {
    setTimeout(function() {
      document.querySelectorAll('a,button,h1,h2,h3,h4,li,span,p,td,th,label,div').forEach(function(el) {
        if (el.children.length === 0) {
          var t = el.textContent.trim();
          if (TRAD_KAB_SITE[t] && el.textContent !== TRAD_KAB_SITE[t]) {
            if (!_orig.has(el)) _orig.set(el, t);
            el.textContent = TRAD_KAB_SITE[t];
          }
        }
      });
    }, 300);
  }
});

function appliquerTamazight() {
  _kabActif = true;
  _observer.observe(document.body, {childList: true, subtree: true});
  document.querySelectorAll('a, button, h1, h2, h3, h4, li, span, p').forEach(el => {
    if (el.children.length === 0) {
      const texte = el.textContent.trim();
      if (!_orig.has(el)) _orig.set(el, texte);
      const trad = TRAD_KAB_SITE[texte];
      if (trad) el.textContent = trad;
    }
  });
}

function restaurerOriginal() {
  _orig.forEach((texte, el) => { el.textContent = texte; });
  _orig.clear();
}

function effacerCookies() {
  var d = window.location.hostname;
  var e = "expires=Thu, 01 Jan 1970 00:00:00 UTC";
  document.cookie = "googtrans=; " + e + "; path=/";
  document.cookie = "googtrans=; " + e + "; path=/; domain=" + d;
  document.cookie = "googtrans=; " + e + "; path=/; domain=." + d;
}

function changerLangueSite(codeLangue) {
  document.querySelectorAll(".lang-btn").forEach(b => b.classList.remove("active"));
  const btn = document.querySelector('.lang-btn[data-lang="' + codeLangue + '"]');
  if (btn) btn.classList.add("active");
  document.documentElement.dir = (codeLangue === 'ar') ? 'rtl' : 'ltr';

  effacerCookies();

  if (codeLangue === 'kab') {
    restaurerOriginal();
    setTimeout(appliquerTamazight, 200);
    return;
  }

  restaurerOriginal();

  if (codeLangue === 'fr') {
    window.location.reload();
    return;
  }

  var code = codeLangue === "zh" ? "zh-CN" : codeLangue;
  setTimeout(function() {
    document.cookie = "googtrans=/fr/" + code + "; path=/";
    document.cookie = "googtrans=/fr/" + code + "; path=/; domain=." + window.location.hostname;
    window.location.reload();
  }, 100);
}

window._gtDone = false;
function googleTranslateElementInit() {
  if (window._gtDone) return;
  window._gtDone = true;
  try {
    new google.translate.TranslateElement(
      { pageLanguage: "fr", includedLanguages: "fr,en,zh-CN,ar", autoDisplay: false },
      "google_translate_element"
    );
  } catch(e) {}
}

document.addEventListener("DOMContentLoaded", function () {
  var div = document.createElement("div");
  div.id = "google_translate_element";
  div.style.display = "none";
  document.body.appendChild(div);
  var gt = document.createElement("script");
  gt.src = "https://translate.google.com/translate_a/element.js?cb=googleTranslateElementInit";
  document.body.appendChild(gt);
  document.querySelectorAll(".lang-btn").forEach(b => b.classList.add("notranslate"));
});
